### PR TITLE
Closes #459 - Implemented stack trace sampling

### LINKED ISSUE #459: Add stack-trace sampling
It can be very hard to find a suitable instrumentation when only having a black-box look at applications.

For this prupose stack-trace sampling would be very useful: e.g., the user only needs to define an entrypoint scope, from which on the relevant calls will automatically be detected by performing stack-trace sampling.

From configuration perspective this could be realized as a special sensor which accepts scopes.

The hardest part will be to somehow reconstruct spans from the collect stack trace samples as spans and exporting them with OpenCensus.

**List of issues belonging to this epic:**

- [ ] Implement basic stack-trace sampling (#487)
- [ ] Use a dynamically configurable timer for stack trace sampling (#488)
- [ ] Make sampled trace work correctly with nested standard instrumentation (#490)
- [ ] Use Thread.dump for collecting stack traces (#491)
- [ ] Add documentation for stack trace sampling (#492)

### PR DESCRIPTION
**Pull request by JonasKunz**
CLsoes #459

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930)

### CODE REVIEW

**Review by Patrick-Eichhorn — COMMENTED** [review]
> Reviewed 30 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930)* status: all files reviewed, 18 unresolved discussions (waiting on @JonasKunz)

___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/CustomSpanBuilder.java, line 34 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIOlwr35BH9EWr64DFx:-MIOlwr35BH9EWr64DFy:b5hcbvd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/CustomSpanBuilder.java#L34)):*
> ```Java
> 
>     /**
>      * The startEndHandler member of {@link io.opencensus.implcore.trace.SpanBuilderImpl.Options}.
> ```

Comment: The timestampConverter member of (@link io.opencencus.implcore.internal.RecordEventsSpanImpl) ? 
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/Invocation.java, line 61 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIOvoQqBkGHVL_BE9fu:-MIOvoQqBkGHVL_BE9fv:bw649lo) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/Invocation.java#L61)):*
> ```Java
>      * Stored the invocation which happened directly after this invocation.
>      * This implies that nextSibling has the same parent.
>      * This field acts as a single linked lsit pointer for the list of children of the parent.
> ```

typo? (lsit pointer)
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/Invocation.java, line 133 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MISnzR-ExgT1Pcl_Fnj:-MISnzR-ExgT1Pcl_Fnk:bkyrj78) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/Invocation.java#L133)):*
> ```Java
> 
>     /**
>      * To preserve clarity of exported traces, we "hide" certain invocations, meaning that they will not be exported.
> ```

Note: talk about
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java, line 31 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIOy0Z-4TnfDqRvnGBR:-MIOy0Z-4TnfDqRvnGBS:b4e7olm) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java#L31)):*
> ```Java
>         }
> 
>         Invocation rootInvocation = new Invocation(null, null, null); //dummy object, just used as a lsit
> ```

typo list?
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java, line 49 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIOyoy76x0JaESCaZVb:-MIOyoy76x0JaESCaZVc:b-q8v18p) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java#L49)):*
> ```Java
>      * @param durations  an index for the method durations (computed via {@link #getMethodDurations(List)}
>      * @param startDepth the depth at which we start looking for the methods within the stack traces.
>      * @param output     All events from the "events" argument will be appended to this output list, but possibly ienhanced with better stack traces.
> ```

typo ienhanced?
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java, line 140 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP-W1Q3Sbdaz_9ZiEG:-MIP-W1Q3Sbdaz_9ZiEH:b-258fbq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java#L140)):*
> ```Java
>                 int endIndex = findLastEqualEvent(events, offset, depth);
>                 endIndex = extendEndToIncludeInstrumentations(events, offset, endIndex);
>                 if (offset != endIndex) { //at least to events have fallen into the range
> ```

typo two?
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/PlaceholderSpan.java, line 27 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP14vtEnuH-vSgzpky:-MIP14vtEnuH-vSgzpkz:bp4vcm2) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/PlaceholderSpan.java#L27)):*
> ```Java
> 
>     /**
>      * Stores teh attributes added to this span.
> ```

typo the
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java, line 51 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP28z_3KTOj_BkZex5:-MIP28z_3KTOj_BkZex6:b-1xbe1f) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java#L51)):*
> ```Java
> 
>     /**
>      * In order to recosntruct the stack trace, we need to know how many frames on the stack trace should be ignored.
> ```

typo reconstruct
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java, line 53 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP2IjY7UihvJ5GM4ZO:-MIP2IjY7UihvJ5GM4ZP:b2zdcss) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java#L53)):*
> ```Java
>      * In order to recosntruct the stack trace, we need to know how many frames on the stack trace should be ignored.
>      * For this purpose we need a stack trace of the method which started the stack-trace sampling.
>      * We capture the stack-trace by creating a new Throwable isntance (the constructor captures the stack trace).
> ```

typo instance
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java, line 60 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP70ak9ou2TL-gjRFf:-MIP70ak9ou2TL-gjRFg:byjz6n5) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java#L60)):*
> ```Java
> 
>     /**
>      * The span which acts as a root for all sampled methods.
> ```

is always an instrumented method? 
Where in the code is it prevented to start new threads (for stack trace sampling) with one instrumented method under another instrumented method?
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java, line 66 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP2YzqCzA3xkjEJYb8:-MIP2YzqCzA3xkjEJYb9:bdpyj8m) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java#L66)):*
> ```Java
>     /**
>      * The list storing the sequence of events.
>      * E.g. whenever a stack-trace sample is recorded, an isntrumented is entered or exited,
> ```

typo instrumented; instrumented method?
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java, line 128 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP5Gie3tTb9s2gQpRZ:-MIP5Gie3tTb9s2gQpR_:b-41w1m9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java#L128)):*
> ```Java
>      * @return a callback which must be invoked as soon as the method finishes.
>      */
>     public synchronized MethodExitNotifier newSpanStarted(PlaceholderSpan span, String className, String methodName) {
> ```

what dose the MethodExitNotifier do? Is the addExit method called instantly?
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java, line 139 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP6C4YB9vem_QVx-3K:-MIP6C4YB9vem_QVx-3L:b-ycak8r) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java#L139)):*
> ```Java
> 
>     /**
>      * Should be called when an instrumented method is called within this trace, which however does continue an exisitign span instead of creating a new one.
> ```

what means continued? When is this the case? or when is it needed?
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java, line 189 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP8tEN-tOE9jpjcswL:-MIP8tEN-tOE9jpjcswM:b-krqkfh) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java#L189)):*
> ```Java
>     }
> 
>     private void exportWithChildren(Invocation invoc, Span parentSpan) {
> ```

how exactly does this method work?
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/StackTraceSampler.java, line 147 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MISfInm3zg6hI6qnMCv:-MISfInm3zg6hI6qnMCw:bk5ino5) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/StackTraceSampler.java#L147)):*
> ```Java
> 
>     /**
>      * Continues a span but makes it's children stack-trace sampling aware.
> ```

when is this needed/called?
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/MethodHookConfigurationResolver.java, line 80 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIPDdDSAZA7tYdQdmVK:-MIPDdDSAZA7tYdQdmVL:b-mit2u) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/MethodHookConfigurationResolver.java#L80)):*
> ```Java
>             builder.errorStatus(getAndDetectConflicts(tracingRules, r -> r.getTracing()
>                     .getErrorStatus(), s -> !StringUtils.isEmpty(s), "error-status data key"));
>             builder.autoTracing(getAndDetectConflicts(tracingRules, r -> r.getTracing()
> ```

what happens at this point? and when :) 
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java, line 4 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIPE0pz7PSnGW8_BYzi:-MIPE0pz7PSnGW8_BYzj:b-b5p2uh) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java#L4)):*
> ```Java
> 
> import io.grpc.Context;
> import io.opencensus.common.Function;
> ```

what is this file for?
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGenerator.java, line 14 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIPER0X-7QroDy5E7if:-MIPER0X-7QroDy5E7ig:b-b5p2uh) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGenerator.java#L14)):*
> ```Java
> import rocks.inspectit.ocelot.config.model.instrumentation.rules.MetricRecordingSettings;
> import rocks.inspectit.ocelot.config.model.instrumentation.rules.RuleTracingSettings;
> import rocks.inspectit.ocelot.core.instrumentation.autotracing.StackTraceSampler;
> ```

what is this file for?

**Review by Patrick-Eichhorn — DISMISSED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Henning-Schulz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930)* status: all files reviewed, 1 unresolved discussion (waiting on @JonasKunz)

___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java, line 70 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIZs3cD2atEhvviQPRv:-MIZs3cE4cyWTS9MeHpU:b1x6fd1) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ceaa980608523ce62947876be705389ab21e98ba/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java#L70)):*
> ```Java
>                     while (currentDepth < trace.size() && !isSameMethod(trace.get(currentDepth), entryEvent)) {
>                         currentDepth++;
>                     } //after the loop, currentDepth is bigger than the trace OR points at the found span
> ```

If I understood correctly, `currentDepth` bigger than the trace means that something went wrong, as we have

```
entry method X --> stack trace not containing X --> exit X
```

It could make sense to highlight in the comment that this is a fallback (or, if I'm wrong, explain why/how it can happen).

**Review by JonasKunz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930)* status: all files reviewed, 1 unresolved discussion (waiting on @JonasKunz)

___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/CustomSpanBuilder.java, line 34 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIOlwr35BH9EWr64DFx:-MITImJgBI7AUN4q2V_a:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/CustomSpanBuilder.java#L34)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

Comment: The timestampConverter member of (@link io.opencencus.implcore.internal.RecordEventsSpanImpl) ? 
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/Invocation.java, line 61 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIOvoQqBkGHVL_BE9fu:-MITJ-a5EXrLcRA-Xqhe:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/Invocation.java#L61)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

typo? (lsit pointer)
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/Invocation.java, line 133 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MISnzR-ExgT1Pcl_Fnj:-MISstHX6WAYk29IiI3q:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/Invocation.java#L133)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

Note: talk about
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java, line 31 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIOy0Z-4TnfDqRvnGBR:-MITJFHVA1g_fHYHQwIz:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java#L31)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

typo list?
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java, line 49 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIOyoy76x0JaESCaZVb:-MITJKNA1Ury40iQXJHw:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java#L49)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

typo ienhanced?
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java, line 140 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP-W1Q3Sbdaz_9ZiEG:-MITJN_GBhC9sMAa_pVu:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java#L140)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

typo two?
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/PlaceholderSpan.java, line 27 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP14vtEnuH-vSgzpky:-MITJRTc1x2tAbhb22SY:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/PlaceholderSpan.java#L27)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

typo the
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java, line 51 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP28z_3KTOj_BkZex5:-MITJYfn8YOe1apFMPUo:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java#L51)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

typo reconstruct
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java, line 53 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP2IjY7UihvJ5GM4ZO:-MITJZjq5VIp4gc9eDia:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java#L53)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

typo instance
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java, line 60 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP70ak9ou2TL-gjRFf:-MIStUqJ9pUL-ysmyLk5:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java#L60)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

is always an instrumented method? 
Where in the code is it prevented to start new threads (for stack trace sampling) with one instrumented method under another instrumented method?
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java, line 66 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP2YzqCzA3xkjEJYb8:-MITJfgBECY-pFVvonSd:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java#L66)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

typo instrumented; instrumented method?
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java, line 128 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP5Gie3tTb9s2gQpRZ:-MISv-xm9pxCSfodjWYT:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java#L128)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

what dose the MethodExitNotifier do? Is the addExit method called instantly?
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java, line 139 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP6C4YB9vem_QVx-3K:-MISww96Ejyfb8udoVkE:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java#L139)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

what means continued? When is this the case? or when is it needed?
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java, line 189 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIP8tEN-tOE9jpjcswL:-MISyKBe0sR8KBfDfP_0:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java#L189)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

how exactly does this method work?
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/StackTraceSampler.java, line 147 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MISfInm3zg6hI6qnMCv:-MISyUc-A2SB7428qauP:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/StackTraceSampler.java#L147)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

when is this needed/called?
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/MethodHookConfigurationResolver.java, line 80 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIPDdDSAZA7tYdQdmVK:-MISz66S9aP0qR1jmysl:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/MethodHookConfigurationResolver.java#L80)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

what happens at this point? and when :) 
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java, line 4 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIPE0pz7PSnGW8_BYzi:-MISzV8n8O7NBG232I_o:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java#L4)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

what is this file for?
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGenerator.java, line 14 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/930#-MIPER0X-7QroDy5E7if:-MISzkZv6dCPdi5ZtR75:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/27496fc32bfeb8ee4470d9a1e5bd3d67bf14fc15/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGenerator.java#L14)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

what is this file for?
</blockquote></details>

Done.

**Pull request merged**
