### PR TITLE
Closes #1531 - Change base URL for the documentation website, when working on the documentation

### LINKED ISSUE #1531: [Feature] - Change base URL for the documentation website, when working on the documentation
**Is your feature request related to a problem? Please describe.**
When working on the documentation and starting the web preview, the start page of the documentation of the latest release is being shown and your changes won't be seen.
You have to manually go to xxx/inspectit-ocelot/docs/next/docs1 to see the current documentation you are working on.
(The default URL at the moment is xxx/inspectit-ocelot/docs/doc1)

**Describe the solution you'd like**
It would be nice to instantly get a web preview of the current documentation after startup, where you are working on.
So you don't always have to manually go to xxx/inspectit-ocelot/docs/next/docs1.

### PR DESCRIPTION
**Pull request by danipaniii**
Closes #1531

Now the base URL for starting the documentation website is set to xxx/inspectit-ocelot/docs/next/doc1, so when working on the documentation you don't have to always manually go to that URL.

- - -
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532)

### CODE REVIEW

**Review by mc-chaos — COMMENTED** [review]
Is the agent config only shown, if agent-command are configured? In the current Version agen-config could be shown without agent-command enabled.
Some environments do not have enabled agent-command, but would See corrent agen-config. Regards Sascha

**Comment by danipaniii** [comment]
Dear Sascha,
I think you commented on the wrong PR :D 
But to answer your question: In the current master branch it is still possible to see the agent-config eventhough the agent commands are not enabled. Once [https://github.com/inspectIT/inspectit-ocelot/pull/1528](url) PR is being merged to the master branch, this will not be possible anymore.
Kind Regards 
Daniel

**Comment by danipaniii** [comment]
Dear Sascha,
I have to  correct myself, indeed for the agent-config it is not necessary to have the agent commands enabled. I will update the documentation.
Also with the PR mentioned above, this will not be implemented, I must have mixed something up :D
Thanks a lot!
Kind Regards
Daniel

**Comment by heiko-holz** [comment]
Hi @danipaniii, thanks for the pull request!

I realized that you branched off another feature branch for this pull request instead of inspectIT Ocelot master branch.

The only change this PR brings is the change in the `index.html` file. 

I would recommend rebasing this branch to the master branch and only commit the update to the `index.html` file, and not the changes of other feature branches.

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532)* status: 0 of 27 files reviewed, 1 unresolved discussion (waiting on @danipaniii)

___
*[`inspectit-ocelot-documentation/website/static/index.html` line 7 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NGWUAxa6XGCj1g7fuGw:-NGWUAxb-sfh0HTTZMFe:b-kjnxxo) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d5fde56936802d45210a9c0f49fc23b07c5279ca/inspectit-ocelot-documentation/website/static/index.html#L7)):*
> ```HTML
>     <meta http-equiv="refresh" content="0; url=docs/next/doc1">
>     <script type="text/javascript">
>       window.location.href = 'docs/next/doc1';
> ```

where would this link point when the documentation is built and published online?

Online, it should point to `docs/doc1`

**Review by danipaniii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532)* status: 0 of 29 files reviewed, 1 unresolved discussion (waiting on @heiko-holz)

___
*[`inspectit-ocelot-documentation/website/static/index.html` line 7 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NGWUAxa6XGCj1g7fuGw:-NH9Lv1L524PlBEHrSd-:b-6vtb9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d5fde56936802d45210a9c0f49fc23b07c5279ca/inspectit-ocelot-documentation/website/static/index.html#L7)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

where would this link point when the documentation is built and published online?

Online, it should point to `docs/doc1`
</blockquote></details>

My guess is, it would probably point to docs/next/doc1. 
So now I changed the baseUrl in the siteConfig, so that when the documentation is started locally, the url will be /inspectit-ocelot/docs/next/doc1, if not, the url should be /inspectit/docs/doc1

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 19 files at r7, 1 of 1 files at r9, 7 of 14 files at r10, 7 of 13 files at r15, 13 of 14 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532)* status: all files reviewed, 3 unresolved discussions (waiting on @danipaniii)

___
*[`inspectit-ocelot-documentation/website/siteConfig.js` line 18 at r16](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHO5Yq-AwhlBPAqH1Ka:-NHO5Yq-AwhlBPAqH1Kb:b-m9ircs) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/912c547320bc3d03ddfd45ff3f549197af76c7d1/inspectit-ocelot-documentation/website/siteConfig.js#L18)):*
> ```JavaScript
>   tagline: 'Documentation of the inspectIT Ocelot Java Agent',
>   url: 'https://inspectit.github.io', // Your website URL
>   baseUrl: process.env.IS_LOCAL ? '/inspectit-ocelot/docs/next/doc1' : '/inspectit-ocelot/',
> ```

Can you add a comment why we need/want to set the `baseUrl` differently for local development and releases :)?
___
*[`inspectit-ocelot-documentation/website/siteConfig.js` line 19 at r16](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHO5OYj87frKslMEWMR:-NHO5OYj87frKslMEWMS:bw8wcuf) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/912c547320bc3d03ddfd45ff3f549197af76c7d1/inspectit-ocelot-documentation/website/siteConfig.js#L19)):*
> ```JavaScript
>   url: 'https://inspectit.github.io', // Your website URL
>   baseUrl: process.env.IS_LOCAL ? '/inspectit-ocelot/docs/next/doc1' : '/inspectit-ocelot/',
>   //baseUrl: '/inspectit-ocelot/', // Base URL for your project */
> ```

you could remove the comment `//baseUrl: '/inspectit-ocelot/'`



_Code quote:_
```JavaScript
process.env.IS_LOCAL
```
___
*[`inspectit-ocelot-documentation/website/static/index.html` line 7 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NGWUAxa6XGCj1g7fuGw:-NHO62G73KWmHaImpa23:bdf4vvo) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d5fde56936802d45210a9c0f49fc23b07c5279ca/inspectit-ocelot-documentation/website/static/index.html#L7)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

My guess is, it would probably point to docs/next/doc1. 
So now I changed the baseUrl in the siteConfig, so that when the documentation is started locally, the url will be /inspectit-ocelot/docs/next/doc1, if not, the url should be /inspectit/docs/doc1
</blockquote></details>

okay, should we then change it back here to `docs/doc1`?

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532)* status: all files reviewed, 5 unresolved discussions (waiting on @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/.yarn/install-state.gz` line 0 at r16](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHO6RCQ9vYnYbcC5bm7:-NHO6RCRBvDO1-nCaUpA:bnhino8) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/912c547320bc3d03ddfd45ff3f549197af76c7d1/components/inspectit-ocelot-configurationserver-ui/.yarn/install-state.gz#L0)):*
I think this file can be deleted
___
*[`inspectit-ocelot-documentation/website/.yarn/install-state.gz` line 0 at r16](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHO6W0O3jR1RCRtZAVn:-NHO6W0O3jR1RCRtZAVo:bhrxu52) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/912c547320bc3d03ddfd45ff3f549197af76c7d1/inspectit-ocelot-documentation/website/.yarn/install-state.gz#L0)):*
I think this file can be deleted.

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532)* status: all files reviewed, 6 unresolved discussions (waiting on @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/yarn.lock` line 5 at r17](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHOlmMP2gB-C5bh9rkW:-NHOlmMP2gB-C5bh9rkX:b8f22wm) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/94c73f695fff9493a5597ef0e593633a7414b90e/components/inspectit-ocelot-configurationserver-ui/yarn.lock#L5)):*
> ```YAML
> 
> __metadata:
>   version: 6
> ```

Before merging, we need to make sure that the `yarn.lock` does not introduce noisy installs.
I would suggest resetting the `yarn.lock` to the version of the `main` branch, and then re-running `yarn`

Why was this file changed anyhow? This PR should only affect the Documentation, not the Configuration Server
___
*[`inspectit-ocelot-documentation/website/siteConfig.js` line 14 at r17](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHOjhQ-11weWut0FaLO:-NHOjhQ-11weWut0FaLP:b-892rxa) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/94c73f695fff9493a5597ef0e593633a7414b90e/inspectit-ocelot-documentation/website/siteConfig.js#L14)):*
> ```JavaScript
> const users = [];
> 
> const siteConfig = {
> ```

I think the only changes now are in the code formatting.
Did you apply prettier, i.e., was the code formatting incorrect before?
___
*[`inspectit-ocelot-documentation/website/static/index.html` line 10 at r17](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHOlPn979zyfAsBEbzG:-NHOlPn979zyfAsBEbzH:b-xzsier) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/94c73f695fff9493a5597ef0e593633a7414b90e/inspectit-ocelot-documentation/website/static/index.html#L10)):*
> ```HTML
>       // If we wouldn't do that the URL on startup would be '/inspectit-ocelot/docs/doc1' showing us the documentation
>       // from the latest release
>       let re = new RegExp("(inspectit.github.io)|(www.inspectit.rocks)");
> ```

I think dropping `www` in front of `inspectit.rocks` would be sensible, as I can also access it via `https://inspectit.rocks` without `www.`
___
*[`inspectit-ocelot-documentation/website/static/index.html` line 11 at r17](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHOjphp7I43cb4HeTBE:-NHOjphp7I43cb4HeTBF:b-vcsfvd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/94c73f695fff9493a5597ef0e593633a7414b90e/inspectit-ocelot-documentation/website/static/index.html#L11)):*
> ```HTML
>       // from the latest release
>       let re = new RegExp("(inspectit.github.io)|(www.inspectit.rocks)");
>       console.log("OUTPUT: ", re.test(window.location.href));
> ```

in the final version, we need to remove the `console.log` statement

**Review by danipaniii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532)* status: 27 of 29 files reviewed, 5 unresolved discussions (waiting on @heiko-holz)

___
*[`inspectit-ocelot-documentation/website/siteConfig.js` line 18 at r16](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHO5Yq-AwhlBPAqH1Ka:-NHOpgQJ3Nvck37C_O8I:b-5x41xy) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/912c547320bc3d03ddfd45ff3f549197af76c7d1/inspectit-ocelot-documentation/website/siteConfig.js#L18)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Can you add a comment why we need/want to set the `baseUrl` differently for local development and releases :)?
</blockquote></details>

I added a comment in the index.html file, where we set the URL.
___
*[`inspectit-ocelot-documentation/website/siteConfig.js` line 14 at r17](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHOjhQ-11weWut0FaLO:-NHOpaWu4-eTybMIaOol:b-jjkrkg) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/94c73f695fff9493a5597ef0e593633a7414b90e/inspectit-ocelot-documentation/website/siteConfig.js#L14)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I think the only changes now are in the code formatting.
Did you apply prettier, i.e., was the code formatting incorrect before?
</blockquote></details>

I did apply prettier code formatting, because the config server UI tests did fail at the prettier part
___
*[`inspectit-ocelot-documentation/website/.yarn/install-state.gz` line  at r16](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHO6W0O3jR1RCRtZAVn:-NHOpuX6AmwiEg-z_SF5:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/912c547320bc3d03ddfd45ff3f549197af76c7d1/inspectit-ocelot-documentation/website/.yarn/install-state.gz#L)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I think this file can be deleted.
</blockquote></details>

Done.
___
*[`inspectit-ocelot-documentation/website/static/index.html` line 10 at r17](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHOlPn979zyfAsBEbzG:-NHOq1RmDreicgWu5t2V:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/94c73f695fff9493a5597ef0e593633a7414b90e/inspectit-ocelot-documentation/website/static/index.html#L10)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I think dropping `www` in front of `inspectit.rocks` would be sensible, as I can also access it via `https://inspectit.rocks` without `www.`
</blockquote></details>

Done.
___
*[`inspectit-ocelot-documentation/website/static/index.html` line 11 at r17](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHOjphp7I43cb4HeTBE:-NHOq1nV8f4xR7eQ0Pim:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/94c73f695fff9493a5597ef0e593633a7414b90e/inspectit-ocelot-documentation/website/static/index.html#L11)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

in the final version, we need to remove the `console.log` statement
</blockquote></details>

Done.
___
*[`components/inspectit-ocelot-configurationserver-ui/yarn.lock` line 5 at r17](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHOlmMP2gB-C5bh9rkW:-NHOq3H554Z9WZk7Wltz:b-nu130e) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/94c73f695fff9493a5597ef0e593633a7414b90e/components/inspectit-ocelot-configurationserver-ui/yarn.lock#L5)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Before merging, we need to make sure that the `yarn.lock` does not introduce noisy installs.
I would suggest resetting the `yarn.lock` to the version of the `main` branch, and then re-running `yarn`

Why was this file changed anyhow? This PR should only affect the Documentation, not the Configuration Server
</blockquote></details>

I copied the yarn.lock from master into this one

**Review by heiko-holz — COMMENTED** [review]
> Reviewed 2 of 2 files at r19.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532)* status: 27 of 31 files reviewed, all discussions resolved

___
*[`inspectit-ocelot-documentation/website/siteConfig.js` line 14 at r17](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532#-NHOjhQ-11weWut0FaLO:-NHP4CVX7LLsO-nMQFwF:bwic0rv) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/94c73f695fff9493a5597ef0e593633a7414b90e/inspectit-ocelot-documentation/website/siteConfig.js#L14)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

I did apply prettier code formatting, because the config server UI tests did fail at the prettier part
</blockquote></details>

Okay, thanks!

**Review by heiko-holz — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532)* status: 27 of 31 files reviewed, all discussions resolved

**Review by heiko-holz — APPROVED** [review]
> Reviewed 1 of 4 files at r20, 7 of 7 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1532)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @danipaniii)

**Pull request merged**
