### PR TITLE
Closes #1574: [Bug] - Span attributes not added when obfuscator is enabled

### LINKED ISSUE #1574: [Bug] - Span attributes not added when obfuscator is enabled
**Describe the bug**
When the `obfuscator` is enabled and an exceptions is added to a span's attributes, it is not converted via `toString()`, and we receive the following exception:
```Java
r.i.o.c.o.DynamicMultiSpanExporter       : Exception thrown in execute
java.lang.ClassCastException: class YOUR_EXCEPTION_CLASS cannot be cast to class java.lang.String (YOUR_EXCEPTION_CLASS is in unnamed module of loader YOUR_CLASS_LOADER; java.lang.String is in module java.base of loader 'bootstrap')
        at io.opentelemetry.exporter.internal.otlp.KeyValueMarshaler.create(KeyValueMarshaler.java:68)
        at io.opentelemetry.exporter.internal.otlp.KeyValueMarshaler.access$000(KeyValueMarshaler.java:30)
        at io.opentelemetry.exporter.internal.otlp.KeyValueMarshaler$1.accept(KeyValueMarshaler.java:47)
        at io.opentelemetry.exporter.internal.otlp.KeyValueMarshaler$1.accept(KeyValueMarshaler.java:42)
        at java.base/java.util.HashMap.forEach(HashMap.java:1337)
        at io.opentelemetry.sdk.internal.AttributesMap.forEach(AttributesMap.java:88)
        at io.opentelemetry.exporter.internal.otlp.KeyValueMarshaler.createRepeated(KeyValueMarshaler.java:41)
        at io.opentelemetry.exporter.internal.otlp.traces.SpanMarshaler.create(SpanMarshaler.java:44)
        at io.opentelemetry.exporter.internal.marshal.MarshalerUtil.groupByResourceAndScope(MarshalerUtil.java:67)
        at io.opentelemetry.exporter.internal.otlp.traces.ResourceSpansMarshaler.groupByResourceAndScope(ResourceSpansMarshaler.java:95)
        at io.opentelemetry.exporter.internal.otlp.traces.ResourceSpansMarshaler.create(ResourceSpansMarshaler.java:36)
        at io.opentelemetry.exporter.internal.otlp.traces.TraceRequestMarshaler.create(TraceRequestMarshaler.java:32)
        at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter.export(OtlpGrpcSpanExporter.java:54)
        at rocks.inspectit.ocelot.core.opentelemetry.DynamicMultiSpanExporter.lambda$export$0(DynamicMultiSpanExporter.java:44)
        at rocks.inspectit.ocelot.core.opentelemetry.DynamicMultiSpanExporter.execute(DynamicMultiSpanExporter.java:80)
        at rocks.inspectit.ocelot.core.opentelemetry.DynamicMultiSpanExporter.export(DynamicMultiSpanExporter.java:44)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.exportCurrentBatch(BatchSpanProcessor.java:326)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.run(BatchSpanProcessor.java:244)
        at java.base/java.lang.Thread.run(Unknown Source)
```

This is caused by the `create` method of the [OTEL KeyValueMarshaler](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/otlp/KeyValueMarshaler.java), which tries to cast the value to a String via `(String) value`, and not using `value.toString()`.

The cause is the implementation of the `rocks.inspectit.ocelot.core.privacy.obfuscation#putSpanAttribute(....)`.

**To Reproduce**

1. enable obfuscation via `inspectit.security.obfuscation.enabled=true`
2. instrument a method that throws an exception
3. see error log

**Expected behavior**
All possible attribute values need to be converted accordingly in the `rocks.inspectit.ocelot.core.privacy.obfuscation#putSpanAttribute(....)`.

The exceptions should be added as `exception.toString()` as the attribute value.

### PR DESCRIPTION
**Pull request by heiko-holz**
Closes #1574

- - -
This change is [Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1575)

### CODE REVIEW

**Review by quandor — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1575)* status: all files reviewed, 3 unresolved discussions (waiting on @heiko-holz)

___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/OtlpTraceExporterService.java` line 66 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1575#-NNkhB_B9USU1cpS6Slm:-NNkhB_B9USU1cpS6Sln:bd6suwh) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/90aa908294a76a8cd4f4e2da8f138494559fee28/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/OtlpTraceExporterService.java#L66)):*
> ```Java
>             OtlpTraceExporterSettings otlp = configuration.getExporters().getTracing().getOtlp();
> 
>             String endpoint = otlp.getEndpoint();
> ```

I saw that code in three different places so far. Is it possible to move that into `otlp.getEndpoint()`? In that way we would have easily at a single place.
___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/ExporterServiceIntegrationTestBase.java` line 297 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1575#-NNkhtAe3IZ5uSqnpI2c:-NNkhtAe3IZ5uSqnpI2d:bvkr74l) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/90aa908294a76a8cd4f4e2da8f138494559fee28/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/ExporterServiceIntegrationTestBase.java#L297)):*
> ```Java
>                 }
> 
>                 return (childSpan.get().getParentSpanId().equals(parentSpan.get().getSpanId()));
> ```

Those enclosing parenthesis are unnecessary, or am I missing something?
___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/privacy/obfuscation/ObfuscationManagerTest.java` line 294 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1575#-NNkndUaAjVdlFnlknf5:-NNkndUaAjVdlFnlknf6:b-vqbfgn) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/90aa908294a76a8cd4f4e2da8f138494559fee28/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/privacy/obfuscation/ObfuscationManagerTest.java#L294)):*
> ```Java
>             verifyNoMoreInteractions(span);
> 
>             // TODO: Boolean
> ```

Das TODO sieht für mich erledigt aus ;-)

**Comment by heiko-holz** [comment]
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/OtlpTraceExporterService.java` line 66 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1575#-NNkhB_B9USU1cpS6Slm:-NNlBKDy941cnhvMH55z:b-bock0k) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/90aa908294a76a8cd4f4e2da8f138494559fee28/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/OtlpTraceExporterService.java#L66)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

I saw that code in three different places so far. Is it possible to move that into `otlp.getEndpoint()`? In that way we would have easily at a single place.
</blockquote></details>

Yeah, good idea.
I agree.

However, I'd first like to talk to you about the "http-padding" that I introduced.

**Review by heiko-holz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1575)* status: 3 of 14 files reviewed, 3 unresolved discussions (waiting on @quandor)

___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/privacy/obfuscation/ObfuscationManagerTest.java` line 294 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1575#-NNkndUaAjVdlFnlknf5:-NNlBZDiENAq3dCQRjsM:br3rrnj) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/90aa908294a76a8cd4f4e2da8f138494559fee28/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/privacy/obfuscation/ObfuscationManagerTest.java#L294)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

Das TODO sieht für mich erledigt aus ;-)
</blockquote></details>

Yes, indeed.
I left it to see if the reviewer sees it ;) /joking

**Review by quandor — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1575#-:-NNpSNvY7AHremqzI0z_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @heiko-holz)

___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/OtlpTraceExporterService.java` line 66 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1575#-NNkhB_B9USU1cpS6Slm:-NNpS3sCBDThIk3aIqRa:bb6ywmx) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/90aa908294a76a8cd4f4e2da8f138494559fee28/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/OtlpTraceExporterService.java#L66)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Yeah, good idea.
I agree.

However, I'd first like to talk to you about the "http-padding" that I introduced.
</blockquote></details>

LGTM
___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/ExporterServiceIntegrationTestBase.java` line 297 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1575#-NNkhtAe3IZ5uSqnpI2c:-NNpS8h81aI16yrt6RZc:bn1wz0t) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/90aa908294a76a8cd4f4e2da8f138494559fee28/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/ExporterServiceIntegrationTestBase.java#L297)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Thanks for spotting.
I removed the redundant parentheses.
</blockquote></details>

:thumbsup:

**Pull request merged**
