### PR TITLE
Closes #966 - Resolve 'rt.bmr' data send by Boomerang plugin RT

### LINKED ISSUE #966: Resolve 'rt.bmr' data send by Boomerang plugin RT
The data contained in the 'rt.bmr' attribute, is a comma separated list.

See: http://akamai.github.io/boomerang/BOOMR.plugins.RT.html#toc1__anchor

    rt.bmr: Several parameters that include resource timing information for boomerang itself, ie, how long did boomerang take to load

Example: rt.bmr="37,1,2,2"

Each of these values should be available during the metric and tag processing.
As an example, the previous data could result in attributes similar to the following, divided according to their index:

    rt.bmr.0: 37
    rt.bmr.1: 1
    rt.bmr.2: 2
    rt.bmr.3: 2
    rt.bmr.sum: 42

### PR DESCRIPTION
**Pull request by Patrick-Eichhorn**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970)

### CODE REVIEW

**Review by mariusoe — DISMISSED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970)* status: all files reviewed, 3 unresolved discussions (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 32 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970#-MROQdkX4CydhA9-Qz5V:-MROQdkX4CydhA9-Qz5W:b-6um7yi) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b4716c4c61f4835007f55c21b6f426f862189168/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L32)):*
> ```
> targetAttribute != null && !targetAttribute.equals("")
> ```

Instead of this, you can also use the following method of Apache Commons:

```
StringUtils.isNotBlank(targetAttribute)
```
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 40 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970#-MROR0bFDqBaP-8RjfVr:-MROR0bFDqBaP-8RjfVs:b1qngqo) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b4716c4c61f4835007f55c21b6f426f862189168/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L40)):*
> ```Java
>                 beacon = beacon.merge(Collections.singletonMap(resultKey, attributes[i]));
> 
>                 sum += Integer.parseInt(attributes[i]);
> ```

We should wrap this in a try/catch block, in case the number is not a valid number. In that case, this would stop the processing of the bmr Attribute.
___
*[components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java, line 23 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970#-MRORiZA95cjvYf35jGu:-MRORiZBBZNHFgJaSvby:b-wn7xuf) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b4716c4c61f4835007f55c21b6f426f862189168/components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java#L23)):*
> ```Java
>     @Nested
>     public class Process {
> ```

Can you add three more tests to check whats happening when the `bmr` attribute is like:
* `1,,1`
  * I would expect: `bmr.0 = 1`,`bmr.2 = 1`, `bmr.sum = 2`
* `1,not a number,1`
  * I would expect: `bmr.0 = 1`,`bmr.2 = 1`, `bmr.sum = 2`
* `abc`
  * I would expect: `bmr.0` and `bmr.sum` does not exist

**Review by Patrick-Eichhorn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @mariusoe)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 32 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970#-MROQdkX4CydhA9-Qz5V:-MROiUaxDKkPy9lZMhQX:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b4716c4c61f4835007f55c21b6f426f862189168/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L32)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> targetAttribute != null && !targetAttribute.equals("")
> ```

Instead of this, you can also use the following method of Apache Commons:

```
StringUtils.isNotBlank(targetAttribute)
```
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 40 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970#-MROR0bFDqBaP-8RjfVr:-MROiVwZ3z2sQR1EAkSc:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b4716c4c61f4835007f55c21b6f426f862189168/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L40)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

We should wrap this in a try/catch block, in case the number is not a valid number. In that case, this would stop the processing of the bmr Attribute.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java, line 23 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970#-MRORiZA95cjvYf35jGu:-MROiXafAoNOsggxfwrI:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b4716c4c61f4835007f55c21b6f426f862189168/components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java#L23)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Can you add three more tests to check whats happening when the `bmr` attribute is like:
* `1,,1`
  * I would expect: `bmr.0 = 1`,`bmr.2 = 1`, `bmr.sum = 2`
* `1,not a number,1`
  * I would expect: `bmr.0 = 1`,`bmr.2 = 1`, `bmr.sum = 2`
* `abc`
  * I would expect: `bmr.0` and `bmr.sum` does not exist
</blockquote></details>

Done.

**Review by mariusoe — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970)* status: all files reviewed, 2 unresolved discussions (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 49 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970#-MRQD-2485Mx9sOKEpfn:-MRQD-2485Mx9sOKEpfo:b-bb8cn) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/7c7bb075a222b9716c436409df2ef0f910dc1f67/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L49)):*
> ```Java
>                 }
>             }
>             if (sum != 0) {
> ```

We should record `0` in case data exist.
___
*[components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java, line 23 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970#-MRORiZA95cjvYf35jGu:-MRQD3rp94FOvGjEfHWQ:bh4o7ax) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b4716c4c61f4835007f55c21b6f426f862189168/components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java#L23)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In my oppinion, we should record `0` as well.

As before, `abc` should not produce any data, but `0,0` should result in `bmr.0=0`, `bmr.1=0`, `bmr.sum=0`

**Review by Patrick-Eichhorn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @mariusoe)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 49 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970#-MRQD-2485Mx9sOKEpfn:-MRTe_uPD-ZS7TjfTI2H:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/7c7bb075a222b9716c436409df2ef0f910dc1f67/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L49)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

We should record `0` in case data exist.
</blockquote></details>

Done.

**Review by mariusoe — DISMISSED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970)* status: all files reviewed, 1 unresolved discussion (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 45 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970#-MRTfcpE1V_kRlhPSkID:-MRTfcpE1V_kRlhPSkIE:bwol5ft) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8f3ba5b836a9ded9cf9437b794222edfc42696b1/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L45)):*
> ```Java
>                     sum += Integer.parseInt(attributes[i]);
>                     beacon = beacon.merge(Collections.singletonMap(resultKey, attributes[i]));
>                     beacon = beacon.merge(Collections.singletonMap(ATTRIBUTE_KEY + ".sum", String.valueOf(sum)));
> ```

Can you move this out of the loop. Now, the sum is merged into the beacon after each attribute, even there are more attributes left. Basically, this has to be done only once after the loop - actually, like it was before just without the if statement. :-)

**Review by mariusoe — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
