### PR TITLE
Closes  #1291: Extend the Configuration UI to display Configuration Documentation

### LINKED ISSUE #1291: Extend the Configuration UI so that the Configuration Documentation can be displayed
The goal of this ticket is to extend the web UI of the configuration server by a new view showing a configuration documentation.

The displayed configuration documentation should refer to an agent mapping selected by the user. It should therefore be possible to select a specific agent mapping on the basis of its name. As soon as a user saves a configuration file, the documentation should be updated.

It would be good if the documentation can be displayed at the same time (side by side) to the configuration editor.

### PR DESCRIPTION
**Pull request by aaronweissler**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1317)

### CODE REVIEW

**Review by mariusoe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1317)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @aaronweissler and @mariusoe)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/configuration/ConfigurationController.java, line 126 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1317#-MwgBQCa5yCVri5z2f7e:-MwgBQCa5yCVri5z2f7f:b-22nifa) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/effff658d40af03453630eae7917ee914972af65/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/configuration/ConfigurationController.java#L126)):*
> ```Java
>                     configYaml = yaml.dump(combined);
>                 } catch (Exception e) {
>                     log.error("Could not get contents of DefaultConfig. Will continue without including it.", e);
> ```

Imo it would be better to combine this error with the one below (generating the docs failed). So in case the user want to include the default configurations but there is an error, it should fail and not returning the docs without the default ones included. That would be confusing and wrong.

**Review by aaronweissler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1317)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @mariusoe)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/configuration/ConfigurationController.java, line 126 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1317#-MwgBQCa5yCVri5z2f7e:-MwlIQt21gyLY_-rxMdK:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/effff658d40af03453630eae7917ee914972af65/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/configuration/ConfigurationController.java#L126)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Imo it would be better to combine this error with the one below (generating the docs failed). So in case the user want to include the default configurations but there is an error, it should fail and not returning the docs without the default ones included. That would be confusing and wrong.
</blockquote></details>

Done.

**Review by mariusoe — COMMENTED** [review]
> Reviewed 7 of 9 files at r1, 12 of 17 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1317)* status: 15 of 19 files reviewed, all discussions resolved (waiting on @mariusoe)

**Review by mariusoe — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1317)* status: 16 of 19 files reviewed, all discussions resolved (waiting on @mariusoe)

**Review by mariusoe — APPROVED** [review]
> Reviewed 3 of 17 files at r6.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1317)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronweissler)

**Pull request merged**
