### PR TITLE
Closes #1048 - Extend the 'illegal tag value' error message, to specify which tag is concerned

### LINKED ISSUE #1048: Extend the "illegal tag value" error message, to specify which tag is concerned.
It is helpful to know which tag is affected by the error message.

### PR DESCRIPTION
**Pull request by Mahir-Isikli**
closes #1048

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1052)

### CODE REVIEW

**Review by Patrick-Eichhorn — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1052)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @Mahir-Isikli and @Patrick-Eichhorn)

___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java, line 330 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1052#-MZMz7Y36UqIuOv0Eaca:-MZMz7Y36UqIuOv0Eacb:b9zsfrz) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/09229074d63cda3b2c5ef8328bfc3afd994de113/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java#L330)):*
> ```Java
>         TagContextBuilder builder = Tags.getTagger().emptyBuilder();
>         dataTagsStream().forEach(e -> builder.putLocal(TagKey.create(e.getKey()), TagUtils.createTagValue(e.getKey()
>                 .toString(), e.getValue().toString())));
> ```

.toString() is redundant. The key of the map is a String. 
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java, line 562 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1052#-MZMzfjK2eKV9oDPk8CC:-MZMzfjK2eKV9oDPk8CD:b9zsfrz) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/09229074d63cda3b2c5ef8328bfc3afd994de113/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java#L562)):*
> ```Java
>                 .filter(e -> ALLOWED_TAG_TYPES.contains(e.getValue().getClass()))
>                 .map(e -> Tag.create(TagKey.create(e.getKey()), TagUtils.createTagValue(e.getKey()
>                         .toString(), e.getValue()
> ```

.toString() is redundant. The key of the map is a String. 
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/MetricsRecorder.java, line 65 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1052#-MZN0Dg44Xc0AVB70E-d:-MZN0Dg58fT3LKLTHSg-:b-6lv0vk) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/09229074d63cda3b2c5ef8328bfc3afd994de113/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/MetricsRecorder.java#L65)):*
> ```Java
>         commonTagsManager.getCommonTagKeys()
>                 .forEach(commonTagKey -> Optional.ofNullable(inspectitContext.getData(commonTagKey.getName()))
>                         .ifPresent(value -> builder.putLocal(commonTagKey, TagUtils.createTagValue(commonTagKey.toString(), value
> ```

commonTagKey is of type "TagKey", you can get access of the name with the mehtod getName() -> commonTagKey.getName() 
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/MetricsRecorder.java, line 75 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1052#-MZN-uK66IsrvTet33hz:-MZN-uK66IsrvTet33i-:b9zsfrz) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/09229074d63cda3b2c5ef8328bfc3afd994de113/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/MetricsRecorder.java#L75)):*
> ```Java
>         metricAccessor.getDataTagAccessors()
>                 .forEach((key, accessor) -> Optional.ofNullable(accessor.get(context))
>                         .ifPresent(tagValue -> builder.putLocal(TagKey.create(key), TagUtils.createTagValue(key.toString(), tagValue
> ```

.toString() is redundant. The key of the map is a String.

**Review by Patrick-Eichhorn — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1052#-:-MZS6OQH8PpJ9ljRUz1p:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @Mahir-Isikli)

**Review by Mahir-Isikli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1052)* status: all files reviewed, 4 unresolved discussions (waiting on @Patrick-Eichhorn)

___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java, line 330 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1052#-MZMz7Y36UqIuOv0Eaca:-MZS7Etp7vECCC7EcXpR:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f565c0bd350d82149cb131867325d7c600faaa/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java#L330)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

.toString() is redundant. The key of the map is a String. 
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java, line 562 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1052#-MZMzfjK2eKV9oDPk8CC:-MZS7Hp2EeFG0KnNf2G_:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f565c0bd350d82149cb131867325d7c600faaa/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java#L562)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

.toString() is redundant. The key of the map is a String. 
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/MetricsRecorder.java, line 65 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1052#-MZN0Dg44Xc0AVB70E-d:-MZS7K9B58am2NEECRgJ:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f565c0bd350d82149cb131867325d7c600faaa/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/MetricsRecorder.java#L65)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

commonTagKey is of type "TagKey", you can get access of the name with the mehtod getName() -> commonTagKey.getName() 
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/MetricsRecorder.java, line 75 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1052#-MZN-uK66IsrvTet33hz:-MZS7KVoE7WpHPfnYnB9:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f565c0bd350d82149cb131867325d7c600faaa/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/MetricsRecorder.java#L75)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

.toString() is redundant. The key of the map is a String. 
</blockquote></details>

Done.

**Review by Patrick-Eichhorn — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1052)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Mahir-Isikli)

**Pull request merged**
