### PR TITLE
Tag guard

### PR DESCRIPTION
**Pull request by EddeCCC**
Add TagGuard, which enables to limit all or specific tags in measurements

- - -
This change is [Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1625)

### CODE REVIEW

**Review by TitusLabs — DISMISSED** [review]
> Reviewed 1 of 9 files at r1, 8 of 23 files at r2, 7 of 255 files at r3, 223 of 240 files at r4, 1 of 2 files at r6, 33 of 35 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1625)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Dimi-Ma)

**Review by Dimi-Ma — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 8 of 23 files at r2, 7 of 255 files at r3, 229 of 240 files at r4, 1 of 2 files at r6, 33 of 35 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1625)* status: all files reviewed, 5 unresolved discussions (waiting on @EddeCCC)

___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/ExporterServiceIntegrationTestBase.java` line 330 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1625#-NktUaqr2s-quUPyumqw:-NktUaqr2s-quUPyumqx:b-9xdpnz) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b1567ef217ca583b78cc7f4f171322e9b030e8e6/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/ExporterServiceIntegrationTestBase.java#L330)):*
> ```Java
>         }
> 
>         public List<ExportMetricsServiceRequest> getMetricRequests() {
> ```

This function seems to not be used and could be removed
___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/ExporterServiceIntegrationTestBase.java` line 373 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1625#-NktUiqK-etwyNFL1qkt:-NktUiqK-etwyNFL1qku:bnj7hl0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b1567ef217ca583b78cc7f4f171322e9b030e8e6/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/ExporterServiceIntegrationTestBase.java#L373)):*
> ```Java
>     }
> 
>     public OtlpGrpcServer getGrpcServer() {
> ```

same as above
___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthIncidentBufferTest.java` line 39 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1625#-NktqoHjDfUQ0Xtr8DiY:-NktqoHjDfUQ0Xtr8DiZ:b7mk886) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/336160c3027c800343bce5a9af3d2aad21ab2050/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthIncidentBufferTest.java#L39)):*
> ```Java
>     }
>     @Test
>     void verifyBufferSize() {
> ```

this test is redundant.
___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManagerDeadlockGh1597IntTest.java` line 52 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1625#-NkttHmL3_Sy6Z0lCAiY:-NkttHmL3_Sy6Z0lCAiZ:b-79mss3) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b1567ef217ca583b78cc7f4f171322e9b030e8e6/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManagerDeadlockGh1597IntTest.java#L52)):*
> ```Java
>             long start = System.currentTimeMillis();
>             while (System.currentTimeMillis() - start < millisToRun) {
>                 cut.invalidateIncident(cut.getClass(), "Invalidation due to invalidator event");
> ```

Maybe it would be better to use a more descriptive message here.
___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManagerTest.java` line 41 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1625#-NkuFvPB-2fAuAIc4YeR:-NkuFvPB-2fAuAIc4YeS:b-4k89uy) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b1567ef217ca583b78cc7f4f171322e9b030e8e6/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManagerTest.java#L41)):*
> ```Java
> 
>         @Test
>         void verifyAgentHealthChangedEvent() {
> ```

This Test exists 2 times with the same name, one with invalidator as null and one where its set. Do these tests show the same result? The other test is under the nested class ``TimeoutHealth`` if its supposed to show something different it is not apparent from how the test is written. (goes for the other tests too since there are some duplicates with only the `ìnvalidator`` being a different value but having the same test name.

**Review by Dimi-Ma — CHANGES_REQUESTED** [review]
> Reviewed 65 of 65 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1625)* status: all files reviewed, 2 unresolved discussions (waiting on @EddeCCC)

___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthIncidentBufferTest.java` line 39 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1625#-NktqoHjDfUQ0Xtr8DiY:-Nl7DCwm2pwJUwcKnLUQ:bmr5xbn) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/336160c3027c800343bce5a9af3d2aad21ab2050/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthIncidentBufferTest.java#L39)):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

this test is redundant.
</blockquote></details>

Expected value is mocked so the test case is not valid and can be removed. 
___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManagerTest.java` line 41 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1625#-NkuFvPB-2fAuAIc4YeR:-Nl7HymEDKIxsajz0sH4:bo4ghzr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b1567ef217ca583b78cc7f4f171322e9b030e8e6/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManagerTest.java#L41)):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

This Test exists 2 times with the same name, one with invalidator as null and one where its set. Do these tests show the same result? The other test is under the nested class ``TimeoutHealth`` if its supposed to show something different it is not apparent from how the test is written. (goes for the other tests too since there are some duplicates with only the `ìnvalidator`` being a different value but having the same test name.
</blockquote></details>

The changes are fine but the naming can still be improved. It would be better to have a distinct name for each test to represent what is being tested in it.

**Review by Dimi-Ma — APPROVED** [review]
> Reviewed 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1625)* status: all files reviewed, 2 unresolved discussions (waiting on @EddeCCC)

___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/WriteSpanAttributesAction.java` line 4 at r10](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1625#-Nl7iHtjBzimTiQHcJqP:-Nl7iHtjBzimTiQHcJqQ:b-c6zvo1) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2907a066846ac9f5c17b8f347a57ed8d108a7a52/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/WriteSpanAttributesAction.java#L4)):*
> ```Java
> 
> import io.opentelemetry.api.trace.Span;
> import lombok.*;
> ```

Do we want to group together imports of the same library if so when should be the the trigger set? 
___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGeneratorTest.java` line 30 at r10](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1625#-Nl7jFJtA5VA2YfK7yLr:-Nl7jFJtA5VA2YfK7yLs:b-889o9f) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2907a066846ac9f5c17b8f347a57ed8d108a7a52/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGeneratorTest.java#L30)):*
> ```Java
> import rocks.inspectit.ocelot.core.testutils.Dummy;
> 
> import java.util.*;
> ```

Same here, is this grouping really needed?

**Comment by EddeCCC** [comment]
Pull-Requested was approved. By-Passing to avoid unnecessary delay.

**Pull request merged**
