### PR TITLE
Updates dependency to recent versions

### PR DESCRIPTION
**Pull request by quandor**
Most of the dependencies are now managed via spring-boot dependency management. That means an upgrade of spring-boot version updates automatically dependencies managed by spring-boot and guarantees compatibility.
All other versions are managed in a single file (gradle.properties). Usually those versions are the most current ones. If that is not the case a comment should explain why not.

- - -
This change is [Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584)

### CODE REVIEW

**Review by quandor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584)* status: 0 of 20 files reviewed, 2 unresolved discussions

___
*[`.github/workflows/agent_test.yml` line 29 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584#-NOsLam7EalzBYPx-tNh:-NOsLam91YUEvE7yxTpb:b-cj2wqf) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/5f060d538692a478330ef87ad30f378c238be5e5/.github/workflows/agent_test.yml#L29)):*
> ```YAML
>           - 'ibmcom/ibmjava:8-sdk'
>           - 'eclipse-temurin:8'
>           - 'eclipse-temurin:11'
> ```

I included the following information in the corresponding commit comment. That ensures that reasons for this decision are not completely lost in a distant future.

Why did I change those images?

* The images of sgrio are at least two years old.
    See https://hub.docker.com/r/sgrio/java
* Images from openjdk are deprecated.
    See https://hub.docker.com/_/openjdk

eclipse-temurin are the official openjdk builds. Since they are based on
ubuntu (as far as the comitter understands it) there is no reason for
ubuntu specific images in the build matrix anymore.
___
*[`inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/ExecutorContextPropagationTest.java` line 65 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584#-NOsLzML6MmDsl7sdHLm:-NOsLzML6MmDsl7sdHLn:b29jomn) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/5f060d538692a478330ef87ad30f378c238be5e5/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/ExecutorContextPropagationTest.java#L65)):*
> ```Java
>             taskFuture.get();
> 
>             assertThat(refTags.get()).toIterable().hasSize(1)
> ```

That change was necessary to be able to use a current version of `assertj-core`.
___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/special/ScheduledExecutorContextPropagationSensorTest.java` line 31 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584#-NOsMZL35JdAgUStyITX:-NOsMZL5-ndNJJJoKQ2E:b-f0aie9) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/befee12e8cb5a3feca841ea918b437b33ca5dd50/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/special/ScheduledExecutorContextPropagationSensorTest.java#L31)):*
> ```Java
> 
>     @BeforeEach
>     private void beforeEach() {
> ```

That change was necessary to be able to use current versions of JUnit.

**Review by quandor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584)* status: 0 of 20 files reviewed, 1 unresolved discussion

___
*[`gradle.properties` line 59 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584#-NOsP6eD6tjBz7mjPy1J:-NOsP6eD6tjBz7mjPy1K:b4esb5a) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/5f060d538692a478330ef87ad30f378c238be5e5/gradle.properties#L59)):*
> ```INI
> piccoloVersion=1.0.3
> 
> # TODO Should we simply update that version? Was 3.24.1-GA
> ```

At least all tests are running. So I do not see any reason to not update to that newer version.

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584)* status: all files reviewed, 4 unresolved discussions (waiting on @quandor)

___
*[`gradle.properties` line 59 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584#-NOsP6eD6tjBz7mjPy1J:-NPXrnPeCvMiPn-mvKeY:b4lm0r4) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/5f060d538692a478330ef87ad30f378c238be5e5/gradle.properties#L59)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

At least all tests are running. So I do not see any reason to not update to that newer version.
</blockquote></details>

Yeah, I think we can upgrade.

However, there is a typo in `javassist`, i.e., the second **s** is missing (it should be javas**s**ist
___
*[`gradle.properties` line 75 at r2](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584#-NPXsHZB9haf0-Er6MfE:-NPXsHZB9haf0-Er6MfF:bcov9mp) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/399dcb84dbf9bcc93e6506aebb740bbba6607f91/gradle.properties#L75)):*
> ```INI
> 
> # Can we get safely newer? 3.15.7
> protobufJavaUtilVersion=3.21.12
> ```

I have no idea if an upgrade would smoothly work. What do you think?  Have you tried it out?
___
*[`inspectit-ocelot-core/build.gradle` line 49 at r2](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584#-NPXtNVV8gdfgypUmcdw:-NPXtNVV8gdfgypUmcdx:b26urnc) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/befee12e8cb5a3feca841ea918b437b33ca5dd50/inspectit-ocelot-core/build.gradle#L49)):*
> ```Gradle
> 
>     implementation(
>             platform("com.fasterxml.jackson:jackson-bom:${jacksonBomVersion}"),
> ```

how is jackson now managed?
___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/jmx/JmxMetricsRecorderTest.java` line 123 at r2](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584#-NPXvXEBEMlRIJ0xoYdq:-NPXvXEBEMlRIJ0xoYdr:b-twe63k) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/399dcb84dbf9bcc93e6506aebb740bbba6607f91/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/jmx/JmxMetricsRecorderTest.java#L123)):*
> ```Java
> 
>             TagContext tagContext = tagContextBuilder.build();
>             assertThat(InternalUtils.getTags(tagContext)).toIterable().isEmpty();
> ```

the calls to `toIterable()` are all needed due to an upgrade of `assertJ`, right?



_Code quote:_
```Java
InternalUt
```

**Review by quandor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584)* status: all files reviewed, 2 unresolved discussions (waiting on @heiko-holz)

___
*[`gradle.properties` line 59 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584#-NOsP6eD6tjBz7mjPy1J:-NPcyHim8E7_Dfb_1T5S:b-98glhl) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/5f060d538692a478330ef87ad30f378c238be5e5/gradle.properties#L59)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Yeah, I think we can upgrade.

However, there is a typo in `javassist`, i.e., the second **s** is missing (it should be javas**s**ist
</blockquote></details>

Deleted the TODO and changed to javassist.
___
*[`gradle.properties` line 75 at r2](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584#-NPXsHZB9haf0-Er6MfE:-NPcyXnFEEDz13Y_Ndbs:b-oi6zyj) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/399dcb84dbf9bcc93e6506aebb740bbba6607f91/gradle.properties#L75)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I have no idea if an upgrade would smoothly work. What do you think?  Have you tried it out?
</blockquote></details>

I just forgot to remove that comment. Since it is dependency we use for tests only and all tests are running, there is no real risk.
___
*[`inspectit-ocelot-core/build.gradle` line 49 at r2](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584#-NPXtNVV8gdfgypUmcdw:-NPcyn1AEkQpccMRWd4t:b-v4upy1) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/befee12e8cb5a3feca841ea918b437b33ca5dd50/inspectit-ocelot-core/build.gradle#L49)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

how is jackson now managed?
</blockquote></details>

Jackson is managed via the spring boot bom and the spring boot plugin.
___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/jmx/JmxMetricsRecorderTest.java` line 123 at r2](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584#-NPXvXEBEMlRIJ0xoYdq:-NPcyttx0mvEnAaF4XZg:bdkbqhj) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/399dcb84dbf9bcc93e6506aebb740bbba6607f91/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/jmx/JmxMetricsRecorderTest.java#L123)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

the calls to `toIterable()` are all needed due to an upgrade of `assertJ`, right?
</blockquote></details>

Yes, that is correct.

**Review by quandor — COMMENTED** [review]
> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584)* status: all files reviewed, 2 unresolved discussions (waiting on @heiko-holz)

**Review by heiko-holz — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1584)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @quandor)

**Pull request merged**
