### PR TITLE
Allow disabling console log on start-up

### PR DESCRIPTION
**Pull request by florinandone**
Allow disabling the console log before the log system is initialized

This is required to disable the log on console for:

`
2021-05-30 21:13:44,503 INFO 143 --- [inspectIT] [ Thread-0] rocks.inspectit.ocelot.core.AgentImpl : Starting inspectIT Ocelot Agent...
2021-05-30 21:13:44,504 INFO 144 --- [inspectIT] [ Thread-0] rocks.inspectit.ocelot.core.AgentImpl : Version: SNAPSHOT
2021-05-30 21:13:44,504 INFO 144 --- [inspectIT] [ Thread-0] rocks.inspectit.ocelot.core.AgentImpl : Build Date: Sun May 30 20:52:21 AEST 2021
2021-05-30 21:13:44,505 INFO 145 --- [inspectIT] [ Thread-0] rocks.inspectit.ocelot.core.AgentImpl : OpenCensus was loaded in inspectIT classloader
2021-05-30 21:13:45,035 INFO 675 --- [inspectIT] [ Thread-0] r.i.o.core.config.InspectitEnvironment : Registered Configuration Sources:
2021-05-30 21:13:45,035 INFO 675 --- [inspectIT] [ Thread-0] r.i.o.core.config.InspectitEnvironment : systemProperties
2021-05-30 21:13:45,036 INFO 676 --- [inspectIT] [ Thread-0] r.i.o.core.config.InspectitEnvironment : systemEnvironment
2021-05-30 21:13:45,036 INFO 676 --- [inspectIT] [ Thread-0] r.i.o.core.config.InspectitEnvironment : inspectitDefaults
2021-05-30 21:13:45,036 INFO 676 --- [inspectIT] [ Thread-0] r.i.o.core.config.InspectitEnvironment : inspectitEnvironment
`

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1095)

### CODE REVIEW

**Comment by florinandone** [comment]
@mariusoe Hi Marius,  Could you help with a review?
Does this make sense for you?
If not, is there any other way to stop the initial console output?
That is breaking some of our existing scripts.

**Comment by florinandone** [comment]
@Patrick-Eichhorn Could you help with a review on this?
If not good direction, I will try to find some other solution.

**Comment by mariusoe** [comment]
Hi @florinandone 

sorry for the late response but we were quite busy last week. Your PR and the idea of it looks good. I've added some unit tests to it and the abillity so that JVM property are also to be considered. Once the tests are done, I'll merge it.

Thanks for the contribution.

**Review by mariusoe — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1095)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @florinandone)

**Comment by florinandone** [comment]
Thank you, much appreciated.

**Pull request merged**
