### PR TITLE
Closes #1049 - Edit the 'illegal tag value' error message to be printed more than once

### LINKED ISSUE #1049: Edit the "illegal tag value" error message to be printed more than once.
Currently the `isWaringPrinted` flag is a static variable. If more than one tag is illegal, a warning is printed only for the first tag value. 
For this reason, it is better if the first X warnings are printed regularly after a certain waiting time.

### PR DESCRIPTION
**Pull request by Mahir-Isikli**
closes #1049

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064)

### CODE REVIEW

**Review by Patrick-Eichhorn — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Mahir-Isikli and @Patrick-Eichhorn)

___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/tags/TagUtils.java, line 12 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-M_0fqqe6L1Pw73rqqUr:-M_0fqqe6L1Pw73rqqUs:b-vasv31) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/5e4bba87071e91f7687cf3574b019d9dba53390d/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/tags/TagUtils.java#L12)):*
> ```Java
>     private static int printedWarningCounter = 0;
> 
>     private static int maxWarningPrints = 10;
> ```

Does not have to be static and can be final
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/tags/TagUtils.java, line 16 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-M_0gHuXEReJhU8zl19V:-M_0gHuY2RRWBFiHbl7Z:bic53hu) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/5e4bba87071e91f7687cf3574b019d9dba53390d/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/tags/TagUtils.java#L16)):*
> ```Java
>     private static long lastWarningTime = 0;
> 
>     private static int waitingTimeInMinutes = 10;
> ```

Does not have to be static and can be final
I think we can replace the minutes to seconds to allow a finer adjustment.
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/tags/TagUtilsTest.java, line 27 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-M_0eOQqCe8PcHM6IgrP:-M_0eOQqCe8PcHM6IgrQ:b-96i9vy) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/5e4bba87071e91f7687cf3574b019d9dba53390d/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/tags/TagUtilsTest.java#L27)):*
> ```Java
>         assertThat(TagUtils.createTagValue("my-tag-key", "non-printable-character-\u007f")).isEqualTo(TagValue.create("<invalid>"));
>     }
> ```

I think the tests do not work because the "printedWarningCounter" is static and already incremented by the previous tests (createTagValue_tooLong() and createTagValue_nonPrintableCharacter()). 
For this case you can make the printedWarningCounter public (package) and reset it to 0 for this test.
For such a case, we use the @VisibleforTesting annotation for the variable to make it clear why it is public.

**Review by Mahir-Isikli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Patrick-Eichhorn and @VisibleForTesting)

___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/tags/TagUtils.java, line 12 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-M_0fqqe6L1Pw73rqqUr:-M_6H-8w9gokuml1uzQK:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/5e4bba87071e91f7687cf3574b019d9dba53390d/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/tags/TagUtils.java#L12)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

Does not have to be static and can be final
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/tags/TagUtils.java, line 16 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-M_0gHuXEReJhU8zl19V:-M_6H-eX5K-xGylEf53m:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/5e4bba87071e91f7687cf3574b019d9dba53390d/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/tags/TagUtils.java#L16)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

Does not have to be static and can be final
I think we can replace the minutes to seconds to allow a finer adjustment.
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/tags/TagUtilsTest.java, line 27 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-M_0eOQqCe8PcHM6IgrP:-M_6H1X68O_4fInMcDy8:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/5e4bba87071e91f7687cf3574b019d9dba53390d/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/tags/TagUtilsTest.java#L27)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

I think the tests do not work because the "printedWarningCounter" is static and already incremented by the previous tests (createTagValue_tooLong() and createTagValue_nonPrintableCharacter()). 
For this case you can make the printedWarningCounter public (package) and reset it to 0 for this test.
For such a case, we use the @VisibleforTesting annotation for the variable to make it clear why it is public.
</blockquote></details>

Done.

**Review by mariusoe — CHANGES_REQUESTED** [review]
Good job Mahir. :)

I have a few more minor comments that you can take a look at. I put the im the EUM project, but they also refer to the one in the core project.
Once these are fixed, we can merge the PR.

> Reviewed 1 of 2 files at r3, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-:-Mcsw8oM7iltJdX6xbKm:b-mu75gw)* status: all files reviewed, 9 unresolved discussions (waiting on @Mahir-Isikli, @Patrick-Eichhorn, and @VisibleForTesting)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 12 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-Mcstc2a6h4B2t0O_3E1:-Mcstc2bBcbZ41ZN5peK:b-2we8nd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/fafdc4fd2ce989189e6088f316a06b268d5c7193/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L12)):*
> ```Java
> 
>     @VisibleForTesting
>     static int printedWarningCounter = 0;
> ```

Please add some comments to all static fields.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 17 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-McsteSa0kRWzop1zbq1:-McsteSa0kRWzop1zbq2:b-3yvi4q) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/fafdc4fd2ce989189e6088f316a06b268d5c7193/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L17)):*
> ```Java
>     static long lastWarningTime = 0;
> 
>     private final static int maxWarningPrints = 10;
> ```

It is common pratices that constant fields are written in uppcer cases: `MAX_WARNING_PRINTS`
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 52 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-McsvnSK2Vyf-cmJA8X-:-McsvnSK2Vyf-cmJA8X0:b2h1unl) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/fafdc4fd2ce989189e6088f316a06b268d5c7193/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L52)):*
> ```Java
>             printedWarningCounter++;
>             if (printedWarningCounter == maxWarningPrints) {
>                 lastWarningTime = System.currentTimeMillis();
> ```

We should print a log message, that further log messages are suppressed, so that the user knows why no more logs appear.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 55 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-Mcsu8sE4R8Ib7Mtfs2U:-Mcsu8sE4R8Ib7Mtfs2V:b17690t) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/fafdc4fd2ce989189e6088f316a06b268d5c7193/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L55)):*
> ```Java
>             }
> 
>         } else if ((System.currentTimeMillis() - lastWarningTime) > waitingTimeInMilliSeconds) {
> ```

We should reset this counter also if the last warning was more than `waitingTimeInMilliSeconds` ago and not only if the counter has reached the `maxWarningPrints` value.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 57 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-McsudHb4V_iLIhg0zEC:-McsudHb4V_iLIhg0zED:bon5l4p) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/fafdc4fd2ce989189e6088f316a06b268d5c7193/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L57)):*
> ```Java
>         } else if ((System.currentTimeMillis() - lastWarningTime) > waitingTimeInMilliSeconds) {
>             printedWarningCounter = 0;
>             printWarning(tagKey, value);
> ```

Can your restructure this method a bit, so that the method does not have to call itself? This would make them a little easier to understand.
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/SpringTestBase.java, line 151 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-McsvHJn5gCM-YXFnBx6:-McsvHJo-0rPLCZMObsN:b-66yn4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/fafdc4fd2ce989189e6088f316a06b268d5c7193/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/SpringTestBase.java#L151)):*
> ```
> Integer
> ```
You can just use primitives instead of their wrapper classes: `int`

**Review by Mahir-Isikli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064)* status: 2 of 4 files reviewed, 9 unresolved discussions (waiting on @Mahir-Isikli, @mariusoe, @Patrick-Eichhorn, and @VisibleForTesting)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 12 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-Mcstc2a6h4B2t0O_3E1:-Md1yz493qt3qMQ7z2nF:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/fafdc4fd2ce989189e6088f316a06b268d5c7193/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L12)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Please add some comments to all static fields.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 17 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-McsteSa0kRWzop1zbq1:-Md1z0AP2OLHORwLZWws:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/fafdc4fd2ce989189e6088f316a06b268d5c7193/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L17)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

It is common pratices that constant fields are written in uppcer cases: `MAX_WARNING_PRINTS`
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 52 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-McsvnSK2Vyf-cmJA8X-:-Md1z7d1-v6qCBz26kRK:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/fafdc4fd2ce989189e6088f316a06b268d5c7193/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L52)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

We should print a log message, that further log messages are suppressed, so that the user knows why no more logs appear.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 55 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-Mcsu8sE4R8Ib7Mtfs2U:-Md1zt-U27_P-KMsGIsy:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/fafdc4fd2ce989189e6088f316a06b268d5c7193/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L55)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

We should reset this counter also if the last warning was more than `waitingTimeInMilliSeconds` ago and not only if the counter has reached the `maxWarningPrints` value.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 57 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-McsudHb4V_iLIhg0zEC:-Md23Q9B8WEXNYn28N71:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/fafdc4fd2ce989189e6088f316a06b268d5c7193/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L57)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Can your restructure this method a bit, so that the method does not have to call itself? This would make them a little easier to understand.
</blockquote></details>

Done.

**Review by Patrick-Eichhorn — DISMISSED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064)* status: all files reviewed, 6 unresolved discussions (waiting on @mariusoe)

___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/SpringTestBase.java, line 151 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-McsvHJn5gCM-YXFnBx6:-MeAXQdr6d9HuzG_ozoy:b-br7dky) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/fafdc4fd2ce989189e6088f316a06b268d5c7193/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/SpringTestBase.java#L151)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> Integer
> ```
You can just use primitives instead of their wrapper classes: `int`
</blockquote></details>

todo - must still be changed

**Review by Mahir-Isikli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @mariusoe)

___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/SpringTestBase.java, line 151 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064#-McsvHJn5gCM-YXFnBx6:-MeAZeLf4_9WgRnrN6MR:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/fafdc4fd2ce989189e6088f316a06b268d5c7193/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/SpringTestBase.java#L151)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

todo - must still be changed
</blockquote></details>

Done.

**Review by Patrick-Eichhorn — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064)* status: all files reviewed, 6 unresolved discussions (waiting on @mariusoe)

**Review by Patrick-Eichhorn — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1064)* status: all files reviewed, 6 unresolved discussions (waiting on @mariusoe)

**Pull request merged**
