### PR TITLE
Closes #895 - Enhance the endpoint to fetch files with the possibility to specify a version

### LINKED ISSUE #895: Enhance the endpoint to fetch the file contents of the configuration server with the possibility to specify a version
The configuration server offers the possibility to fetch the content of configuration files of the workspace branch (which is used by the UI for example). Currently, the workspace branch is always used as a basis.

In this ticket this endpoint should be extended so that a specific version can be specified (based on the commit ID) to which the resulting filte content refers. This should make it possible to get the content of a file in a specific version (commit). It should be possible to specify the ID using a request parameter called `version`.

Example: `/api/v1/files/example.yml?version=e3004bed2cf2ba75a4d49d5383919223be58bc5f`

By default, the content of the file located in the latest version of the workspace branch should be used (for example, if no version parameter is specified).

It should also be possible to fetch the file content of file located on the configuration server's live branch. For this purpose, a special verison id can be reserved, e.g. `live`, which causes to use the current live branch as basis of the file content.

Example: `/api/v1/files/example.yml?version=live`

This enhancement should only refer to the read access of the file content (`GET /api/v1/files/...`). Write access to specific versions should not be allowed!

### PR DESCRIPTION
**Pull request by fylip97**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910)

### CODE REVIEW

**Review by mariusoe — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910)* status: all files reviewed, 5 unresolved discussions (waiting on @fylip97)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/file/DirectoryController.java, line 31 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910#-MG3u8Bd7oPNheuxQGrY:-MG3u8Bd7oPNheuxQGrZ:b-89ujl) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b71c4578786cb702f7e580477c54aa1f1825dd90/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/file/DirectoryController.java#L31)):*
> ```Java
>         Collection<FileInfo> collection;
>         if (commitId == null) {
>             collection = fileManager.getWorkingDirectory().listConfigurationFiles(path);
> ```

Since we cannot use a revision here, just implemented it as you have it already done at the beginning. Also add a comment that we have to do this because using a revision whe cannot display empty directories.

```
if (commitId == null) {
    // add comment why....
    return fileManager.getWorkingDirectory().listConfigurationFiles(path);
} else if (commitId.equals("live")) {
    return fileManager.getLiveRevision().listConfigurationFiles(path);
} else {
    return fileManager.getCommitWithId(commitId).listConfigurationFiles(path);
}
```
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/file/FileController.java, line 64 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910#-MG3ulsTCCLcP0iKNR0M:-MG3ulsTCCLcP0iKNR0N:b-ven5qk) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b71c4578786cb702f7e580477c54aa1f1825dd90/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/file/FileController.java#L64)):*
> ```Java
>                            @RequestParam(value = "version", required = false) String commitId) {
> 
>         String path = RequestUtil.getRequestSubPath(request);
> ```

Please remove the empty line before this and add one after.
___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerIntTest.java, line 78 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910#-MG3vgph8rTVRIIhvrpD:-MG3vgph8rTVRIIhvrpE:burf3y) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b71c4578786cb702f7e580477c54aa1f1825dd90/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerIntTest.java#L78)):*
> ```
> ResponseEntity<Optional>
> ```
This endpoint returns a `FileData` object. Thus, you can use it directly: `ResponseEntity<FileData> result2 = authRest.getForEntity("/api/v1/files/file.yml", FileData.class);`
___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerIntTest.java, line 78 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910#-MG3vsZL1Trp_9AIjpk4:-MG3veO74i_olNlcJeur:b-n067qq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b71c4578786cb702f7e580477c54aa1f1825dd90/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerIntTest.java#L78)):*
> ```Java
>                     .contains(tuple("file.yml", FileInfo.Type.FILE, null));
> 
>             ResponseEntity<Optional> result2 = authRest.getForEntity("/api/v1/files/file.yml", Optional.class);
> ```

Handling and providing the file content is not done by the `DirectoryController` so you don't have to do this in this test. Move these tests (where you check for the file's content) to the `FileControllerIntTest` or create it if it does not exist, please.
___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerIntTest.java, line 97 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910#-MG3wIV98gTEZB1NAqkm:-MG3wIVA6nHMn1rtXao1:b-v0nxdw) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b71c4578786cb702f7e580477c54aa1f1825dd90/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerIntTest.java#L97)):*
> ```Java
>                     .contains(tuple("file.yml", FileInfo.Type.FILE, null));
> 
>             ResponseEntity<Optional> result1 = authRest.getForEntity("/api/v1/files/file.yml?version=live/", Optional.class);
> ```

Here as well. Please move it to the `FileControllerIntTest`

**Review by fylip97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @mariusoe)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/file/DirectoryController.java, line 31 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910#-MG3u8Bd7oPNheuxQGrY:-MG89ne_4ekXON7XRf2T:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b71c4578786cb702f7e580477c54aa1f1825dd90/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/file/DirectoryController.java#L31)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Since we cannot use a revision here, just implemented it as you have it already done at the beginning. Also add a comment that we have to do this because using a revision whe cannot display empty directories.

```
if (commitId == null) {
    // add comment why....
    return fileManager.getWorkingDirectory().listConfigurationFiles(path);
} else if (commitId.equals("live")) {
    return fileManager.getLiveRevision().listConfigurationFiles(path);
} else {
    return fileManager.getCommitWithId(commitId).listConfigurationFiles(path);
}
```
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/file/FileController.java, line 64 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910#-MG3ulsTCCLcP0iKNR0M:-MG8A4QJ9DWtmSZ5CLAg:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b71c4578786cb702f7e580477c54aa1f1825dd90/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/file/FileController.java#L64)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Please remove the empty line before this and add one after.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerIntTest.java, line 78 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910#-MG3vgph8rTVRIIhvrpD:-MG8Agw21CgdJIHbxAJo:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b71c4578786cb702f7e580477c54aa1f1825dd90/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerIntTest.java#L78)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> ResponseEntity<Optional>
> ```
This endpoint returns a `FileData` object. Thus, you can use it directly: `ResponseEntity<FileData> result2 = authRest.getForEntity("/api/v1/files/file.yml", FileData.class);`
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerIntTest.java, line 78 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910#-MG3vsZL1Trp_9AIjpk4:-MG8C8hm2e9erJemMUtO:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b71c4578786cb702f7e580477c54aa1f1825dd90/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerIntTest.java#L78)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Handling and providing the file content is not done by the `DirectoryController` so you don't have to do this in this test. Move these tests (where you check for the file's content) to the `FileControllerIntTest` or create it if it does not exist, please.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerIntTest.java, line 97 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910#-MG3wIV98gTEZB1NAqkm:-MG8Dd4M9-YIsFRbZjhI:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/b71c4578786cb702f7e580477c54aa1f1825dd90/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerIntTest.java#L97)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Here as well. Please move it to the `FileControllerIntTest`
</blockquote></details>

Done.

**Review by mariusoe — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910)* status: all files reviewed, 2 unresolved discussions (waiting on @fylip97)

___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/FileControllerIntTest.java, line 34 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910#-MGCpwWQ0_klMOaZruwU:-MGCpwWQ0_klMOaZruwV:bdd4zzc) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/106254076af9e047d918e501a3688081c90e986d/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/FileControllerIntTest.java#L34)):*
> ```
> assertThat(resultBody2.toString()).contains("content=");
> ```
Using the `toString` method for this comparision is - imo - not the best way, because it heavily depends on the returned formatting.
Since you already have a `FileData` object, you just can use its `getContent` method. This way, the tests will be more robust and needs less restructuring.

Example:
```
assertThat(resultBody2).isNotNull();
assertThat(resultBody2.getContent()).isBlank();
```
___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/FileControllerIntTest.java, line 53 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910#-MGCqJFE9FphypzkI2d4:-MGCqJFE9FphypzkI2d5:bsc65h3) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/106254076af9e047d918e501a3688081c90e986d/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/FileControllerIntTest.java#L53)):*
> ```Java
> 
>             Optional<String> resultBodyLive = result1.getBody();
>             assertThat(resultBodyLive.toString()).contains("status=INTERNAL_SERVER_ERROR");
> ```

See the previous comment.

**Review by fylip97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @mariusoe)

___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/FileControllerIntTest.java, line 34 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910#-MGCpwWQ0_klMOaZruwU:-MGCtEvz7fFoSUyIEIOZ:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/106254076af9e047d918e501a3688081c90e986d/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/FileControllerIntTest.java#L34)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> assertThat(resultBody2.toString()).contains("content=");
> ```
Using the `toString` method for this comparision is - imo - not the best way, because it heavily depends on the returned formatting.
Since you already have a `FileData` object, you just can use its `getContent` method. This way, the tests will be more robust and needs less restructuring.

Example:
```
assertThat(resultBody2).isNotNull();
assertThat(resultBody2.getContent()).isBlank();
```
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/FileControllerIntTest.java, line 53 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910#-MGCqJFE9FphypzkI2d4:-MGCtFHe8hOckxTYBesZ:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/106254076af9e047d918e501a3688081c90e986d/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/FileControllerIntTest.java#L53)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

See the previous comment.
</blockquote></details>

Done.

**Review by mariusoe — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mariusoe — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
