### PR TITLE
Closes #1066 - Extend the configuration UI so that different file types can be created

### LINKED ISSUE #1066: Extend the configuration UI so that different file types can be created
In this ticket, the configuration UI is to be extended in such a way that the "New File" button allows a selection (drop-down) of the type of configuration to be created.

All files are still normal YAML files. Only a header is inserted - a comment in the YAML file - which determines its type. E.g.: `# type: method-configuration`

The new configuration file type should be named "Method Configuration".

image

### PR DESCRIPTION
**Pull request by Patrick-Eichhorn**
closes #1066

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088)

### CODE REVIEW

**Review by mariusoe — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088)* status: all files reviewed, 8 unresolved discussions (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js, line 104 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8ye0pAVlzACOqfgBx:-Ma8ye0pAVlzACOqfgBy:bzaea21) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js#L104)):*
> ```JavaScript
>   hideDeleteFileDialog = () => this.setState({ isDeleteFileDialogShown: false, filePath: null });
> 
>   showCreateFileDialog = (filePath, isCreateMethodConfiguration) =>
> ```

I think we should use an other approach for this. In case we have more thatn one file type, we would need many different boolean attributes here, making it hard to maintain and error-prone.

Let's pass some kind of enum to the dialog, defining what kind of file should be created. E.g. `NORMAL`, 'METHOD_CONFIGURATION'.
This can then be easily extended with further file types.
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileToolbar.js, line 47 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8zp1579D_hmxgdXLq:-Ma8zp1579D_hmxgdXLr:bnb8sq8) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileToolbar.js#L47)):*
> ```JavaScript
>           margin-right: 0.25rem;
>         }
>         .this :global(.p-toolbar-group-right) :global(.p-button) {
> ```

Can you use the same css selector as in the `group-left`?
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js, line 11 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8xLEE-FNZS7dI0LNH:-Ma8xLEE-FNZS7dI0LNI:bjs6gyb) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js#L11)):*
> ```
> methodConfigurationContentJSON
> ```

How about `methodConfigurationTemplate`? I would remove the prefix `JSON` because it will be just a JavaScript object after importing.
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js, line 129 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8wGGKDPRWuPLjMKpM:-Ma8wGGKDPRWuPLjMKpN:bivhvcj) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js#L129)):*
> ```JavaScript
>     const fullPath = this.getAbsolutePath(this.state.filename);
> 
>     if (this.props.dmethodConfigurationContentirectoryMode) {
> ```

Paste mistake?
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js, line 131 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8wozm5BAGbWaZGJNe:-Ma8wozm5BAGbWaZGJNf:b-gt1u5c) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js#L131)):*
> ```JavaScript
>     if (this.props.dmethodConfigurationContentirectoryMode) {
>       this.props.createDirectory(fullPath, true, true);
>     } else if (this.props.createMethodConfiguration) {
> ```

How about refactoring so we have just one `writeFile` statement:

```
} else {
  let content = '';
  if (this.props.createMethodConfiguration) { 
    content = '# type: method-configuration\n' + JSON.stringify(methodConfigurationContentJSON);
  }
  this.props.writeFile(fullPath, content, true, true);
}
```

Imo, using a variable for the file's content is more readable.
___
*[components/inspectit-ocelot-configurationserver-ui/src/data/method-configuration.json, line 1 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8vWtT67irNMkrRNDD:-Ma8vWtT67irNMkrRNDE:b-3f4rar) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/data/method-configuration.json#L1)):*
> ```JSON
> {
> ```

Can we rename this file? Maybe including the term "template_" or something like that. So that it is clear, that this will be used as a template.
Maybe a subdirectory `templates` would also make sense in case we'll have multiple templates in the future?
___
*[components/inspectit-ocelot-configurationserver-ui/src/data/method-configuration.json, line 6 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8utFCE1IIT78boo0J:-Ma8utFCE1IIT78boo0K:bap13ks) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/data/method-configuration.json#L6)):*
> ```
> r_trace
> ```
Because everyone will see this method name in the autocompletetion, we should think on a differnt name - maybe also stating that this is some kind of internal/generated rule.

Something like:
`r_internal_trace_method`
or
`r_generated_trace_method`
___
*[components/inspectit-ocelot-configurationserver-ui/src/data/method-configuration.json, line 10 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8vJqT0VRYtvI51d2B:-Ma8vJqT0VRYtvI51d2C:bbxjt9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/data/method-configuration.json#L10)):*
> ```JSON
>             "r_trace_method": true
>           },
>           "scopes": null
> ```

Do we need this or can we just remove it?

**Review by mariusoe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088)* status: all files reviewed, 9 unresolved discussions (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js, line 132 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma916Ar4bN7bZhU25lD:-Ma916Ar4bN7bZhU25lE:b-ossunv) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js#L132)):*
> ```
> # type: method-configuration
> ```
Maybe it would make sense to use a JSON object here, because then  we can easily add additional data and check for certain attributes if needed.

**Review by Patrick-Eichhorn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088)* status: 0 of 14 files reviewed, 9 unresolved discussions (waiting on @mariusoe and @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileToolbar.js, line 47 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8zp1579D_hmxgdXLq:-MaXN2zQBRCK97wBb9VE:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileToolbar.js#L47)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Can you use the same css selector as in the `group-left`?
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js, line 11 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8xLEE-FNZS7dI0LNH:-MaXNHJnA0CWLuVwVfEk:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js#L11)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> methodConfigurationContentJSON
> ```

How about `methodConfigurationTemplate`? I would remove the prefix `JSON` because it will be just a JavaScript object after importing.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js, line 129 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8wGGKDPRWuPLjMKpM:-MaXNh5P1mncHXP13XuG:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js#L129)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Paste mistake?
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js, line 131 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8wozm5BAGbWaZGJNe:-MaXOJ0X-zjHGFYUYRp5:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js#L131)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

How about refactoring so we have just one `writeFile` statement:

```
} else {
  let content = '';
  if (this.props.createMethodConfiguration) { 
    content = '# type: method-configuration\n' + JSON.stringify(methodConfigurationContentJSON);
  }
  this.props.writeFile(fullPath, content, true, true);
}
```

Imo, using a variable for the file's content is more readable.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js, line 132 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma916Ar4bN7bZhU25lD:-MaXOuqY4HRZgWSxN68h:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js#L132)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> # type: method-configuration
> ```
Maybe it would make sense to use a JSON object here, because then  we can easily add additional data and check for certain attributes if needed.

</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/data/method-configuration.json, line 1 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8vWtT67irNMkrRNDD:-MaXOh9V5fpeYlwsO27S:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/data/method-configuration.json#L1)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Can we rename this file? Maybe including the term "template_" or something like that. So that it is clear, that this will be used as a template.
Maybe a subdirectory `templates` would also make sense in case we'll have multiple templates in the future?
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/data/method-configuration.json, line 6 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8utFCE1IIT78boo0J:-MaXPmuB8VOySiZOlqxU:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/data/method-configuration.json#L6)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> r_trace
> ```
Because everyone will see this method name in the autocompletetion, we should think on a differnt name - maybe also stating that this is some kind of internal/generated rule.

Something like:
`r_internal_trace_method`
or
`r_generated_trace_method`

</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/data/method-configuration.json, line 10 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-Ma8vJqT0VRYtvI51d2B:-MaXPy9zA8MwnYQp1jxA:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f0f154303ef0f5008a5e48e5bbb42d669f07ac0f/components/inspectit-ocelot-configurationserver-ui/src/data/method-configuration.json#L10)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Do we need this or can we just remove it?
</blockquote></details>

Done.

**Review by mariusoe — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r2, 6 of 6 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088)* status: all files reviewed, 7 unresolved discussions (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js, line 238 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-MaYLB7n8dByRHLp6fmH:-MaYLB7oD3gSsnevn023:bnpv8pl) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b9b2cfa2b34f08f6c51a728c98f14a247f396e2/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js#L238)):*
> ```JavaScript
>           fileType={this.state.fileType}
>         />
>         <CreateDialog
> ```

Remove one dialog
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js, line 40 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-MaYSDBpEUk3thaM8pkL:-MaYSDBpEUk3thaM8pkM:b-uq1qqn) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b9b2cfa2b34f08f6c51a728c98f14a247f396e2/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js#L40)):*
> ```JavaScript
>         focusOnShow={false}
>         style={{ width: '400px' }}
>         header={'Create ' + fileTypeName + ' ' + type}
> ```

Problem in direcotry mode
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js, line 136 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-MaYPmzoCYgUv2evyVXS:-MaYPmzoCYgUv2evyVXT:b-71eq66) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b9b2cfa2b34f08f6c51a728c98f14a247f396e2/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js#L136)):*
> ```JavaScript
>       let content = '';
>       if (this.props.fileType !== FILE_TYPES.NORMAL) {
>         const fileHeader = '# {"type": "' + this.props.fileType.name + '"}\n';
> ```

```const { fileType, writeFile, onHide } = this.props;```
___
*[components/inspectit-ocelot-configurationserver-ui/src/data/constants.js, line 39 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-MaYOh5xDj-h1AVURcWO:-MaYOh5yDUqnH2m1SRqe:b-7h27qv) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b9b2cfa2b34f08f6c51a728c98f14a247f396e2/components/inspectit-ocelot-configurationserver-ui/src/data/constants.js#L39)):*
> ```
> FILE
> ```
CONFIGURATION_TYPES
___
*[components/inspectit-ocelot-configurationserver-ui/src/data/constants.js, line 40 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-MaYPKo40z6Yo3cza8Jx:-MaYPKo40z6Yo3cza8Jy:bb772uk) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b9b2cfa2b34f08f6c51a728c98f14a247f396e2/components/inspectit-ocelot-configurationserver-ui/src/data/constants.js#L40)):*
> ```JavaScript
>  */
> export const FILE_TYPES = {
>   NORMAL: {
> ```

YAML
___
*[components/inspectit-ocelot-configurationserver-ui/src/data/constants.js, line 45 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-MaYRwjKAOBL6_OW2ZQp:-MaYRwjKAOBL6_OW2ZQq:bj5mhin) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b9b2cfa2b34f08f6c51a728c98f14a247f396e2/components/inspectit-ocelot-configurationserver-ui/src/data/constants.js#L45)):*
> ```
> method-configuration
> ```
`Method-Configuration`
___
*[components/inspectit-ocelot-configurationserver-ui/src/data/constants.js, line 46 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-MaYOl3K5PJ2rQcp3vm5:-MaYOl3K5PJ2rQcp3vm6:bbru045) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b9b2cfa2b34f08f6c51a728c98f14a247f396e2/components/inspectit-ocelot-configurationserver-ui/src/data/constants.js#L46)):*
> ```
> content
> ```
template?

**Review by Patrick-Eichhorn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088)* status: all files reviewed, 7 unresolved discussions (waiting on @mariusoe)

___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js, line 238 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-MaYLB7n8dByRHLp6fmH:-MaYi23R0MHhtgARd_Jh:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b9b2cfa2b34f08f6c51a728c98f14a247f396e2/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js#L238)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Remove one dialog
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js, line 40 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-MaYSDBpEUk3thaM8pkL:-MaYjdbL29T5bMtO1N4f:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b9b2cfa2b34f08f6c51a728c98f14a247f396e2/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js#L40)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Problem in direcotry mode
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js, line 136 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-MaYPmzoCYgUv2evyVXS:-MaZ2s7c64Sir87gQxDq:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b9b2cfa2b34f08f6c51a728c98f14a247f396e2/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js#L136)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

```const { fileType, writeFile, onHide } = this.props;```
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/data/constants.js, line 39 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-MaYOh5xDj-h1AVURcWO:-MaZ2tbgCW7fjEAdbIs_:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b9b2cfa2b34f08f6c51a728c98f14a247f396e2/components/inspectit-ocelot-configurationserver-ui/src/data/constants.js#L39)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> FILE
> ```
CONFIGURATION_TYPES
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/data/constants.js, line 40 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-MaYPKo40z6Yo3cza8Jx:-MaZ3JHg5gQ1AJcGGOp-:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b9b2cfa2b34f08f6c51a728c98f14a247f396e2/components/inspectit-ocelot-configurationserver-ui/src/data/constants.js#L40)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

YAML
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/data/constants.js, line 45 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-MaYRwjKAOBL6_OW2ZQp:-MaZ3Jyj9p-_TFH0QfqZ:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b9b2cfa2b34f08f6c51a728c98f14a247f396e2/components/inspectit-ocelot-configurationserver-ui/src/data/constants.js#L45)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> method-configuration
> ```
`Method-Configuration`
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/data/constants.js, line 46 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1088#-MaYOl3K5PJ2rQcp3vm5:-MaZ3wlBAUfqJ3sZCyBn:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b9b2cfa2b34f08f6c51a728c98f14a247f396e2/components/inspectit-ocelot-configurationserver-ui/src/data/constants.js#L46)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> content
> ```
template?
</blockquote></details>

Done.

**Pull request merged**
