### PR TITLE
Closes #1553: Fix dependency vulnerabilities in v2.2.0

### LINKED ISSUE #1553: Fix dependency vulnerabilities in v2.2.0
The current release (`v2.2.0`) has `security-high` vulnerabilities for the following dependencies:
```
com.fasterxml.jackson.core : jackson-databind : 2.13.1
org.apache.tomcat.embed : tomcat-embed-core : 8.5.46
org.springframework : spring-beans : 5.3.14
org.yaml : snakeyaml : 1.30
```

These dependencies (also transitively) need to be updated.

### PR DESCRIPTION
**Pull request by heiko-holz**
Closes #1553

- - -
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554)

### CODE REVIEW

**Review by quandor — CHANGES_REQUESTED** [review]
> Reviewed 22 of 33 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554)* status: all files reviewed, 4 unresolved discussions (waiting on @heiko-holz)

___
*[`build.gradle` line 22 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJnam6KBQp0v8dX66A2:-NJnam6KBQp0v8dX66A3:b8w0cen) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/03b25fc60bb1e301057b260e2c3c2dd008d59cd8/build.gradle#L22)):*
> ```Gradle
>     apply plugin: 'jacoco'
> 
>     if (!project.hasProperty('') || project.getProperty('buildVersion').empty) {
> ```

Was removing `buildVersion` intentional?
___
*[`components/inspectit-ocelot-configdocsgenerator/build.gradle` line 35 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJnazuXAIGZ-YbNvDUk:-NJnazuXAIGZ-YbNvDUl:bdakbfe) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/03b25fc60bb1e301057b260e2c3c2dd008d59cd8/components/inspectit-ocelot-configdocsgenerator/build.gradle#L35)):*
> ```Gradle
>     implementation(
>             project(':inspectit-ocelot-config'),
>             "ch.qos.logback:logback-classic:${logbackVersion}",
> ```

We probably could get rid of that version and let the spring-dependency-manangement-plugin decide upon its version. If ${logbackVersion} is not newer than the one from spring-boot.
___
*[`components/inspectit-ocelot-configdocsgenerator/build.gradle` line 39 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJnbDBsE-K6zLbcP5Ix:-NJnbDBsE-K6zLbcP5Iy:b-nyrfl0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/03b25fc60bb1e301057b260e2c3c2dd008d59cd8/components/inspectit-ocelot-configdocsgenerator/build.gradle#L39)):*
> ```Gradle
>             'commons-beanutils:commons-beanutils:1.9.4',
> 
>             "org.springframework.boot:spring-boot-starter-web:${springBootVersion}",
> ```

We probably could get rid of that version and let the spring-dependency-manangement-plugin decide upon its version.
___
*[`components/inspectit-ocelot-configdocsgenerator/src/test/java/inspectit/ocelot/configdocsgenerator/parsing/ConfigParserTest.java` line 67 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJncGpnAhchF3KsYDCG:-NJncGpnAhchF3KsYDCH:bz4yilt) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/03b25fc60bb1e301057b260e2c3c2dd008d59cd8/components/inspectit-ocelot-configdocsgenerator/src/test/java/inspectit/ocelot/configdocsgenerator/parsing/ConfigParserTest.java#L67)):*
> ```Java
>             Map<String, Boolean> enabledMap = new HashMap<>();
>             enabledMap.put("free", true);
>           // TODO: Why was a mock used here? An upgrade to a newer Mockito version caused
> ```

I want to discuss that shortly. I think we can safely switch to non-mock usage, but want to be sure that I did not missed something.

**Review by heiko-holz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554)* status: all files reviewed, 4 unresolved discussions (waiting on @quandor)

___
*[`components/inspectit-ocelot-configdocsgenerator/src/test/java/inspectit/ocelot/configdocsgenerator/parsing/ConfigParserTest.java` line 67 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJncGpnAhchF3KsYDCG:-NJnhl5eAUbajS1k2V-z:b-qln5cp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/03b25fc60bb1e301057b260e2c3c2dd008d59cd8/components/inspectit-ocelot-configdocsgenerator/src/test/java/inspectit/ocelot/configdocsgenerator/parsing/ConfigParserTest.java#L67)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

I want to discuss that shortly. I think we can safely switch to non-mock usage, but want to be sure that I did not missed something.
</blockquote></details>

Yes, I agree. Looks good!

**Review by heiko-holz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554)* status: all files reviewed, 4 unresolved discussions (waiting on @quandor)

___
*[`build.gradle` line 22 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJnam6KBQp0v8dX66A2:-NJniFfB4aClMUJ2OXDE:breib8p) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/03b25fc60bb1e301057b260e2c3c2dd008d59cd8/build.gradle#L22)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

Was removing `buildVersion` intentional?
</blockquote></details>

Good catch, this was unintentional!
Thanks for checking

**Review by quandor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @heiko-holz)

___
*[`build.gradle` line 22 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJnam6KBQp0v8dX66A2:-NJnlHmS7cCY38QbNZUI:btca4rb) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/03b25fc60bb1e301057b260e2c3c2dd008d59cd8/build.gradle#L22)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Good catch, this was unintentional!
Thanks for checking
</blockquote></details>

I reintroduced it.
___
*[`components/inspectit-ocelot-configdocsgenerator/build.gradle` line 35 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJnazuXAIGZ-YbNvDUk:-NJnl_A95qisgN7iEIYo:b-yxp6qf) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/03b25fc60bb1e301057b260e2c3c2dd008d59cd8/components/inspectit-ocelot-configdocsgenerator/build.gradle#L35)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

We probably could get rid of that version and let the spring-dependency-manangement-plugin decide upon its version. If ${logbackVersion} is not newer than the one from spring-boot.
</blockquote></details>

I got rid of that version.
___
*[`components/inspectit-ocelot-configdocsgenerator/build.gradle` line 39 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJnbDBsE-K6zLbcP5Ix:-NJnlclV3DJZT_AbUXnm:b-yxp6qf) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/03b25fc60bb1e301057b260e2c3c2dd008d59cd8/components/inspectit-ocelot-configdocsgenerator/build.gradle#L39)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

We probably could get rid of that version and let the spring-dependency-manangement-plugin decide upon its version.
</blockquote></details>

I got rid of that version.
___
*[`components/inspectit-ocelot-configdocsgenerator/src/test/java/inspectit/ocelot/configdocsgenerator/parsing/ConfigParserTest.java` line 67 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJncGpnAhchF3KsYDCG:-NJnlO3a6AEStvQJ7msa:b-nnndlu) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/03b25fc60bb1e301057b260e2c3c2dd008d59cd8/components/inspectit-ocelot-configdocsgenerator/src/test/java/inspectit/ocelot/configdocsgenerator/parsing/ConfigParserTest.java#L67)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Yes, I agree. Looks good!
</blockquote></details>

I will remove the TODO comment
___
*[`components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/SwaggerConfiguration.java` line 23 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJnlne98_Y9uaCKHDB7:-NJnlne98_Y9uaCKHDB8:bnetpnd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/03b25fc60bb1e301057b260e2c3c2dd008d59cd8/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/SwaggerConfiguration.java#L23)):*
> ```Java
>                 .info(new Info().title("Configuration Server API")
>                         .description("inspectIT Ocelot Configuration Server")
>                         // TODO: retrieve version properly
> ```

This TODO still needs to be solved.

**Review by quandor — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-:-NJo08OPEZiKDkNuuloE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @heiko-holz)

___
*[`components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/SwaggerConfiguration.java` line 23 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJnlne98_Y9uaCKHDB7:-NJo042L6SOu7CRjcttZ:bb6ywmx) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/03b25fc60bb1e301057b260e2c3c2dd008d59cd8/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/SwaggerConfiguration.java#L23)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

This TODO still needs to be solved.
</blockquote></details>

LGTM

**Review by heiko-holz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554)* status: all files reviewed, 3 unresolved discussions (waiting on @quandor)

___
*[`components/inspectit-ocelot-configurationserver/build.gradle` line 8 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJo60eB7wGDqMCIBoEh:-NJo60eB7wGDqMCIBoEi:b-ulk9de) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6def9606c13c25e972a0f919b3e374b400eaf1c2/components/inspectit-ocelot-configurationserver/build.gradle#L8)):*
> ```Gradle
>     id "org.cyclonedx.bom" version "1.7.2"
>     // Add the plugin in the existing plugins block
>     id "org.owasp.dependencycheck" version "5.2.4"
> ```

I wonder if we could upgrade to `v7.4.1`: https://plugins.gradle.org/plugin/org.owasp.dependencycheck
___
*[`components/inspectit-ocelot-configurationserver/build.gradle` line 137 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJo6If5D92FDHfr5750:-NJo6If5D92FDHfr5751:b-lwut22) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6def9606c13c25e972a0f919b3e374b400eaf1c2/components/inspectit-ocelot-configurationserver/build.gradle#L137)):*
> ```Gradle
>             "io.jsonwebtoken:jjwt-jackson:${jsonWebTokenVersion}",
>             "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml",
>             "com.fasterxml.jackson.core:jackson-databind",
> ```

this is now handled by the Spring Boot Bom, right?
Should we add a short comment?
___
*[`components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/SwaggerConfiguration.java` line 23 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJnlne98_Y9uaCKHDB7:-NJo5D_4BscvozEKbVg0:b-cstnkg) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/03b25fc60bb1e301057b260e2c3c2dd008d59cd8/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/SwaggerConfiguration.java#L23)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

I agree
___
*[`inspectit-ocelot-core/build.gradle` line 69 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJo7PibEM99zn4Hngmb:-NJo7PibEM99zn4Hngmc:bj4lpfo) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6def9606c13c25e972a0f919b3e374b400eaf1c2/inspectit-ocelot-core/build.gradle#L69)):*
> ```Gradle
>             'org.apache.commons:commons-math3:3.6.1',
>             'org.apache.httpcomponents:httpclient:4.5.8',
>             "commons-io:commons-io:${commonsIoVersion}",
> ```

do we need the version here? In the `build.gradle` of the `configuration-server`, we only explicitly set the version of `commons-io` and not of `commons-lang3`

**Review by quandor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554)* status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @heiko-holz)

___
*[`inspectit-ocelot-core/build.gradle` line 69 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJo7PibEM99zn4Hngmb:-NJoL_dB7K5vs4Uwd3il:b-q4erva) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6def9606c13c25e972a0f919b3e374b400eaf1c2/inspectit-ocelot-core/build.gradle#L69)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

do we need the version here? In the `build.gradle` of the `configuration-server`, we only explicitly set the version of `commons-io` and not of `commons-lang3` 
</blockquote></details>

Yes, we do need the version in this file. In `build.gradle` of module `configuration-server` we use the spring-boot-plugin which handles the dependencies via spring-boot-bom. We do not use that plugin in core-build.gradle.
We might try that, but since there are so many dependencies in this file, I see a high risk of getting this PR done in time.
But we definitely should align all dependency versions in inspectit-ocelot.

**Review by quandor — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554)* status: all files reviewed, 1 unresolved discussion (waiting on @heiko-holz)

**Review by heiko-holz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @heiko-holz)

___
*[`components/inspectit-ocelot-configurationserver/build.gradle` line 137 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJo6If5D92FDHfr5750:-NJoS_3mDFb2yiyK6L54:bd5l6mr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6def9606c13c25e972a0f919b3e374b400eaf1c2/components/inspectit-ocelot-configurationserver/build.gradle#L137)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

I added a comment.
</blockquote></details>

thanks!
___
*[`inspectit-ocelot-core/build.gradle` line 69 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554#-NJo7PibEM99zn4Hngmb:-NJoSPzVBxYskKRSjruc:b-f03ez0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6def9606c13c25e972a0f919b3e374b400eaf1c2/inspectit-ocelot-core/build.gradle#L69)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

Yes, we do need the version in this file. In `build.gradle` of module `configuration-server` we use the spring-boot-plugin which handles the dependencies via spring-boot-bom. We do not use that plugin in core-build.gradle.
We might try that, but since there are so many dependencies in this file, I see a high risk of getting this PR done in time.
But we definitely should align all dependency versions in inspectit-ocelot.
</blockquote></details>

Thanks for the elaborate answer. I agree, we shouldn't change `core` in this PR.

**Review by quandor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1554)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @heiko-holz)

**Pull request merged**
