### PR TITLE
Upgrade OpenTelemetry to v1.17.0

### PR DESCRIPTION
**Pull request by heiko-holz**
Upgrade OpenTelemetry to [v1.17.0](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.17.0)

- - -
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1515)

### CODE REVIEW

**Review by Dimi-Ma — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1515)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @ClaudioWaldvogel and @heiko-holz)

___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/OpenTelemetryControllerImpl.java` line 408 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1515#-NJdkezm6PIu9z5QZUNR:-NJdkezm6PIu9z5QZUNS:bb5a5nq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/58f3fc90584589fb5a8b597abee7c1e7a8ff6f63/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/OpenTelemetryControllerImpl.java#L408)):*
> ```Java
>             // register metric reader for each service
>             for (DynamicallyActivatableMetricsExporterService metricsExportService : registeredMetricExporterServices.values()) {
>                 builder.registerMetricReader(OpenCensusMetrics.attachTo(metricsExportService.getNewMetricReader()));//OpenCensusMetrics.attachTo(metricsExportService.getNewMetricReader()));
> ```

the comment can be removed.

**Review by Dimi-Ma — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1515)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @heiko-holz)

**Review by heiko-holz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1515)* status: 8 of 12 files reviewed, all discussions resolved (waiting on @Dimi-Ma)

___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/OpenTelemetryControllerImpl.java` line 408 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1515#-NJdkezm6PIu9z5QZUNR:-NJiuRtMDGkl9VIKylqT:b80d70j) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/58f3fc90584589fb5a8b597abee7c1e7a8ff6f63/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/OpenTelemetryControllerImpl.java#L408)):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

the comment can be removed.
</blockquote></details>

comment was removed

**Review by Dimi-Ma — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1515)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @heiko-holz)

**Review by Dimi-Ma — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1515#-:-NJj0JHFEC8h6pjZqpOo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @heiko-holz)

**Pull request merged**
