### PR TITLE
Publish agent, test with https://jitpack.io/

### PR DESCRIPTION
**Pull request by florinandone**
I want to make the agent available via https://jitpack.io/.
In my opinion, this will be useful for others. Could you please merge this?

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1039)

### CODE REVIEW

**Comment by florinandone** [comment]
See jitpack for inspectit 

https://jitpack.io/#inspectit/inspectit-ocelot

These are the files published in jitpack.io for standard and my fork

https://jitpack.io/com/github/inspectIT/inspectit-ocelot/
https://jitpack.io/com/github/florinandone/inspectit-ocelot/


From gradle can build with:

   allprojects {
        repositories {
            jcenter()
            maven { url "https://jitpack.io" }
        }
   }
        dependencies {
	        implementation 'com.github.inspectit:inspectit-ocelot:Tag'
	}

**Comment by florinandone** [comment]
@mariusoe Hi, I saw you did label my request.
Is t possible to get it approved? 
Otherwise, I need other ways to integrate with Gradle.
Could you recommend one?

**Comment by mariusoe** [comment]
Hi @florinandone 

thanks for your contribution. 
Distributing our artifacts via Jitpack is a nice idea. I've now adjusted one more little thing (changed quotes to quotation marks) and then merge your PR, since everything else looks good.

**Review by mariusoe — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1039)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @florinandone)

**Comment by florinandone** [comment]
@mariusoe Thank you for this.

FYI, I did copy from inspectit-ocelot-config\build.gradle and is in one more place
You may change there for consistency also.

**Pull request merged**
