### PR TITLE
Closes #1543 - Older Agent versions are no longer compatible with the config server from the release 2.2.

### LINKED ISSUE #1543: [Bug] - Older Agent versions are no longer compatible with the config server from the release 2.2.0
**Describe the bug**
Older agent versions are no longer compatible with the config server from the release 2.2.0. 
When using an older agent version with the current config server the status view cannot be shown and an error is being thrown, because older agent versions don't send a json string to config server containing the service states map.

**To Reproduce**
1. Start current config server
2. Start current config server ui
3. Start an older agent (Version < 2.2.0)
4. Go to the .../status page in the config ui
5. Error

**Expected behavior**
The status view should be opened without an error and there should be a message in the tooltip of the "Show Service States" Button, saying that this functionality is available from agent versions 2.2.0 and up.
If the agent version is below 2.2.0, this button should be disabled.

### PR DESCRIPTION
**Pull request by danipaniii**
Fixing the incompatibility error with older agent versions and the config server from the release 2.2.0.

- - -
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544)

### CODE REVIEW

**Comment by danipaniii** [comment]
version-code


Personally I am wondering if the if-condition at line 122 is necessary?
Because by default log preloading, agent commands and the service states available are set to false and if they can't be fetched later in the try catch block at 140, they are not available.

**Comment by heiko-holz** [comment]
*[`components/inspectit-ocelot-configurationserver-ui/yarn.lock` line 0 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NGzKZ-TAUazyrmDM3-9:-NGzKZ-UAuiFpWapH5Cq:b7vbayf) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ea765308c0f5855b75296019f577d4b73d933705/components/inspectit-ocelot-configurationserver-ui/yarn.lock#L0)):*
can you please delete your `yarn.lock` locally and build it fresh (via `yarn install`). I think the uploaded `yarn.lock` also contains `npm` stuff

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544)* status: all files reviewed, 5 unresolved discussions (waiting on @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 140 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NGzIo5h0O25NEeQ8qH8:-NGzIo5h0O25NEeQ8qH9:bnm2sss) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ea765308c0f5855b75296019f577d4b73d933705/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L140)):*
> ```JavaScript
>       agentIdElement = <span style={{ color: 'gray' }}>({agentId})</span>;
> 
>       try {
> ```

I would surround this with  `if(serviceStatesAvailable)`, otherwise we are executing unnecessary code.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 143 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NGzJD504RMcjAP58_BJ:-NGzGf6W7Ki9V_KMHCXq:bax9z19) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ea765308c0f5855b75296019f577d4b73d933705/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L143)):*
> ```JavaScript
>         serviceStates = JSON.parse(metaInformation.serviceStates);
> 
>         logAvailable = serviceStates.LogPreloader;
> ```

Actually, we need to retrieve the `logAvailable` and `agentCommandsEnabled` differently, to be downwards-compatible with versions that do not have the service states.

Thus, we need an if/else, checking whether `serviceStatesAvailable`. If it's not available due to an earlier version of the agent, I think we have to parse the config to see if `logAvailable` and `agentCommandsEnabled`
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 241 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NGzJw6r5FYRjd_kZACE:-NGzJw6sC1xrPmIsUzGV:bzhkv4c) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ea765308c0f5855b75296019f577d4b73d933705/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L241)):*
> ```JavaScript
>             logAvailable && agentCommandsEnabled
>               ? 'Show Logs'
>               : "<b>Logs not available!</b>\nMake sure to enable 'log-preloading' and 'agent-commands' in the config, and configure the URL for the agent commands.\nAvailable for agent versions 1.1.5 and above"
> ```

Can you add a similar message to the `Download Support Archive` tooltip :)?
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 291 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NGzK3iM8wmXspoSuVnu:-NGzK3iM8wmXspoSuVnv:b9nmmy8) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ea765308c0f5855b75296019f577d4b73d933705/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L291)):*
> ```JavaScript
>     let agentCommandsEnabled = false;
> 
>     try {
> ```

Again, to be downwards compatible, we need to check if `serviceStatesAvailable`, and if not, retrieve the `agentCommandsEnabled` differently.

**Comment by heiko-holz** [comment]
Hi @danipaniii , I think we still need line 122 it to see if `serviceStatesAvailable`, to use it further (see my other comments).

If we don't check for `serviceStatesAvailable` (see other comments), we are executing unnecessary try/catch blocks.
Also, we need to retrieve `logAvailable´ and `agentCommandsEnabled` in a downward-compatible way (see my other comments)

**Review by MariusBrill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544)* status: all files reviewed, 5 unresolved discussions (waiting on @danipaniii and @heiko-holz)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 140 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NGzIo5h0O25NEeQ8qH8:-NH4Bjt87i2gkN_9ig1n:b-7rl0jd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ea765308c0f5855b75296019f577d4b73d933705/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L140)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I would surround this with  `if(serviceStatesAvailable)`, otherwise we are executing unnecessary code.
</blockquote></details>

done.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 143 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NGzJD504RMcjAP58_BJ:-NH4BsGI02KObfJ7bfL1:b-ubomd0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ea765308c0f5855b75296019f577d4b73d933705/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L143)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Actually, we need to retrieve the `logAvailable` and `agentCommandsEnabled` differently, to be downwards-compatible with versions that do not have the service states.

Thus, we need an if/else, checking whether `serviceStatesAvailable`. If it's not available due to an earlier version of the agent, I think we have to parse the config to see if `logAvailable` and `agentCommandsEnabled`
</blockquote></details>

As we discussed, we won't implement this feature as it would too much load on the client
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 241 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NGzJw6r5FYRjd_kZACE:-NH4UXze4rhSCMq1s5u4:b-7rl0jd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ea765308c0f5855b75296019f577d4b73d933705/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L241)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Can you add a similar message to the `Download Support Archive` tooltip :)?
</blockquote></details>

done.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 291 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NGzK3iM8wmXspoSuVnu:-NH4XF6o1t42UkGf-ycq:b-7rl0jd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ea765308c0f5855b75296019f577d4b73d933705/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L291)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Again, to be downwards compatible, we need to check if `serviceStatesAvailable`, and if not, retrieve the `agentCommandsEnabled` differently.
</blockquote></details>

done.

**Review by Dimi-Ma — COMMENTED** [review]
> Dismissed @heiko-holz from a discussion.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @heiko-holz and @MariusBrill)

___
*[`components/inspectit-ocelot-configurationserver-ui/yarn.lock` line  at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NGzKZ-TAUazyrmDM3-9:-NH3greb1pRqaWpvuD2N:bb7f2mf) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ea765308c0f5855b75296019f577d4b73d933705/components/inspectit-ocelot-configurationserver-ui/yarn.lock#L)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

can you please delete your `yarn.lock` locally and build it fresh (via `yarn install`). I think the uploaded `yarn.lock` also contains `npm` stuff
</blockquote></details>

done

**Review by MariusBrill — COMMENTED** [review]
> Dismissed @heiko-holz from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @Dimi-Ma and @heiko-holz)

**Review by Dimi-Ma — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-:-NH4d3pE0DPOmGjK-bSL:bnfp4nl)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @heiko-holz and @MariusBrill)

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544)* status: all files reviewed, 2 unresolved discussions (waiting on @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/dialogs/DownloadDialogue.js` line 29 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NH4kZlm5BEgi-1yAeyN:-NH4kZlm5BEgi-1yAeyO:boz4vq4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6e776ee65315ed92839733d3ad94c5de20cffd10/components/inspectit-ocelot-configurationserver-ui/src/components/views/dialogs/DownloadDialogue.js#L29)):*
> ```JavaScript
>         return `${dialogueSettings.header} could not be loaded due to an unexpected error.\n
>                 Ensure that both agent-commands and log-preloading are enabled and the agent-commands URL is correct in your agent
>                 configuration.\nThis feature is only available for agent versions 1.15.0 and higher`;
> ```

I added the note for the required version number to the error message in the DownloadDialogue
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 111 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NH4koSH8ODVgreJ6e_4:-NH4koSI2VLQB97F4Dob:bu60s8u) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6e776ee65315ed92839733d3ad94c5de20cffd10/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L111)):*
> ```JavaScript
>     const agentVersionTokens = agentVersion.split('.');
>     let logAvailable = false;
>     let agentCommandsEnabled = false;
> ```

`agentCommandsEnabled` will never be set to `true` if the `serviceStatesAvailable` is not true.
I think we need to include a version check to the agent commands as well.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 125 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NH4kiG1-bxhUBfsfwXS:-NH4kiG1-bxhUBfsfwXT:b-xteg36) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6e776ee65315ed92839733d3ad94c5de20cffd10/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L125)):*
> ```JavaScript
>       logAvailable = agentVersionNumber > 11500;
>       // support archive is available at version 2.20+
>       supportArchiveAvailable = agentVersionNumber >= 22000;
> ```

I added `supportArchiveAvailable`
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 127 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NH4kl-VEFRrVdzMqmFY:-NH4kl-VEFRrVdzMqmFZ:b-5embhk) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6e776ee65315ed92839733d3ad94c5de20cffd10/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L127)):*
> ```JavaScript
>       supportArchiveAvailable = agentVersionNumber >= 22000;
>       // service states are available at version 2.20+
>       serviceStatesAvailable = agentVersionNumber >= 22000;
> ```

I fixed it to `22000`
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 112 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NH4mfwIB-4F_C2do4TS:-NH4mfwIB-4F_C2do4TT:b-68x8xb) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ef824059be5dbecb5603d656e436c3d12f55f27f/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L112)):*
> ```JavaScript
>     const agentVersionTokens = agentVersion.split('.');
>     let logAvailable = false;
>     let agentCommandsEnabled = false;
> ```

the `agentCommandsEnabled` will never be true unless we have `serviceStatesAvailable`.

I think we need to also do a version check for agent commands, or assume agent commands are enabled.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 132 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NH4m_qPErq7o6k0MALd:-NH4m_qPErq7o6k0MALe:bg3l6xm) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ef824059be5dbecb5603d656e436c3d12f55f27f/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L132)):*
> ```JavaScript
>     }
> 
>     if (serviceStatesAvailable) {
> ```

I added the code snippet to resolve the `serviceStates` here, to avoid duplicate code

**Review by heiko-holz — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544)* status: all files reviewed, 2 unresolved discussions (waiting on @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 112 at r11](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NH4sd-O8E4YXdv0IiNu:-NH4sd-O8E4YXdv0IiNv:bmha1mr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/7adf4fc9d83557f3b600c7f946a5d38f9323f1f7/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L112)):*
> ```JavaScript
>     const agentVersionTokens = agentVersion.split('.');
>     let logAvailable = false;
>     let agentCommandsEnabled = true;
> ```

We now initialize the `agentCommandsEnabled` to true (to be downwards compatible)

**Review by danipaniii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @Dimi-Ma, @heiko-holz, and @MariusBrill)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/dialogs/DownloadDialogue.js` line 29 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NH4kZlm5BEgi-1yAeyN:-NH91Ujo-WlYFZfgvPNg:b-83sjoh) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6e776ee65315ed92839733d3ad94c5de20cffd10/components/inspectit-ocelot-configurationserver-ui/src/components/views/dialogs/DownloadDialogue.js#L29)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I added the note for the required version number to the error message in the DownloadDialogue
</blockquote></details>

Nice!
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 127 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NH4kl-VEFRrVdzMqmFY:-NH91zuc6B8R2P7BiBkM:bskhgrg) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6e776ee65315ed92839733d3ad94c5de20cffd10/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L127)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I fixed it to `22000`
</blockquote></details>

I am still seeing the 20200 

I fixed it.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 360 at r11](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NH98VuS9e5GRtIy_6hj:-NH98VuS9e5GRtIy_6hk:bxxqzde) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/7adf4fc9d83557f3b600c7f946a5d38f9323f1f7/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L360)):*
> ```JavaScript
>                 agentCommandsEnabled && supportArchiveAvailable
>                   ? 'Download Support Archive'
>                   : "<b>Support archive not available!</b>\nMake sure to enable 'agent-commands' in the config and configure the URL for the agent commands. \n This feature is only available for agent versions 1.15.0 and above."
> ```

Changed the version in the tooltip to 2.2.0

**Review by heiko-holz — COMMENTED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544)* status: all files reviewed, 2 unresolved discussions (waiting on @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 127 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NH4kl-VEFRrVdzMqmFY:-NHO1Xvw3m0hY7lx9gJR:b-ur4lp6) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6e776ee65315ed92839733d3ad94c5de20cffd10/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L127)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

I am still seeing the 20200 

I fixed it.
</blockquote></details>

Actually, I was "unfixing" it :angel: 

The actual agent version is `20200` (as the minor version is `2`, in `22000` the minor version is `20`.

Let's discuss this in today's Sync meeting.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 360 at r11](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544#-NH98VuS9e5GRtIy_6hj:-NHO2-qX42nVTqi3sKRq:bd5l6mr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/7adf4fc9d83557f3b600c7f946a5d38f9323f1f7/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L360)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

Changed the version in the tooltip to 2.2.0
</blockquote></details>

thanks!

**Review by heiko-holz — APPROVED** [review]
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1544)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @danipaniii)

**Pull request merged**
