### PR TITLE
Closes #1003 - Updated default config.

### LINKED ISSUE #1003: Update default config.
exporters.metrics.influx: url property should be added but commented out.

exporters.tracing.jaeger: grpc property should be added but commented out.

Add  new lines between the properties to increase readbility.

tracing.jaeger.url is deprecated and should be marked as @Depcrecated in the respective settings.

Add logs to TraceExportersConfiguration.

### PR DESCRIPTION
**Pull request by MariusBrill**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004)

### CODE REVIEW

**Review by Patrick-Eichhorn — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @MariusBrill)

___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 123 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004#-MTj5wM41HMHmOgU2WmB:-MTj1LiuC5RbBPlZe0Pn:blt61z4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/583a8208c2a1fee283ea7c58dce779f183351dee/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L123)):*
> ```YAML
>         enabled: true
> 
>         # The host of the prometheus server.
> ```

This is not the host of the prometheus server itself, it is the host of the "prometheus HTTP endpoint"
___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 126 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004#-MTj6FeN5_QHE3av8ErW:-MTj1NS9BlZSDcXLFWkf:byuq9uz) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/583a8208c2a1fee283ea7c58dce779f183351dee/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L126)):*
> ```YAML
>         host: localhost
> 
>         # The port of the prometheus server.
> ```

""- of the prometheus HTTP endpoint"
___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 160 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004#-MTj209t82T0uCz4Wv9x:-MTj209t82T0uCz4Wv9y:b-td40lj) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/583a8208c2a1fee283ea7c58dce779f183351dee/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L160)):*
> ```YAML
>         # E.g. if the exportInterval is 15s and the buffer-size is 4, the export will keep up to one minute of data in memory.
>         buffer-size: 40
> ```

Can you extend the influx config with user and password (as comments)
___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 166 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004#-MTj1hx31c1vEM60dwsc:-MTj1hx31c1vEM60dwsd:b-j307il) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/583a8208c2a1fee283ea7c58dce779f183351dee/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L166)):*
> ```YAML
>         enabled: true
> 
>         # location of the jaeger gRPC API.
> ```

Upper Case
___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 167 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004#-MTj1jho1JI3HBlnZ5uU:-MTj1jho1JI3HBlnZ5uV:b-j307il) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/583a8208c2a1fee283ea7c58dce779f183351dee/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L167)):*
> ```YAML
> 
>         # location of the jaeger gRPC API.
>         # either a valid NameResolver-compliant URI, or an authority string.
> ```

Upper Case

**Review by MariusBrill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 123 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004#-MTj5wM41HMHmOgU2WmB:-MTjBoygBS1rnZGZAOi6:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/583a8208c2a1fee283ea7c58dce779f183351dee/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L123)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

This is not the host of the prometheus server itself, it is the host of the "prometheus HTTP endpoint"
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 126 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004#-MTj6FeN5_QHE3av8ErW:-MTjBonTA6HcS-_8gfd9:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/583a8208c2a1fee283ea7c58dce779f183351dee/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L126)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

""- of the prometheus HTTP endpoint"
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 160 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004#-MTj209t82T0uCz4Wv9x:-MTjBmtI7vmxDiiq_SZ3:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/583a8208c2a1fee283ea7c58dce779f183351dee/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L160)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

Can you extend the influx config with user and password (as comments)
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 166 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004#-MTj1hx31c1vEM60dwsc:-MTjBn8P2nLd5vndyz79:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/583a8208c2a1fee283ea7c58dce779f183351dee/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L166)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

Upper Case
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 167 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004#-MTj1jho1JI3HBlnZ5uU:-MTjBncP8WE6FoGnvepH:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/583a8208c2a1fee283ea7c58dce779f183351dee/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L167)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

Upper Case
</blockquote></details>

Done.

**Review by Patrick-Eichhorn — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004)* status: all files reviewed, 5 unresolved discussions (waiting on @Patrick-Eichhorn)

**Review by Patrick-Eichhorn — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
