### PR TITLE
feat: generate SBOM file for releases

### PR DESCRIPTION
**Pull request by aaronweissler**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1367)

### CODE REVIEW

**Review by aaronweissler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1367)* status: 0 of 3 files reviewed, 2 unresolved discussions

___
*[build.gradle, line 38 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1367#-Mz-rfU92p1B2OyxvN6i:-Mz-rfU92p1B2OyxvN6j:b-29r6q1) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ff9bc96bb709e8a55a6bb870f811ee2ffd617081/build.gradle#L38)):*
> ```Gradle
>     // includeConfigs += ["runtimeClasspath"]
>     // skipConfigs is a list of configuration names to exclude when generating the BOM
>     // skipConfigs += ["compileClasspath", "testCompileClasspath"]
> ```

I do not know which configs would be sensible to skip or if only a specific set should be included in the first place. 
The currently commented-out values are from the plugin's readme https://github.com/CycloneDX/cyclonedx-gradle-plugin
___
*[.circleci/config.yml, line 62 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1367#-Mz-ryUt2YDeBbQhg8vv:-Mz-ryUt2YDeBbQhg8vw:btk1zug) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ff9bc96bb709e8a55a6bb870f811ee2ffd617081/.circleci/config.yml#L62)):*
> ```YAML
>       - run: cp ~/inspectit/repo/components/inspectit-ocelot-eum-server/build/libs/inspectit-ocelot-eum-server-${CIRCLE_TAG}.jar ~/inspectit/artifacts
>       - run: cp ~/inspectit/repo/build/reports/bom.json ~/inspectit/artifacts
>       - run: cp ~/inspectit/repo/build/reports/bom.xml ~/inspectit/artifacts
> ```

I could not yet test whether these additions work as expected.

**Review by aaronweissler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1367)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @mariusoe)

___
*[inspectit-ocelot-core/build.gradle, line 156 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1367#-MzTqO9tAewHkky1lDjC:-MzTqO9tAewHkky1lDjD:b-1rzojm) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/bf2a3d94bcc0dd809b36c5e09c2ddadc2b65dd24/inspectit-ocelot-core/build.gradle#L156)):*
> ```Gradle
> cyclonedxBom {
>     // includeConfigs is the list of configuration names to include when generating the BOM (leave empty to include every configuration)
>     includeConfigs += ["runtimeClasspath"]
> ```

As discussed, only dependencies in the runtimeClasspath are taken into account.

**Review by mariusoe — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1367)* status: all files reviewed, 2 unresolved discussions (waiting on @aaronweissler)

___
*[.circleci/config.yml, line 61 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1367#-MznXUjl0xQ-oBeiEHcp:-MznXUjl0xQ-oBeiEHcq:bkuvnzw) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/a2ed689d0f89f9cc73e6d65e194358bd12b945e9/.circleci/config.yml#L61)):*
> ```YAML
>       - run: cp ~/inspectit/repo/components/inspectit-ocelot-configurationserver/build/libs/inspectit-ocelot-configurationserver-${CIRCLE_TAG}.jar ~/inspectit/artifacts
>       - run: cp ~/inspectit/repo/components/inspectit-ocelot-eum-server/build/libs/inspectit-ocelot-eum-server-${CIRCLE_TAG}.jar ~/inspectit/artifacts
>       - run: cp ~/inspectit/repo/inspectit-ocelot-core/build/reports/bom.json ~/inspectit/artifacts/inspectit-ocelot-agent-bom.json
> ```

Maybe we should bundle all of these bom files within a single zip-archive file. Doing this, we don't overload the release artifacts with all of thoses bom files.
What do you think?
___
*[components/inspectit-ocelot-configurationserver/build.gradle, line 84 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1367#-MznXBy2EtVwyQk6C9nN:-MznXBy33gOCV-dpVkgN:bf5lsa8) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/a2ed689d0f89f9cc73e6d65e194358bd12b945e9/components/inspectit-ocelot-configurationserver/build.gradle#L84)):*
> ```Gradle
> 
> cyclonedxBom {
>     // includeConfigs is the list of configuration names to include when generating the BOM (leave empty to include every configuration)
> ```

Imo we don't need this comment. Please remove it in each file.

**Review by aaronweissler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1367)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @mariusoe)

___
*[.circleci/config.yml, line 61 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1367#-MznXUjl0xQ-oBeiEHcp:-MztpA-VDmeSvuHW1NVb:b7btyiw) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/a2ed689d0f89f9cc73e6d65e194358bd12b945e9/.circleci/config.yml#L61)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Maybe we should bundle all of these bom files within a single zip-archive file. Doing this, we don't overload the release artifacts with all of thoses bom files.
What do you think?
</blockquote></details>

I like the idea, is added now :)
___
*[components/inspectit-ocelot-configurationserver/build.gradle, line 84 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1367#-MznXBy2EtVwyQk6C9nN:-MztpG_588ev7CYIhH5p:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/a2ed689d0f89f9cc73e6d65e194358bd12b945e9/components/inspectit-ocelot-configurationserver/build.gradle#L84)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Imo we don't need this comment. Please remove it in each file.
</blockquote></details>

Done.

**Review by mariusoe — APPROVED** [review]
> Reviewed 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1367)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronweissler)

**Pull request merged**
