### PR TITLE
Fix match expression documentation

### PR DESCRIPTION
**Pull request by Patrick-Eichhorn**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/939)

### CODE REVIEW

**Review by Henning-Schulz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/939)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/topics/editor/HandlerEditor.js, line 33 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/939#-MK3fYMW2iStN8VEerQz:-MK3fYMW2iStN8VEerR-:b-xogaku) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e1a9397f26ae5a7d18d6cceb759346860b8ba942/components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/topics/editor/HandlerEditor.js#L33)):*
> ```JavaScript
>               {'Options are: level(), changed() and tag matching.'}
>               <br />
>               {'Example: (level() >= WARNING) AND ("host" == \'s001.example.com\')'}
> ```

My feeling says it should be the same quote sign, e.g., `"host" == "s001.example.com"`, but I might be wrong.

**Review by Patrick-Eichhorn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/939)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Henning-Schulz)

___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/topics/editor/HandlerEditor.js, line 33 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/939#-MK3fYMW2iStN8VEerQz:-MK58Fsr6-C0apmMIpTq:b5tk2t2) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e1a9397f26ae5a7d18d6cceb759346860b8ba942/components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/topics/editor/HandlerEditor.js#L33)):*
<details><summary><i>Previously, Henning-Schulz (Henning Schulz) wrote…</i></summary><blockquote>

My feeling says it should be the same quote sign, e.g., `"host" == "s001.example.com"`, but I might be wrong.
</blockquote></details>

This is due to the Tick Script-, more precisely the InfluxDB -Syntax.
(Double quotes specify the name of a column, single quotes are string literals).

**Review by Henning-Schulz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/939)* status: 0 of 1 files reviewed, all discussions resolved

___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/topics/editor/HandlerEditor.js, line 33 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/939#-MK3fYMW2iStN8VEerQz:-MK58pFo31kHegaj32M7:b-xmrgo1) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e1a9397f26ae5a7d18d6cceb759346860b8ba942/components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/topics/editor/HandlerEditor.js#L33)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

This is due to the Tick Script-, more precisely the InfluxDB -Syntax.
(Double quotes specify the name of a column, single quotes are string literals).
</blockquote></details>

All right, good to know :+1:

**Review by Henning-Schulz — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/939)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
