### PR TITLE
Introduce issue templates

### PR DESCRIPTION
**Pull request by MariusBrill**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1312)

### CODE REVIEW

**Review by aaronweissler — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1312)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MariusBrill)

**Review by heiko-holz — APPROVED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1312)* status: all files reviewed, 1 unresolved discussion (waiting on @MariusBrill)

___
*[.github/ISSUE_TEMPLATE/bug_report.md, line 25 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1312#-MwRAAwP-QyvmcFr21me:-MwRAAwP-QyvmcFr21mf:byffhoj) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c831a3e3c80f9252de559f70073dd98e34b27a49/.github/ISSUE_TEMPLATE/bug_report.md#L25)):*
> ```Markdown
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> If you have a Stacktrace, please copy and paste it here as text.
> ```

Do we rather want the users to put the stacktrace into the **screenshots** sections or add a section **stacktrace**?

**Comment by MariusBrill** [comment]
@heiko-holz good question!  I think we could either rename the section to something like _Additional Material_ or introduce a second section _Stacktraces_ (or any other speaking name). 

What would you say is the better option?

**Review by heiko-holz — DISMISSED** [review]
I would favor "Additional information (screenshots, stacktrace, ."

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1312#-:-MwRD_ACESRQPE1Q-qdh:b-9h9m3y)* status: all files reviewed, 1 unresolved discussion (waiting on @MariusBrill)

**Review by aaronweissler — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1312)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MariusBrill)

**Pull request merged**
