### PR TITLE
Closes #1356 - fix(config) - Add converter for String to ExporterEnabledState

### LINKED ISSUE #1356: [Bug] - Conversion of old boolean values to new ExporterEnabledState does not work when in quotes
**Describe the bug**
When the boolean for the enabled property is written in quotes, it is treated as a String by Spring and therefore can not be converted using the BooleanToExporterEnabledStateConverter

**To Reproduce**
1. Set an enabled property to `"false"`
2. Start any core test that loads properties
3. See error in logs

**Expected behavior**
Convert the value to equivalent ExporterEnabledState

**Additional information (screenshots, stack traces, etc.)**
Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [rocks.inspectit.ocelot.config.model.exporters.ExporterEnabledState] for value 'false'; nested exception is java.lang.IllegalArgumentException: No enum constant rocks.inspectit.ocelot.config.model.exporters.ExporterEnabledState.false

### PR DESCRIPTION
**Pull request by aaronweissler**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1357)

### CODE REVIEW

**Review by heiko-holz — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1357)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronweissler)

___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/StringToExporterEnabledStateConverter.java, line 34 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1357#-MyliLsqBzleQNsRvI3c:-MyliLsqBzleQNsRvI3d:b8on2h4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b680b7bd532a5a10a6ffc30481bc6b6b26a2f08/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/StringToExporterEnabledStateConverter.java#L34)):*
> ```Java
>         } else {
>             return ExporterEnabledState.valueOf(source);
>         }
> ```

I would suggest not to have the same warning twice in the code.

Suggestion:

```Java
if (source.equalsIgnoreCase("true") || source.equalsIgnoreCase("true")) {
            // log deprecation warn
            log.warn("You are using the deprecated Boolean-based style with quotes to define whether an exporter is enabled. This style will be invalid in future releases of InspectIT Ocelot.");
            return source.equalsIgnoreCase("true") ? ExporterEnabledState.IF_CONFIGURED : ExporterEnabledState.DISABLED;
        }
```



_Code quote:_
```Java
            // log deprecation warn
            log.warn("You are using the deprecated Boolean-based style with quotes to define whether an exporter is enabled. This style will be invalid in future releases of InspectIT Ocelot.");
            return ExporterEnabledState.IF_CONFIGURED;
```

**Review by heiko-holz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1357)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronweissler)

**Review by aaronweissler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1357)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronweissler)

___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/StringToExporterEnabledStateConverter.java, line 34 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1357#-MyliLsqBzleQNsRvI3c:-Mylk48P4wvX7lEva1lx:bjp4tmk) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b680b7bd532a5a10a6ffc30481bc6b6b26a2f08/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/StringToExporterEnabledStateConverter.java#L34)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I would suggest not to have the same warning twice in the code.

Suggestion:

```Java
if (source.equalsIgnoreCase("true") || source.equalsIgnoreCase("true")) {
            // log deprecation warn
            log.warn("You are using the deprecated Boolean-based style with quotes to define whether an exporter is enabled. This style will be invalid in future releases of InspectIT Ocelot.");
            return source.equalsIgnoreCase("true") ? ExporterEnabledState.IF_CONFIGURED : ExporterEnabledState.DISABLED;
        }
```
</blockquote></details>

I wondered about that too, but didn't really like having another nested if, so I like the idea with the inline if, I will change it to that

**Review by heiko-holz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1357#-:-MypfELM-egO073YWEbm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronweissler)

**Pull request merged**
