### PR TITLE
Closes #1555: [Feature] - fix StackTraceSampler / AutoTracing

### LINKED ISSUE #1555: [Feature] - fix StackTraceSampler / AutoTracing
**Describe the feature**
As of version `v2.0.0+`, the Auto-Tracing (Stack-Trace-Sampling) functionality broke.

This feature should be re-enabled with OpenTelemetry

### PR DESCRIPTION
**Pull request by heiko-holz**
Closes #1555

- - -
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558)

### CODE REVIEW

**Review by Dimi-Ma — CHANGES_REQUESTED** [review]
> Reviewed 81 of 81 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558)* status: all files reviewed, 11 unresolved discussions (waiting on @heiko-holz)

*[a discussion](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLtRa374PUhC488s6XR:-NLtRa384VWC9us5Nlj2:basrvax) (no related file):*
There were a few inconsistencies regarding code formatting, maybe we should discuss this in a Meeting.

___
___
*[`inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4J2TraceIdAutoInjectorTest.java` line 58 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NL_W7A-7jJRdjI1aaZ6:-NL_W7A-7jJRdjI1aaZ7:b-15q7n1) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4J2TraceIdAutoInjectorTest.java#L58)):*
> ```Java
>         Span span = tracer.spanBuilder("test").startSpan();
>         try (Scope scope = span.makeCurrent()) {
>             traceId = Span.current().getSpanContext().getTraceId();
> ```

in ```LogCorelationTest.java``` this part was extracted into their own function so to keep everything the same we should do this here too or move the previous implementation into a higher order to be able to use this function everywhere its needed and don't have redundancy.
___
*[`inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4JTraceIdAutoInjectorTest.java` line 36 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NL_X7LZ-7E2ywjkZRWt:-NL_X7L_9DgQZzps8B0t:bdsa9la) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4JTraceIdAutoInjectorTest.java#L36)):*
> ```Java
> 
>         try (Scope scope = tracer.spanBuilder("test").startSpan().makeCurrent()) {
>             traceId = Span.current().getSpanContext().getTraceId();
> ```

Same here for the extraction into their own function.
___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java` line 61 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NL_zGvb-yjlyRgM3VZf:-NL_zGvb-yjlyRgM3VZg:b-12p551) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L61)):*
> ```Java
>     /**
>      * Registers a new {@link rocks.inspectit.ocelot.core.service.DynamicallyActivatableService trace exporter service} that is used to export {@link io.opentelemetry.sdk.trace.data.SpanData} for sampled {@link io.opentelemetry.api.trace.Span}s
>      * This method should ONLY be used in tests of the {@code agent} package.
> ```

Is it a good idea to implement a test only function here? 
___
*[`inspectit-ocelot-core/src/main/java/io/opentelemetry/sdk/trace/OcelotAnchoredClockUtils.java` line 87 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLeMcCKBeFffB617qEN:-NLeMcCKBeFffB617qEO:bfz89nx) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/io/opentelemetry/sdk/trace/OcelotAnchoredClockUtils.java#L87)):*
> ```Java
>             throw new RuntimeException(e);
>         }
> ```

This space is not needed.
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/MethodHookConfigurationResolver.java` line 55 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLf8GQA75YEgyPb57cF:-NLf8GQA75YEgyPb57cG:b4uf7fw) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/MethodHookConfigurationResolver.java#L55)):*
> ```Java
>         boolean traceEntryHook = Stream.of(matchedRules.stream()
>                 .map(InstrumentationRule::getPreEntryActions)
>                 .flatMap(Collection::stream), matchedRules.stream()
> ```

I think it would be better to format this one with the commas instead of the dots to make it more readable for each value. e.g. 



_Code snippet:_
```Java
        boolean traceEntryHook = Stream.of(
            matchedRules.stream().map(InstrumentationRule::getPreEntryActions).flatMap(Collection::stream), 
            matchedRules.stream().map(InstrumentationRule::getEntryActions).flatMap(Collection::stream), 
            matchedRules.stream().map(InstrumentationRule::getPostEntryActions).flatMap(Collection::stream)).flatMap(s -> s).anyMatch(ActionCallConfig::isActionTracing);
            ...
```
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java` line 3 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLfGMQxDHSXAvUAOC-S:-NLfGMQxDHSXAvUAOC-T:bq21tzs) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java#L3)):*
> ```Java
> package rocks.inspectit.ocelot.core.instrumentation.context;
> 
> import io.opencensus.tags.*;
> ```

Is this something that can't be done with open telemetry? 
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGenerator.java` line 176 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLfHvG0BuaaH81XYmps:-NLfHvG0BuaaH81XYmpt:b-cdhvmp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGenerator.java#L176)):*
> ```Java
>         String sampleProbability = tracing.getSampleProbability();
>         if (!StringUtils.isBlank(sampleProbability)) {
>             
> ```

this empty line can be removed.
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/trace/samplers/HybridParentTraceIdRatioBasedSampler.java` line 52 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLfZ-H8Cv8WTVcINKEi:-NLfZ-H8Cv8WTVcINKEj:b-lcbdt0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/trace/samplers/HybridParentTraceIdRatioBasedSampler.java#L52)):*
> ```Java
> 
>         // if any parent link has been sampled, keep the sampling decision.
>         if (isAnyParentLinkSampled) {
> ```

Could we not put this if into the previous if statement with an OR since they are both returning the same? 
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/utils/OpenCensusShimUtils.java` line 90 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLf_mOK-Ea9h9l8WvHd:-NLf_mOK-Ea9h9l8WvHe:b-i321t9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/utils/OpenCensusShimUtils.java#L90)):*
> ```Java
>     }
> 
>     // TODO: über Reflection auf die Copy-Helper-Methode zuzugreifen, anstatt diese zu kopieren
> ```

Is this TODO supposed to be finished in this PR? If not it might be a better idea to create a separate Ticket for it before it gets forgotten.
___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/WriteSpanAttributesTest.java` line 30 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLtOOR4Ddcw9gnDAttU:-NLtOOR4Ddcw9gnDAttV:b4c8hdi) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/WriteSpanAttributesTest.java#L30)):*
> ```Java
>     IObfuscatory obfuscatory;
> 
>     @Spy
> ```

Do we still need to use ```@Spy```here? If yes, a comment explaining why would be helpful :slightly_smiling_face:

**Review by Dimi-Ma — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558)* status: all files reviewed, 11 unresolved discussions (waiting on @heiko-holz)

*[a discussion](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLtRa374PUhC488s6XR:-NLtV7d16wQrDtIEKNWz:b-9ik2bb) (no related file):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

There were a few inconsistencies regarding code formatting, maybe we should discuss this in a Meeting.
</blockquote></details>

Additionally, there is a failing Test in the class ```JaegerThriftExporterServiceIntTest```which i have tested multiple times with the name ```verifyTraceSent```. 

___

**Review by Dimi-Ma — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558)* status: all files reviewed, 11 unresolved discussions (waiting on @heiko-holz)

*[a discussion](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLtRa374PUhC488s6XR:-NLuO0_G3I7EnwPPks0w:bqaxeys) (no related file):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

Additionally, there is a failing Test in the class ```JaegerThriftExporterServiceIntTest```which i have tested multiple times with the name ```verifyTraceSent```. 
</blockquote></details>

Follow up information: the failing Test only fails, if all other tests run too but passes if run alone, this indicates that something isn't cleaned up properly from previous tests.

___

**Review by Dimi-Ma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558)* status: all files reviewed, 10 unresolved discussions (waiting on @heiko-holz)

___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java` line 3 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLfGMQxDHSXAvUAOC-S:-NM31iL6--5MBBTVlHld:b-8rdv33) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java#L3)):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

Is this something that can't be done with open telemetry? 
</blockquote></details>

Since the changes only were supposed to affect traces and not metrics i will retract this comment.

**Review by heiko-holz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558)* status: all files reviewed, 10 unresolved discussions (waiting on @Dimi-Ma)

*[a discussion](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLtRa374PUhC488s6XR:-NM35rHs6FWJAHGp2rG1:b-jujidu) (no related file):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

Follow up information: the failing Test only fails, if all other tests run too but passes if run alone, this indicates that something isn't cleaned up properly from previous tests.
</blockquote></details>

Let's have a chat and look into this issue

___
___
*[`inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4J2TraceIdAutoInjectorTest.java` line 58 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NL_W7A-7jJRdjI1aaZ6:-NLyW3Eh8d5yk6-WAZh5:bdoe33v) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4J2TraceIdAutoInjectorTest.java#L58)):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

in ```LogCorelationTest.java``` this part was extracted into their own function so to keep everything the same we should do this here too or move the previous implementation into a higher order to be able to use this function everywhere its needed and don't have redundancy.
</blockquote></details>

I agree.
I have refactored `Log4J2TraceIdAutoInjectorTest.java` and moved the logic to start the span, extract the trace id, and log the message into the method `startSpanAndExtractTraceIdAndLogMessage`
___
*[`inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4JTraceIdAutoInjectorTest.java` line 36 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NL_X7LZ-7E2ywjkZRWt:-NLyY-imCsLAnNF73qMm:b-ajd0eu) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4JTraceIdAutoInjectorTest.java#L36)):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

Same here for the extraction into their own function.
</blockquote></details>

I would leave this class as it. In my opinion, we would create more boilerplate code when trying to extract this into an extra method as this is the only call to `Span.current().getSpanContext().getTraceId();` in this class
___
*[`inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java` line 61 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NL_zGvb-yjlyRgM3VZf:-NLyZ-tg9Z4z_VHAOH-a:b2qz01u) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/opentelemetry/IOpenTelemetryController.java#L61)):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

Is it a good idea to implement a test only function here? 
</blockquote></details>

I added this for the tests in the `agent` package, as we do not have access to the `core` package there.
Otherwise, I could have directly worked with the `OpenTelemetryControllerImpl.java` class.

I would not know how I could otherwise register a trace exporter in the agent test package, without re-building OpenTelemetry from scratch and discarding the configurations.

Let's discuss this in a meeting.
___
*[`inspectit-ocelot-core/src/main/java/io/opentelemetry/sdk/trace/OcelotAnchoredClockUtils.java` line 87 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLeMcCKBeFffB617qEN:-NLy_-L2C64OUlrWBILW:bsc6cuy) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/io/opentelemetry/sdk/trace/OcelotAnchoredClockUtils.java#L87)):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

This space is not needed.
</blockquote></details>

Thanks for catching this.
I have deleted the empty line.
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/MethodHookConfigurationResolver.java` line 55 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLf8GQA75YEgyPb57cF:-NLy_XSV-AeN9pXX8D2o:bmu0gnj) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/MethodHookConfigurationResolver.java#L55)):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

I think it would be better to format this one with the commas instead of the dots to make it more readable for each value. e.g. 
</blockquote></details>

I cannot really follow.
What do you exactly mean, can you make an example?
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java` line 3 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLfGMQxDHSXAvUAOC-S:-NLy_nPzEsA-kIaIcLJf:bl4vuhs) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java#L3)):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

Is this something that can't be done with open telemetry? 
</blockquote></details>

It can be replaced at a later point with `Baggage` and `Attributes` of OpenTelemetry,
However, this would add more complexity (and take at least 2 more days to this ticket).
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGenerator.java` line 176 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLfHvG0BuaaH81XYmps:-NLya1yi7vwiuKk2jxsU:boxkspe) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGenerator.java#L176)):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

this empty line can be removed.
</blockquote></details>

Thanks, I have deleted the empty line.
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/trace/samplers/HybridParentTraceIdRatioBasedSampler.java` line 52 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLfZ-H8Cv8WTVcINKEi:-NLya9l--iKrXellXS9h:b-ko2tp1) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/trace/samplers/HybridParentTraceIdRatioBasedSampler.java#L52)):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

Could we not put this if into the previous if statement with an OR since they are both returning the same? 
</blockquote></details>

Technically we could. However, I have followed OpenCensus' implementation of https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/trace/samplers/ProbabilitySampler.java.
But we can change it to this if you think this is more readable:
```Java
 // If the parent or any parent link has been sampled keep, the sampling decision.
        if ((parentSpanContext.isValid() && parentSpanContext.isSampled()) || isAnyParentLinkSampled(parentLinks)) {
            return SamplingResult.recordAndSample();
        }

```
___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/utils/OpenCensusShimUtils.java` line 90 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLf_mOK-Ea9h9l8WvHd:-NLycFTLEGUszZZcoK3g:b-57svhy) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/utils/OpenCensusShimUtils.java#L90)):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

Is this TODO supposed to be finished in this PR? If not it might be a better idea to create a separate Ticket for it before it gets forgotten.
</blockquote></details>

Good catch!
Actually, the methods `mapKind` where not used. Thus, I have removed the `TODO` statement and the unused methods.
___
*[`inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/WriteSpanAttributesTest.java` line 30 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1558#-NLtOOR4Ddcw9gnDAttU:-NM34jiR2lMMGO7ki-TP:b-efdnnk) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/WriteSpanAttributesTest.java#L30)):*
<details><summary><i>Previously, Dimi-Ma (Dimitiros Mantas) wrote…</i></summary><blockquote>

Do we still need to use ```@Spy```here? If yes, a comment explaining why would be helpful :slightly_smiling_face: 
</blockquote></details>

Yes, we need the `@Spy` to have a dummy span for the evaluation in `verifyAttributesWritten`. I have added a comment

**Comment by heiko-holz** [comment]
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/trace/samplers/HybridParentTraceIdRatioBasedSampler.java` line 52 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1558#-NLfZ-H8Cv8WTVcINKEi:-NM3QC15DIGAaJD9Ytup:b-tesrja) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/trace/samplers/HybridParentTraceIdRatioBasedSampler.java#L52)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Technically we could. However, I have followed OpenCensus' implementation of https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/trace/samplers/ProbabilitySampler.java.
But we can change it to this if you think this is more readable:
```Java
 // If the parent or any parent link has been sampled keep, the sampling decision.
        if ((parentSpanContext.isValid() && parentSpanContext.isSampled()) || isAnyParentLinkSampled(parentLinks)) {
            return SamplingResult.recordAndSample();
        }

```
</blockquote></details>

We have agreed to change it to the shorter version

**Review by heiko-holz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1558)* status: 72 of 81 files reviewed, 10 unresolved discussions (waiting on @Dimi-Ma)

___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/MethodHookConfigurationResolver.java` line 55 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1558#-NLf8GQA75YEgyPb57cF:-NM3OMp3011ganeXCgfP:bcu8vth) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/MethodHookConfigurationResolver.java#L55)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I cannot really follow.
What do you exactly mean, can you make an example?
</blockquote></details>

After the discussion, we agreed that we need to tweak the code styling of inspectIT Ocelot, but not in this ticket.

**Review by Dimi-Ma — APPROVED** [review]
> Reviewed 7 of 7 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1558)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @heiko-holz)

___
*[`inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4JTraceIdAutoInjectorTest.java` line 36 at r1](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1558#-NL_X7LZ-7E2ywjkZRWt:-NM3OiKQ4vxbxRIg7EqZ:bufo3vj) ([raw file](https://github.com/inspectIT/inspectit-ocelot/blob/1cf6fc01578c41737c9647fa50421db52ed74a37/inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4JTraceIdAutoInjectorTest.java#L36)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

I would leave this class as it. In my opinion, we would create more boilerplate code when trying to extract this into an extra method as this is the only call to `Span.current().getSpanContext().getTraceId();` in this class
</blockquote></details>

Yes, you are right. I probably overlooked the fact that it was the only call in this class.

**Pull request merged**
