### PR TITLE
Closes #1285 - Agents regularly report status to config server

### LINKED ISSUE #1285: Agents regularly report status to config server
All agents should report their status (error, warning, ok) to the config server when connecting/getting the configuration file. This information can be retrieved from error or warning logs that occurred, cf. #1284

The status can later be used to display it in the config sever UI.

### PR DESCRIPTION
**Pull request by Henning-Schulz**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377)

### CODE REVIEW

**Review by MariusBrill — DISMISSED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377)* status: all files reviewed, 7 unresolved discussions (waiting on @Henning-Schulz)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManager.java, line 63 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-MztIpW0AM9BfyZm0QYy:-MztIpW0AM9BfyZm0QYz:bjz1j87) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManager.java#L63)):*
> ```Java
>     public void notifyAgentConfigurationFetched(Map<String, String> agentAttributes, Map<String, String> headers, AgentConfiguration resultConfiguration) {
>         AgentMetaInformation metaInformation = AgentMetaInformation.of(headers);
>         AgentHealth agentHealth = AgentHealth.valueOf(headers.getOrDefault(HEADER_AGENT_HEALTH, "OK"));
> ```

Should the default value be "OK"? Or would it be better to assume the status is not OK when this status is not explicitly set?
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java, line 29 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-MzxjbmtDPHRMXD9jmHa:-MzxjbmtDPHRMXD9jmHb:bijfotz) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java#L29)):*
> ```Java
> public class InternalProcessingAppender extends AppenderBase<ILoggingEvent> {
> 
>     private static final NavigableMap<String, Class<?>> INVALIDATORS = new TreeMap<>();
> ```

I think we could use a short description here



_Code quote:_
```Java
    private static final NavigableMap<
```
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java, line 33 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-Mzxo9pC-DKORbtqmO6r:-Mzxo9pC-DKORbtqmO6s:b-ic0bwr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java#L33)):*
> ```Java
>     private static final Map<Class<? extends Observer>, Observer> observers = new HashMap<>();
> 
>     static {
> ```

Maybe a description would be nice here too
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java, line 102 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-Mzxop_H-V4EpkmYyfHD:-Mzxop_H-V4EpkmYyfHE:b-rggeh9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java#L102)):*
> ```Java
>      * Observer to logging events.
>      */
>     public interface Observer {
> ```

Maybe we should rename this to something like LoggingEventObserver since there is already an Observer Interface in java.until?
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java, line 110 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-MzxpO1k0lm8Ja89q9Cl:-MzxpO1k0lm8Ja89q9Cm:b-q7lyuq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java#L110)):*
> ```Java
>          * @param invalidator Class whose instances invalidate the log event when being sent as event, e.g., {@link rocks.inspectit.ocelot.core.config.InspectitConfigChangedEvent}. May be null.
>          */
>         void onLoggingEvent(ILoggingEvent event, Class<?> invalidator);
> ```

In the classic Observer-pattern shouldn't there just be one update() function upon which the observer obtains the state from the observed object?
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManager.java, line 42 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-MzxqaRs7S6iiqVITflw:-MzxqaRs7S6iiqVITflx:b-6am2zh) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManager.java#L42)):*
> ```Java
>     private final SelfMonitoringService selfMonitoringService;
> 
>     private final Map<Class<?>, AgentHealth> invalidatableHealth = new ConcurrentHashMap<>();
> ```

I think we could use a short description here too.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/event/AgentHealthChangedEvent.java, line 18 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-Mzxrtx15B5az-uB0LQM:-Mzxrtx15B5az-uB0LQN:bagsbau) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/event/AgentHealthChangedEvent.java#L18)):*
> ```Java
>      */
>     @Getter
>     private final AgentHealth oldHealth;
> ```

Do we need this variable? Couldn't we also derive it from the AgentStatusManager?

**Review by Henning-Schulz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377)* status: 22 of 29 files reviewed, 7 unresolved discussions (waiting on @MariusBrill)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManager.java, line 63 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-MztIpW0AM9BfyZm0QYy:-N-O6VuH5LtCRWuYJkL-:b-54v8na) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManager.java#L63)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Should the default value be "OK"? Or would it be better to assume the status is not OK when this status is not explicitly set?
</blockquote></details>

Good point. If the status is not provided by the agent (e.g., because of an old version), let's do not assume one. I now set it only when provided, defaulting to null.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java, line 29 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-MzxjbmtDPHRMXD9jmHa:-N-O6qOD6KwXwPu8fbnA:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java#L29)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

I think we could use a short description here
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java, line 33 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-Mzxo9pC-DKORbtqmO6r:-N-1vwaOCZfsYaDNaNiM:b-xfbiw3) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java#L33)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Maybe a description would be nice here too
</blockquote></details>

As discussed, description above should be enough.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java, line 102 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-Mzxop_H-V4EpkmYyfHD:-N-O6tEZ-HlxnbngMS8W:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java#L102)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Maybe we should rename this to something like LoggingEventObserver since there is already an Observer Interface in java.until?
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java, line 110 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-MzxpO1k0lm8Ja89q9Cl:-N-O6tpm1Zbvl2aRT-iG:b-py7cqt) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppender.java#L110)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

In the classic Observer-pattern shouldn't there just be one update() function upon which the observer obtains the state from the observed object?
</blockquote></details>

You are right, this is not really an observer. I have renamed the class.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManager.java, line 42 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-MzxqaRs7S6iiqVITflw:-N-O70469u3FSipk1gwB:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManager.java#L42)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

I think we could use a short description here too.
</blockquote></details>

Done.
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/event/AgentHealthChangedEvent.java, line 18 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-Mzxrtx15B5az-uB0LQM:-N-1tS0tEYzfjgjXsuDN:bqokbdz) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/event/AgentHealthChangedEvent.java#L18)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Do we need this variable? Couldn't we also derive it from the AgentStatusManager?
</blockquote></details>

As discussed, we use the same pattern as in, e.g., InspectitConfigChangedEvent, which contains the old and new config.

**Review by heiko-holz — COMMENTED** [review]
> Reviewed 1 of 29 files at r1, 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377)* status: 28 of 29 files reviewed, 9 unresolved discussions (waiting on @Henning-Schulz and @MariusBrill)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManager.java, line 63 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-MztIpW0AM9BfyZm0QYy:-N-S4cBV6zVac3bNEbU_:botgjr6) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManager.java#L63)):*
<details><summary><i>Previously, Henning-Schulz (Henning Schulz) wrote…</i></summary><blockquote>

Good point. If the status is not provided by the agent (e.g., because of an old version), let's do not assume one. I now set it only when provided, defaulting to null.
</blockquote></details>

Based on the comment above, wouldn't it be more suitable to have an `UNKNOWN` default status?
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppenderTest.java, line 69 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-N-S8QVwE-DyZpe09Rt4:-N-S8QVwE-DyZpe09Rt5:b-nsm8cx) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/58c1d3bbfd7ca3771c3870964d1507680bb1fa09/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppenderTest.java#L69)):*
> ```Java
>             ILoggingEvent instrumentationEvent = new LoggingEvent("com.dummy.Method", (Logger) LoggerFactory.getLogger(InstrumentationManager.class), Level.INFO, "Dummy Info", new Throwable(), new String[]{});
> 
>             InternalProcessingAppender.LogEventConsumer logEventConsumer = Mockito.mock(InternalProcessingAppender.LogEventConsumer.class);
> ```

you could also move this and the next line into the `@BeforeEach` method, or even create fields for the `logEventConsumer` and `instrumentationEvent` to avoid copy&paste.
The invocation count on the mock `logEventConsumer` could be reset in the `@BeforeEach` method
___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManagerTest.java, line 55 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-N-S8xleAcQlQenw7rzC:-N-S8xleAcQlQenw7rzD:b-3kpylp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/58c1d3bbfd7ca3771c3870964d1507680bb1fa09/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManagerTest.java#L55)):*
> ```Java
>         executorService = new ScheduledThreadPoolExecutor(1);
> 
>         config = new InspectitConfig();
> ```

why do you set the config and the context in the `@BeforeEach` and not in a static `@BeforeAll` method?

**Review by heiko-holz — DISMISSED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377)* status: all files reviewed, 9 unresolved discussions (waiting on @Henning-Schulz and @MariusBrill)

**Review by Henning-Schulz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377)* status: 27 of 29 files reviewed, 7 unresolved discussions (waiting on @heiko-holz and @MariusBrill)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManager.java, line 63 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-MztIpW0AM9BfyZm0QYy:-N-SU4z3A6-6-CLs5G_7:b6naelr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManager.java#L63)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Based on the comment above, wouldn't it be more suitable to have an `UNKNOWN` default status?
</blockquote></details>

That would mean we add `UNKNOWN` to the AgentHealth enum (which is used in the agent and the config server), which I honestly don't like. It does not make any sense in the agent, as it always knows is health. It only makes sense in the configuration server, in case an agent (because its version is too old) did not report a status. And it should be handled somehow special in that case. So I think it is better to have some special value that indicates no health is defined, a.k.a. `null`.

If we want to make the potential absence of a health value more explicit, we could use an `Optional<AgentHealth>`, but imho it does not really add any value here.

**Comment by heiko-holz** [comment]
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManager.java, line 63 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-MztIpW0AM9BfyZm0QYy:-N-SkMvr8VDQndf0BUzg:b9yyb5x) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManager.java#L63)):*
<details><summary><i>Previously, Henning-Schulz (Henning Schulz) wrote…</i></summary><blockquote>

That would mean we add `UNKNOWN` to the AgentHealth enum (which is used in the agent and the config server), which I honestly don't like. It does not make any sense in the agent, as it always knows is health. It only makes sense in the configuration server, in case an agent (because its version is too old) did not report a status. And it should be handled somehow special in that case. So I think it is better to have some special value that indicates no health is defined, a.k.a. `null`.

If we want to make the potential absence of a health value more explicit, we could use an `Optional<AgentHealth>`, but imho it does not really add any value here.
</blockquote></details>

Okay, understood.
I wasn't aware that it is only version-dependent. In a scenario where for example an error would prevent the agent of setting its health, the `UNKNOWN` value would be appropriate.

I agree that `Optional<...>` is not necessary.

**Review by heiko-holz — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377)* status: all files reviewed, 7 unresolved discussions (waiting on @MariusBrill)

___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppenderTest.java, line 24 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-N-SkrGc8G5v5uhxOWkw:-N-SkrGc8G5v5uhxOWkx:b-oykzeb) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/40852ed46c25b842194944a49dcdf3633afa806b/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/logging/logback/InternalProcessingAppenderTest.java#L24)):*
> ```Java
> public class InternalProcessingAppenderTest {
> 
>     private static final ILoggingEvent GENERAL_EVENT = new LoggingEvent("com.dummy.Method", (Logger) LoggerFactory.getLogger(LogMetricsRecorderTest.class), Level.INFO, "Dummy Info", new Throwable(), new String[]{});
> ```

Nice refactoring :)

**Review by Henning-Schulz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377)* status: 26 of 29 files reviewed, 7 unresolved discussions (waiting on @MariusBrill)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManager.java, line 63 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377#-MztIpW0AM9BfyZm0QYy:-N-WtlE-7UuG7ClzyNt4:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/91f821445026b37e8c2361da5e5c03b3a0131e72/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManager.java#L63)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Okay, understood.
I wasn't aware that it is only version-dependent. In a scenario where for example an error would prevent the agent of setting its health, the `UNKNOWN` value would be appropriate.

I agree that `Optional<...>` is not necessary.
</blockquote></details>

Done.

**Review by mariusoe — COMMENTED** [review]
> Dismissed @MariusBrill from 7 discussions.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377)* status: 26 of 29 files reviewed, all discussions resolved (waiting on @MariusBrill)

**Review by Henning-Schulz — COMMENTED** [review]
> Reviewed 19 of 29 files at r1, 5 of 7 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Henning-Schulz)

**Review by heiko-holz — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1377)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Henning-Schulz)

**Pull request merged**
