### PR TITLE
Closes #1495 - improve the behavior when agent commands fail (or are not available) due to missing configuration - frontend

### LINKED ISSUE #1495: [Feature] - improve the behavior when agent commands fail (or are not available) due to missing configuration
**Is your feature request related to a problem? Please describe.**
When the agent commands (https://inspectit.github.io/inspectit-ocelot/docs/configuration/agent-command-configuration) are not enabled, logs/config/support archive cannot be retrieved from the configuration server. Other features, such as the log preloading, also need other settings to be enabled (e.g., `inspectit.log-preloading.enabled`).

Currently, we only receive a timeout exception and a generic error message when a respective agent command fails.

**Describe the solution you'd like**
A uniform behavior for features using the agent commands when they fail due to disabled agent commands (or further configs, such as the log preloading).

I can think of either:
* an appropriate error message when the agent commands are disabled (or more settings are configured in a way that we expect a specific agent command to fail) in the `DownloadDialogue` that is triggered when one of the download agent commands is started
* disabling the buttons in the UI (i.e., logs, config, support archive) with a tooltip explaining what needs to be changed in the configuration to enable this feature

### PR DESCRIPTION
**Pull request by danipaniii**
Closes #1495 
Implementing the DynamicallyServiceObserver to register all the available services (e.g. Prometheus, Jaeger, LogPreloader) and their current state enabled/disabled.
In the UI when clicking the agents name (on the status page) a dialog window opens with a data table, listing all the services and their current state enabled/disabled.
Currently the states are being shown as disabled buttons with the labes (enabled/disabled) to show the user the current state. In the future there is the possibilty to implement a feature to activate those buttons and let the user active/deactivate a service by a simple button click.

- - -
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528)

### CODE REVIEW

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r1, 1 of 3 files at r3, 8 of 9 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528)* status: all files reviewed, 3 unresolved discussions (waiting on @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 180 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528#-NFhEbBl2KQw4LoBc5Nq:-NFhEbBl2KQw4LoBc5Nr:bveelf6) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/a60241f92403a80405930f0291d00ea496001fbb/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L180)):*
> ```JavaScript
>           }
>         `}</style>
>         <label onClick={() => this.setServiceStateDialogShown(true)}>
> ```

Currently, I am missing a tooltip for the badge that tells the user that it opens the Service State Dialogue.
Additionally, the mouse should then be a pointer (as for the buttons).

Or we add a new button to invoke the service state dialogue.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/dialogs/ServiceStateDialog.js` line 29 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528#-NFhFRFD39ivR8S1DSCh:-NFhFRFD39ivR8S1DSCi:bmyjmce) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/a60241f92403a80405930f0291d00ea496001fbb/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/dialogs/ServiceStateDialog.js#L29)):*
> ```JavaScript
>   };
> 
>   const stateTemplate = (rowData) => {
> ```

the list seems to be unordered (or the order is defined by the config-server).

I think we can add a more intuitive order.

Maybe add "categories" (e.g., `exporter`) and indent the services into their categories.
For the categories, we could just take the hierarchically next property.
___
*[`components/inspectit-ocelot-configurationserver-ui/.yarn/install-state.gz` line 0 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528#-NFhGFDH3_ozpdogjdGU:-NFhGFDH3_ozpdogjdGV:b71llr0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e7a5b5c5eb2384117c49f1102820a43c90c40f87/components/inspectit-ocelot-configurationserver-ui/.yarn/install-state.gz#L0)):*
same as with the other pull requests, this file can be deleted and the `.gitignore` updated

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528)* status: all files reviewed, 2 unresolved discussions (waiting on @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 180 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528#-NFhEbBl2KQw4LoBc5Nq:-NFr5IHB8rSMcT1E6laW:b-x1rtws) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/a60241f92403a80405930f0291d00ea496001fbb/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L180)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

I added a new button with a tooltip.
</blockquote></details>

I really like it :)
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js` line 296 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528#-NFr5AE_-qWdwWoGIFzb:-NFr5AE_-qWdwWoGIFzc:b7esiqr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ad1cebe69ee0e62f00cc2d565e546a0e384483a4/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js#L296)):*
> ```JavaScript
>     this.setServiceStateDialogShown(true);
>     this.setState({
>       settingStates: settingStates,
> ```

Should these `settingStates` be named `serviceStates`?
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/dialogs/ServiceStateDialog.js` line 29 at r5](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528#-NFhFRFD39ivR8S1DSCh:-NFr4guaE6-kOLYUU3sv:bqong30) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/a60241f92403a80405930f0291d00ea496001fbb/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/dialogs/ServiceStateDialog.js#L29)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

For now I added a functionality to order the columns by the field. So it's possible to order the name by alphabetical order and the state by enabled/disabled, also in ascending or descending order. 
Maybe we can talk about the sorting by categories, because I think this will need a little bit more thinking to implement.
</blockquote></details>

The sorting is very nice :)

Let's discuss other functionality of this view in the next weekly or a next meeting and make it another issue.

One more thing that I realized is that the buttons of the modal are named `back` and `accept`. Currently, there should only be one button with something like `okay` or `close`.  Or what should the buttons do?

**Review by heiko-holz — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r8, 5 of 7 files at r9, 1 of 1 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528#-:-NGFrU7iEdHO0KCvP7XA:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/.gitignore` line 3 at r10](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528#-NGFtB1o0odXhA0-TiWQ:-NGFtB1o0odXhA0-TiWR:b-20bjvr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9878bfe5cf88c114a1058c4d2963f6ab028ee517/components/inspectit-ocelot-configurationserver-ui/.gitignore#L3)):*
> ```ignore
> node_modules
> .next
> .yarn/*
> ```

Let's discuss this in today's sync.

See https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

**Review by heiko-holz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528)* status: all files reviewed, 2 unresolved discussions (waiting on @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js` line 296 at r7](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528#-NFr5AE_-qWdwWoGIFzb:-NGG3EH32STExtylM_fv:b-ocasnx) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ad1cebe69ee0e62f00cc2d565e546a0e384483a4/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js#L296)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Should these `settingStates` be named `serviceStates`?
</blockquote></details>

this has been fixed

**Review by heiko-holz — COMMENTED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528)* status: all files reviewed, 2 unresolved discussions (waiting on @danipaniii)

**Review by heiko-holz — APPROVED** [review]
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @danipaniii)

___
*[`components/inspectit-ocelot-configurationserver-ui/.gitignore` line 3 at r10](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528#-NGFtB1o0odXhA0-TiWQ:-NGVPeftAAHCLWtmqpeF:b-62nmtq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/9878bfe5cf88c114a1058c4d2963f6ab028ee517/components/inspectit-ocelot-configurationserver-ui/.gitignore#L3)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Let's discuss this in today's sync.

See https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored
</blockquote></details>

updated the `.gitignore` accordingly

**Comment by danipaniii** [comment]
Everything seems to be working as expected.
@heiko-holz in our last conversation we talked about the badge that is being shown in the status view and the badge overlapping the buttons.
The badge doesn't overlap with the buttons anymore, but slightly overlaps the agents service name, if the name is very long (See screenshot)
badge_longname
Since we talked about improving the styling in that part, I was wondering if we should open a new Issue to resolve this or if we should at least solve the overlapping with the badge and the name at the moment.

**Review by heiko-holz — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528)* status: 7 of 24 files reviewed, all discussions resolved (waiting on @danipaniii)

**Comment by heiko-holz** [comment]
Hey @danipaniii, good catch!
I just fixed this by reducing the `max-width` for the service name. 

Anyhow, we can open an issue after this PR to improve the code and style of the Agent Status Table.

**Review by heiko-holz — APPROVED** [review]
> Reviewed 1 of 2 files at r14, 14 of 15 files at r16, 1 of 1 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1528)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @danipaniii)

**Pull request merged**
