### PR TITLE
Closes #1298 Handle httpstatus errors in custom YAML Syntax Highlighter 

### LINKED ISSUE #1298: Handle httpstatus errors in custom YAML Syntax Highlighter

### PR DESCRIPTION
**Pull request by aaronweissler**
This also fixes some linting errors and some format errors in the default config, so all of the files there work properly with the custom highlighter.

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1299)

### CODE REVIEW

**Review by aaronweissler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1299)* status: 0 of 7 files reviewed, all discussions resolved

___
*[inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/rules/_shared/tracing.yml, line 21 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1299#-MvOU_1HEoT3uKikoq0a:-MvOlpx69AJ3Y8UKsYRd:b-ldortb) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/70c359afb61a2c86acccab57f01a06338698f880/inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/rules/_shared/tracing.yml#L21)):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

This made me wonder if the highlighter should accept keys based on Object fields in quotes as well or not. Right now an example like this would be marked as invalid, because it expects "tracing" to be written without quotes.
</blockquote></details>

Talked about it, will stay with expecting them without quotes.

**Comment by aaronweissler** [comment]
Will also add some Documentation to inspectit-ocelot-documentation before ready for review

**Review by heiko-holz — DISMISSED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1299)* status: all files reviewed, 3 unresolved discussions (waiting on @aaronweissler)

___
*[components/inspectit-ocelot-configurationserver-ui/src/components/editor/yaml-editor/InspectitOcelotHighlightRules.js, line 37 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1299#-MvSfB4j6esvw3-RQwi7:-MvSfB4j6esvw3-RQwi8:b-629kt9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/042fb584cd95dd25f3e95c0fc958b7456859f1d5/components/inspectit-ocelot-configurationserver-ui/src/components/editor/yaml-editor/InspectitOcelotHighlightRules.js#L37)):*
> ```JavaScript
> 
>   const defaultRule = {
>     defaultToken: 'text',
> ```

why was the use of `VALUE_TYPE_TEXT` wrong?
___
*[inspectit-ocelot-documentation/docs/config-server/syntax-highlighting.md, line 6 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1299#-MvSg22r6ljGX4vfxhoy:-MvSg22r6ljGX4vfxhoz:b7vq5oe) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/042fb584cd95dd25f3e95c0fc958b7456859f1d5/inspectit-ocelot-documentation/docs/config-server/syntax-highlighting.md#L6)):*
> ```Markdown
> ---
> 
> The *inspectIT Configuration Server* uses a custom [Mode for Syntax Highlighting](https://ace.c9.io/#nav=higlighter) in its Ace Editor based on the standard YAML Highlighting to help with writing your configurations.
> ```

if there is a link to `standard YAML Highlighting`, adding it would be awesome :)
___
*[inspectit-ocelot-documentation/docs/config-server/syntax-highlighting.md, line 11 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1299#-MvSgIFNBdsBtg07B2jB:-MvSgIFNBdsBtg07B2jC:b-uahlp5) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/042fb584cd95dd25f3e95c0fc958b7456859f1d5/inspectit-ocelot-documentation/docs/config-server/syntax-highlighting.md#L11)):*
> ```Markdown
> 
> - Marking illegal fields that do not fit within the Java object the current part of the YAML corresponds to, which should help with both typing and indentation errors.
> - Differentiating between keys that are predetermined by the underlying Java objects that are created from the YAML later and fields whose names you can choose yourself, e.g. the name of a scope.
> ```

maybe "whose names can be chosen freely" instead of "you can choose yourself"
___
*[inspectit-ocelot-documentation/docs/config-server/syntax-highlighting.md, line 12 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1299#-MvSgSY_9_L0XndFlxI6:-MvSgSY_9_L0XndFlxI7:bm1p2lr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/042fb584cd95dd25f3e95c0fc958b7456859f1d5/inspectit-ocelot-documentation/docs/config-server/syntax-highlighting.md#L12)):*
> ```Markdown
> - Marking illegal fields that do not fit within the Java object the current part of the YAML corresponds to, which should help with both typing and indentation errors.
> - Differentiating between keys that are predetermined by the underlying Java objects that are created from the YAML later and fields whose names you can choose yourself, e.g. the name of a scope.
> - When a value in the YAML corresponds to an Enum, impossible values for that Enum are marked as invalid.
> ```

What are `impossible values`?

**Review by aaronweissler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1299)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @heiko-holz)

___
*[components/inspectit-ocelot-configurationserver-ui/src/components/editor/yaml-editor/InspectitOcelotHighlightRules.js, line 37 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1299#-MvSfB4j6esvw3-RQwi7:-MvT6kBeCjGJrUU0Olaz:bqtejaw) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/042fb584cd95dd25f3e95c0fc958b7456859f1d5/components/inspectit-ocelot-configurationserver-ui/src/components/editor/yaml-editor/InspectitOcelotHighlightRules.js#L37)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

why was the use of `VALUE_TYPE_TEXT` wrong?
</blockquote></details>

As talked about, because this instance of 'text' has nothing to do with the Map
___
*[inspectit-ocelot-documentation/docs/config-server/syntax-highlighting.md, line 6 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1299#-MvSg22r6ljGX4vfxhoy:-MvT7Hf7-OaTIc2WFhVq:b-a33ud8) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/042fb584cd95dd25f3e95c0fc958b7456859f1d5/inspectit-ocelot-documentation/docs/config-server/syntax-highlighting.md#L6)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

if there is a link to `standard YAML Highlighting`, adding it would be awesome :)
</blockquote></details>

As talked about, unfortunately there is no readable explanation of the rules, just a pair of javascript files like ours in the ace Editor's GitHub Project
___
*[inspectit-ocelot-documentation/docs/config-server/syntax-highlighting.md, line 11 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1299#-MvSgIFNBdsBtg07B2jB:-MvT6yXxALTU3NPLnZVw:b-ptxi4k) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/042fb584cd95dd25f3e95c0fc958b7456859f1d5/inspectit-ocelot-documentation/docs/config-server/syntax-highlighting.md#L11)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

maybe "whose names can be chosen freely" instead of "you can choose yourself"
</blockquote></details>

Changed it
___
*[inspectit-ocelot-documentation/docs/config-server/syntax-highlighting.md, line 12 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1299#-MvSgSY_9_L0XndFlxI6:-MvT70Cw-3PrpyXPeak2:b-n43gyk) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/042fb584cd95dd25f3e95c0fc958b7456859f1d5/inspectit-ocelot-documentation/docs/config-server/syntax-highlighting.md#L12)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

What are `impossible values`?
</blockquote></details>

As talked about, values that are not part of an enum's set of possible values, added a short further explanation to the documentation :)

**Review by heiko-holz — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1299)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronweissler)

**Pull request merged**
