### PR TITLE
Closes #971 - Extend the "illegal tag value" error message, to specify which tag is concerned.

### LINKED ISSUE #971: Extend the "illegal tag value" error message, to specify which tag is concerned.
It is helpful to know which tag is affected by the error message.

### PR DESCRIPTION
**Pull request by Patrick-Eichhorn**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972)

### CODE REVIEW

**Review by mariusoe — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972)* status: all files reviewed, 5 unresolved discussions (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/BeaconMetricManager.java, line 53 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972#-MRTb7EZ-YufcjQ0Kqn1:-MRTb7EZ-YufcjQ0Kqn2:bglb1xe) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8fce4b2aa4081b146d9c521ac47c8b40ec2402b7/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/BeaconMetricManager.java#L53)):*
> ```Java
>         boolean successful = false;
> 
>         for (Map.Entry<String, BeaconMetricDefinitionSettings> metricDefinitionEntry : configuration.getDefinitions()
> ```

You've only formatted this file, but this code is actually a problem. In case the metric definitions map is null, an exception will occur.

Let's change this in the following way, so that we don't get a NullPointerException and the method will return successfull, too:

```
Map<String, BeaconMetricDefinitionSettings> definitions = configuration.getDefinitions();
if (CollectionUtils.isEmpty(definitions)) {
    successful = true;
} else {
    for (Map.Entry<String, BeaconMetricDefinitionSettings> metricDefinitionEntry : definitions.entrySet()) {
```
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/MeasuresAndViewsManager.java, line 110 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972#-MRTbli03m5cdKsFk2nj:-MRTbli03m5cdKsFk2nk:b-pqha34) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8fce4b2aa4081b146d9c521ac47c8b40ec2402b7/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/MeasuresAndViewsManager.java#L110)):*
> ```Java
>                 Measure measure = metrics.get(metricName);
> 
>                 if (timeWindowViewManager.isViewRegistered(metricName, viewName) || viewDefinitionSettings.getAggregation() == ViewDefinitionSettings.Aggregation.QUANTILES || viewDefinitionSettings
> ```

Can you refactor this line, so we don't have this huge one including a line break here? Maybe extract each condition in a local variable, so we can write something like `if (isRegistered && ...`
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 20 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972#-MRTcSHuEibUZhEN38f3:-MRTcSHuEibUZhEN38f4:b-mvq350) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8fce4b2aa4081b146d9c521ac47c8b40ec2402b7/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L20)):*
> ```Java
>      * If String is not valid an <code>&lt;invalid&gt;</code> TagName is created.
>      *
>      * @param value the tag value
> ```

Add the new parameter as well.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 22 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972#-MRTcQnO3ZCfwY948l0J:-MRTcQnO3ZCfwY948l0K:b-ue3d6i) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8fce4b2aa4081b146d9c521ac47c8b40ec2402b7/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L22)):*
> ```
> v
> ```
Please update documentation
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 38 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972#-MRTcmknB6WACz6Ysy6Z:-MRTcmknB6WACz6Ysy6_:b-u4dfx7) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8fce4b2aa4081b146d9c521ac47c8b40ec2402b7/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L38)):*
> ```Java
>     private static void printWarningOnce(String tagKey, String value) {
>         if (!isWarningPrinted) {
>             log.warn("Error creating value for tag <" + tagKey + ">: illegal tag value <" + value + "> converted to <invalid>");
> ```

You could do it this way, but there is a more performant and better way to use variables in log messages. The problem is that each time the application would log this line, the JVM has to create new string objects where the variables have been added. This has to be done, even in the case the log line would not be printed due to log-level settings.

Because of this, most logger provide additional methods for handling variables. Most of the time it is the same method but you can pass multiple parameters.

For this case:
```
log.warn("Error creating value for tag <{}>: illegal tag value <{}> converted to <invalid>", tagKey, value);
```

You can pass additional object to the log-method Now, you can add `{}` into the log-text which are replaced by the additonal object. In this example, the first `{}` is replaced by `tagKey` and the second `{}` is replaced by `value`.

This has the benefit that it is much easier to read and the JVM does not need to create a new string in case the logger has a different log-level configured.

**Review by Patrick-Eichhorn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972)* status: all files reviewed, 5 unresolved discussions (waiting on @mariusoe)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/BeaconMetricManager.java, line 53 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972#-MRTb7EZ-YufcjQ0Kqn1:-MRTucWKEQawT395FZv8:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8fce4b2aa4081b146d9c521ac47c8b40ec2402b7/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/BeaconMetricManager.java#L53)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

You've only formatted this file, but this code is actually a problem. In case the metric definitions map is null, an exception will occur.

Let's change this in the following way, so that we don't get a NullPointerException and the method will return successfull, too:

```
Map<String, BeaconMetricDefinitionSettings> definitions = configuration.getDefinitions();
if (CollectionUtils.isEmpty(definitions)) {
    successful = true;
} else {
    for (Map.Entry<String, BeaconMetricDefinitionSettings> metricDefinitionEntry : definitions.entrySet()) {
```
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/MeasuresAndViewsManager.java, line 110 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972#-MRTbli03m5cdKsFk2nj:-MRTueEZ1SLT0DTYb43g:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8fce4b2aa4081b146d9c521ac47c8b40ec2402b7/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/MeasuresAndViewsManager.java#L110)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Can you refactor this line, so we don't have this huge one including a line break here? Maybe extract each condition in a local variable, so we can write something like `if (isRegistered && ...`
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 20 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972#-MRTcSHuEibUZhEN38f3:-MRTufBF9XdzUr6RYXu0:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8fce4b2aa4081b146d9c521ac47c8b40ec2402b7/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L20)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Add the new parameter as well.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 22 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972#-MRTcQnO3ZCfwY948l0J:-MRTufxbEKhRJgWNRhM6:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8fce4b2aa4081b146d9c521ac47c8b40ec2402b7/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L22)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> v
> ```
Please update documentation
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java, line 38 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972#-MRTcmknB6WACz6Ysy6Z:-MRTuivK96gihx3gHPkR:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8fce4b2aa4081b146d9c521ac47c8b40ec2402b7/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java#L38)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

You could do it this way, but there is a more performant and better way to use variables in log messages. The problem is that each time the application would log this line, the JVM has to create new string objects where the variables have been added. This has to be done, even in the case the log line would not be printed due to log-level settings.

Because of this, most logger provide additional methods for handling variables. Most of the time it is the same method but you can pass multiple parameters.

For this case:
```
log.warn("Error creating value for tag <{}>: illegal tag value <{}> converted to <invalid>", tagKey, value);
```

You can pass additional object to the log-method Now, you can add `{}` into the log-text which are replaced by the additonal object. In this example, the first `{}` is replaced by `tagKey` and the second `{}` is replaced by `value`.

This has the benefit that it is much easier to read and the JVM does not need to create a new string in case the logger has a different log-level configured.
</blockquote></details>

Done.

**Review by mariusoe — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972)* status: all files reviewed, 1 unresolved discussion (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/BeaconMetricManager.java, line 57 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972#-MRUN5P68Nk8XfDTEbAm:-MRUN5P68Nk8XfDTEbAn:bl3y7g) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2c5346902f6d9acc23f46227b4f0949a5cc32e98/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/BeaconMetricManager.java#L57)):*
> ```
> configuration.getDefinitions()
> ```
use the `definitions` variable from above where you already extracted the definitions of the configuration
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/MeasuresAndViewsManager.java, line 113 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972#-MRUNG3XAsO1bYXSlwn7:-MRUNG3XAsO1bYXSlwn8:b-mq33qw) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2c5346902f6d9acc23f46227b4f0949a5cc32e98/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/MeasuresAndViewsManager.java#L113)):*
> ```Java
>                 boolean isQuantileAggregation = viewDefinitionSettings.getAggregation() == ViewDefinitionSettings.Aggregation.QUANTILES;
>                 boolean isSmoothedAverageAggregation = viewDefinitionSettings.getAggregation() == ViewDefinitionSettings.Aggregation.SMOOTHED_AVERAGE;
>                 if (isRegistered || isQuantileAggregation || isSmoothedAverageAggregation) {
> ```

Much easier to read

**Review by mariusoe — APPROVED** [review]

**Review by mariusoe — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972)* status: all files reviewed, 1 unresolved discussion (waiting on @Patrick-Eichhorn)

**Pull request merged**
