### PR TITLE
Closes #980 - Extending the alerting API to reload kapacitor tasks due to changed alerting rules

### LINKED ISSUE #980: Extending the alerting API to reload kapacitor tasks due to changed alerting rules
Actually, if alerting rules in the configuration server are updated, a restart of kapacitor is required to enable the changes in the kapacitor tasks.
An API call to kapacitor can trigger a reload of the tasks at runtime, to avoid a restart of kapacitor.

### PR DESCRIPTION
**Pull request by Patrick-Eichhorn**
Closes #980

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982)

### CODE REVIEW

**Review by mariusoe — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982)* status: all files reviewed, 4 unresolved discussions (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java, line 61 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982#-MS7FReS5S69NzfhTS80:-MS7FReS5S69NzfhTS81:b4s585q) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/748a20c705abdbd275ef0f7423649f21153a07f4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java#L61)):*
> ```Java
>     public Task updateTask(@PathVariable @ApiParam("The id of the task to update") String taskId, @RequestBody Task task) {
>         ObjectNode response = kapacitor().patchForObject("/kapacitor/v1/tasks/{taskId}", task.toKapacitorRequest(), ObjectNode.class, taskId);
>         ObjectNode responseReload = kapacitor().patchForObject("/kapacitor/v1/templates/{templateID}", task.toKapacitorRequestTemplateUpdate(), ObjectNode.class, task
> ```

You don't have to store this in a variable because you don't need it.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java, line 61 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982#-MS7FXzH3ENlYIl5n631:-MS7FXzH3ENlYIl5n632:bvsmrf2) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/748a20c705abdbd275ef0f7423649f21153a07f4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java#L61)):*
> ```Java
>     public Task updateTask(@PathVariable @ApiParam("The id of the task to update") String taskId, @RequestBody Task task) {
>         ObjectNode response = kapacitor().patchForObject("/kapacitor/v1/tasks/{taskId}", task.toKapacitorRequest(), ObjectNode.class, taskId);
>         ObjectNode responseReload = kapacitor().patchForObject("/kapacitor/v1/templates/{templateID}", task.toKapacitorRequestTemplateUpdate(), ObjectNode.class, task
> ```

Can you move this in a separate method? Imo it is more clearly what's happening and also why:

```
private void triggerTaskReload(Task task) {
    String taskTemplateId = task.getTemplate();
    kapacitor().patchForObject("/kapacitor/v1/templates/{templateID}", task.toKapacitorRequestTemplateUpdate(), ObjectNode.class, taskTemplateId);
}
```

then you just need to call `triggerTaskReload(task);` when a task should be reloaded
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Task.java, line 114 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982#-MS7ITu40k_rKx0PyoDE:-MS7ITu40k_rKx0PyoDF:b-4l5vrx) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/748a20c705abdbd275ef0f7423649f21153a07f4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Task.java#L114)):*
> ```Java
>      * @return a JSON-Object which can be used for updating the template in PATCH request to kapacitor
>      */
>     public ObjectNode toKapacitorRequestTemplateUpdate() {
> ```

Do we need tests for this?
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Task.java, line 115 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982#-MS7FwhLBM_hRtYtxKRI:-MS7FwhLBM_hRtYtxKRJ:buv8014) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/748a20c705abdbd275ef0f7423649f21153a07f4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Task.java#L115)):*
> ```Java
>      */
>     public ObjectNode toKapacitorRequestTemplateUpdate() {
>         ObjectMapper mapper = new ObjectMapper();
> ```

You don't need to create a new object mapper every time. It's recommended to just create one and reuse it.

You can convert it to a final and static field and initialize it once:

```
private static final ObjectMapper mapper = new ObjectMapper();
```

Then in your method - same in the `toKapacitorRequest` - you can just use it.

**Review by Patrick-Eichhorn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @mariusoe)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java, line 61 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982#-MS7FReS5S69NzfhTS80:-MS7QhOqEpSIr-5Bm1mH:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/748a20c705abdbd275ef0f7423649f21153a07f4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java#L61)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

You don't have to store this in a variable because you don't need it.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java, line 61 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982#-MS7FXzH3ENlYIl5n631:-MS7RjMWBnxJX9mEdFs7:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/748a20c705abdbd275ef0f7423649f21153a07f4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java#L61)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Can you move this in a separate method? Imo it is more clearly what's happening and also why:

```
private void triggerTaskReload(Task task) {
    String taskTemplateId = task.getTemplate();
    kapacitor().patchForObject("/kapacitor/v1/templates/{templateID}", task.toKapacitorRequestTemplateUpdate(), ObjectNode.class, taskTemplateId);
}
```

then you just need to call `triggerTaskReload(task);` when a task should be reloaded
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Task.java, line 114 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982#-MS7ITu40k_rKx0PyoDE:-MS7TOjHDsEDU2o_SkxN:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/748a20c705abdbd275ef0f7423649f21153a07f4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Task.java#L114)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Do we need tests for this?
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Task.java, line 115 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982#-MS7FwhLBM_hRtYtxKRI:-MS7SAC25PlTwF_yYaSg:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/748a20c705abdbd275ef0f7423649f21153a07f4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Task.java#L115)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

You don't need to create a new object mapper every time. It's recommended to just create one and reuse it.

You can convert it to a final and static field and initialize it once:

```
private static final ObjectMapper mapper = new ObjectMapper();
```

Then in your method - same in the `toKapacitorRequest` - you can just use it.
</blockquote></details>

Done.

**Review by mariusoe — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982)* status: all files reviewed, 2 unresolved discussions (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java, line 73 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982#-MSCDyRJEzYXVnBBtbgj:-MSCDyRJEzYXVnBBtbgk:bk2jmda) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6c0c23515447440d5bdcfa2cd3ca8c7d8f4464e0/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java#L73)):*
> ```Java
>     }
> 
>     private void triggerTaskReload(Task task) {
> ```

Please add a small comment, also why we do an update of the template for this.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Task.java, line 63 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982#-MSCEBY8CGjdGpARbl_o:-MSCEBY8CGjdGpARbl_p:b-tedz5t) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6c0c23515447440d5bdcfa2cd3ca8c7d8f4464e0/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Task.java#L63)):*
> ```Java
>     List<TemplateVariable> vars;
> 
>     private static final ObjectMapper mapper = new ObjectMapper();
> ```

Please move static variables to the top of the class - before member fields.

**Review by Patrick-Eichhorn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @mariusoe)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java, line 73 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982#-MSCDyRJEzYXVnBBtbgj:-MSRdxRBDZitpVm5flm6:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6c0c23515447440d5bdcfa2cd3ca8c7d8f4464e0/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java#L73)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Please add a small comment, also why we do an update of the template for this.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Task.java, line 63 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982#-MSCEBY8CGjdGpARbl_o:-MSRdyyP85k-CyOgjLCK:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6c0c23515447440d5bdcfa2cd3ca8c7d8f4464e0/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Task.java#L63)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Please move static variables to the top of the class - before member fields.
</blockquote></details>

Done.

**Review by mariusoe — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982)* status: all files reviewed, 1 unresolved discussion (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java, line 73 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982#-MSCDyRJEzYXVnBBtbgj:-MSRnkCP1AR6hiJWpspp:b-tzar3m) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/6c0c23515447440d5bdcfa2cd3ca8c7d8f4464e0/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java#L73)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I thought more like why we are patching the template for this. Maybe we can write a small comment that a task cannot be reloaded and just doing patch request against the template api - without changing it - triggers kapacitor to reload the previously changed task.

**Review by Patrick-Eichhorn — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982#-:-MSWUGTkBcZNjyiU3xOy:bnfp4nl)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @mariusoe)

**Review by mariusoe — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mariusoe — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patrick-Eichhorn)

**Pull request merged**
