### PR TITLE
Closes #1028 - Remove rt.bmr.sum from the rt.bmr beacon processor and change the rt.bmr.index logic to qualified names 

### LINKED ISSUE #1028: Remove rt.bmr.sum from the rt.bmr beacon processor and change the rt.bmr.index logic to qualified names
The sum of the single rt.bmr values leads to an incorrect result. All values refer to the first startTime value: during summing up, times are counted multiple times from the start value.

Currently, the single values can be accessed via the index logic (f.e. rt.bmr.0 stands for startTime). To make the access more applicable and explicit, a name mapping needs to be implemented for the value expression settings. (f.e rt.bmr.startTime)

### PR DESCRIPTION
**Pull request by Patrick-Eichhorn**
Closes #1028

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029)

### CODE REVIEW

**Comment by SaschaBrechmannVHV** [comment]
With this logic, how could i get the full load-time of boomerang? 
As i understand the boomerang doku, one needs to sum all elements of rt.bmr to get the full load-time?

**Comment by mariusoe** [comment]
Hi @SaschaBrechmannVHV 

what do you exactly mean by "full load-time"? Do you need the time the Boomerangjs resource (`bommerang.js`) has needed to load or the same thing but including the time that was needed for initializing it?

Suming up all these values does not make sense because these values are relative timestamps representing the resource timings for the "`boomerang.js`" file. For example, the first element in the list of the "`bmr`" attribute is the timestamp (relative to the initial page loading time) when the "`boomerang.js`" file was requested by the browser. **All following values are given relative to the first one (the starting time).** The second value specifies the time (**relative to the start time**: the first value) when the request has ended (`responseEnd`).

So, if you interested in getting the duration for loading the "`boomerang.js`" file, the "`responseEnd`" value would be the correct one.

The following image represents these values quite good. Once this PR is merged, you have also access to them by its name.
image

For example, if "`responseStart`" contains the value 100 and "`reponseEnd`" contains the value 150, this means that the browser had to wait 100ms until it received the first byte from the server. Since the values are relative to the starting point, the transfer of the file took 50ms (`responseEnd - responseStart`). Here you can now also see why a summation of these values makes no sense, since one would now calculate 100ms + 150ms with these two example values.

I hope this helps you.

**Review by mariusoe — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029)* status: all files reviewed, 7 unresolved discussions (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 17 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029#-MV1gnfFBdkwum-wGhkf:-MV1gnfFBdkwum-wGhkg:bar26si) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1bd3ed4df1d7bd101f4099dc7d7d80a58fc81bb9/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L17)):*
> ```Java
>  * indexed key in the beacon.
>  * <p>
>  * Example: The attribute <code>rt.bmr=37,5</code> will result in <code>rt.bmr.0: 37</code>, <code>rt.bmr.1: 5</code>
> ```

Can you adapt these docs.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 21 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029#-MV1grdl0H9-FieQ5cCM:-MV1grdl0H9-FieQ5cCN:btcicnp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1bd3ed4df1d7bd101f4099dc7d7d80a58fc81bb9/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L21)):*
> ```
> CsvExpander
> ```
Due to the fact that this processor is very much fitted to the `bmr` attribute now, maybe we should name it 'BmrBeaconProcessor'
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 50 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029#-MV1iu0dDuKDwK-ULOh4:-MV1iu0dDuKDwK-ULOh5:btfpo7c) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1bd3ed4df1d7bd101f4099dc7d7d80a58fc81bb9/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L50)):*
> ```Java
>                 String resultKey = ATTRIBUTE_KEY + "." + VALUE_NAMES[i];
> 
>                 String value = (i < attributes.length && !StringUtils.isBlank(attributes[i])) ? attributes[i] : "0";
> ```

Can you rewrite this in easier code? This is quite complex to understand,therefore errors can easily slip in.

Maybe something like this:
```
String value;
if (i > attributes.length || StringUtils.isBlank(attributes[i])) {
    value = "0";
} else {
    value  = attributes[i];
}
```
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 53 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029#-MV1jx9qBytM7AgoFBLu:-MV1jx9qBytM7AgoFBLv:b-s15l0n) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1bd3ed4df1d7bd101f4099dc7d7d80a58fc81bb9/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L53)):*
> ```Java
> 
>                 if (NumberUtils.isCreatable(value)) {
>                     beacon = beacon.merge(Collections.singletonMap(resultKey, value));
> ```

Since we now create a beacon attribute for each timing value, we always have multiple iterations here. To avoid that we merge the beacon unnecessarily often (and creating a lot of garbage objects), we could put all attributes into a local map first, which is then merged only once at the end with the original beacon.

```
HashMap<String, String> bmrAttributes = new HashMap<>();

for (int i = 0; i < VALUE_NAMES.length; i++) {
    ...
        bmrAttributes.put(resultKey, value);
    ...
}

beacon = beacon.merge(bmrAttributes);
```
___
*[components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java, line 25 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029#-MV1lTG-1MjEvO6gDygY:-MV1lTG-1MjEvO6gDygZ:b-8irjxq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1bd3ed4df1d7bd101f4099dc7d7d80a58fc81bb9/components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java#L25)):*
> ```Java
> 
>         private final String[] keyNames = Arrays.stream(CsvExpanderBeaconProcessor.VALUE_NAMES)
>                 .sequential()
> ```

You don't need this. The stream should be sequential by default.
___
*[components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java, line 26 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029#-MV1lkn4CY6jsbtl4VeP:-MV1lkn4CY6jsbtl4VeQ:b-abo2my) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1bd3ed4df1d7bd101f4099dc7d7d80a58fc81bb9/components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java#L26)):*
> ```
> s
> ```
How about `name` or `key`? :)
___
*[components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java, line 30 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029#-MV1ljx88s4Q2zus_em8:-MV1ljx88s4Q2zus_em9:b-et5v30) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1bd3ed4df1d7bd101f4099dc7d7d80a58fc81bb9/components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java#L30)):*
> ```
> Integer
> ```
int

**Review by Patrick-Eichhorn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @mariusoe)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 17 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029#-MV1gnfFBdkwum-wGhkf:-MVRCjGD14Y4AWlVbldB:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1bd3ed4df1d7bd101f4099dc7d7d80a58fc81bb9/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L17)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Can you adapt these docs.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 21 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029#-MV1grdl0H9-FieQ5cCM:-MVRDMZnDmvCfjQhJVdK:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1bd3ed4df1d7bd101f4099dc7d7d80a58fc81bb9/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L21)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> CsvExpander
> ```
Due to the fact that this processor is very much fitted to the `bmr` attribute now, maybe we should name it 'BmrBeaconProcessor'
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 50 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029#-MV1iu0dDuKDwK-ULOh4:-MVRDo5UE91-R_GgqjVf:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1bd3ed4df1d7bd101f4099dc7d7d80a58fc81bb9/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L50)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Can you rewrite this in easier code? This is quite complex to understand,therefore errors can easily slip in.

Maybe something like this:
```
String value;
if (i > attributes.length || StringUtils.isBlank(attributes[i])) {
    value = "0";
} else {
    value  = attributes[i];
}
```
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java, line 53 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029#-MV1jx9qBytM7AgoFBLu:-MVREaOD81lKHWGkooZU:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1bd3ed4df1d7bd101f4099dc7d7d80a58fc81bb9/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java#L53)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Since we now create a beacon attribute for each timing value, we always have multiple iterations here. To avoid that we merge the beacon unnecessarily often (and creating a lot of garbage objects), we could put all attributes into a local map first, which is then merged only once at the end with the original beacon.

```
HashMap<String, String> bmrAttributes = new HashMap<>();

for (int i = 0; i < VALUE_NAMES.length; i++) {
    ...
        bmrAttributes.put(resultKey, value);
    ...
}

beacon = beacon.merge(bmrAttributes);
```
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java, line 25 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029#-MV1lTG-1MjEvO6gDygY:-MVRGF2f8unf2gt-6eHj:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1bd3ed4df1d7bd101f4099dc7d7d80a58fc81bb9/components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java#L25)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

You don't need this. The stream should be sequential by default.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java, line 26 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029#-MV1lkn4CY6jsbtl4VeP:-MVRGFm277U2qQ8VLEfS:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1bd3ed4df1d7bd101f4099dc7d7d80a58fc81bb9/components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java#L26)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> s
> ```
How about `name` or `key`? :)
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java, line 30 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029#-MV1ljx88s4Q2zus_em8:-MVRGKcIA7uOTXlKKmre:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1bd3ed4df1d7bd101f4099dc7d7d80a58fc81bb9/components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java#L30)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> Integer
> ```
int
</blockquote></details>

Done.

**Review by mariusoe — APPROVED** [review]
> Reviewed 17 of 17 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patrick-Eichhorn)

**Review by mariusoe — APPROVED** [review]
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1029)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patrick-Eichhorn)

**Pull request merged**
