### PR TITLE
Closes #377 - Prevent recursive method hook execution

### LINKED ISSUE #377: Prevent instrumentation recursion
With the current implementation of MethodHook, a poorly chosen instrumentation can lead to an infinite recursion.
For example, instrumenting methods of `ArrayList` are such a case. The instrumentation will trigger the method hook, which uses the `ArrayList` class by itself and triggers the instrumentation again and again.
This can be solved by disabling the isntrumentation for the current Thread when entering a method hook based on a ThreadLocal variable.

### PR DESCRIPTION
**Pull request by mariusoe**
closes #377

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1262)

### CODE REVIEW

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1262)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @heiko-holz and @mariusoe)

___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManagerTest.java, line 80 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1262#-MuGRZ-m6jLYreOEAyJf:-MuGRZ-m6jLYreOEAyJg:bbnxllb) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/7eb46b3dee3dfec419705ff55d82735203cab953/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManagerTest.java#L80)):*
> ```Java
> 
>             // set recursion gate
>             HookManager.RECURSION_GATE.set(true);
> ```

Is it feasible to also write a "real scenario" test case for which the RECURSION_GATE is not set manually but by the "poorly chosen instrumentation"?
As I am too far away from the implementation, I fail to grasp the example given in https://github.com/inspectIT/inspectit-ocelot/issues/377

**Review by heiko-holz — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1262)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @heiko-holz and @mariusoe)

**Review by mariusoe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1262)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @heiko-holz)

___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManagerTest.java, line 80 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1262#-MuGRZ-m6jLYreOEAyJf:-Mw28-b79BAE8ilSWO8f:bh79gvq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/7eb46b3dee3dfec419705ff55d82735203cab953/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManagerTest.java#L80)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Is it feasible to also write a "real scenario" test case for which the RECURSION_GATE is not set manually but by the "poorly chosen instrumentation"?
As I am too far away from the implementation, I fail to grasp the example given in https://github.com/inspectIT/inspectit-ocelot/issues/377 
</blockquote></details>

I've added a system test as well including an instrumentation configuration to cover this case (where an instrumentation calls an instrumented method within its instrumentation). Maybe it is more clear now.

**Review by heiko-holz — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1262)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mariusoe)

___
*[inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManagerTest.java, line 80 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1262#-MuGRZ-m6jLYreOEAyJf:-Mw6cgo_B5_MpSXqZdUa:b-hi76s6) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/7eb46b3dee3dfec419705ff55d82735203cab953/inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManagerTest.java#L80)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

I've added a system test as well including an instrumentation configuration to cover this case (where an instrumentation calls an instrumented method within its instrumentation). Maybe it is more clear now.
</blockquote></details>

Yes, the tests phenomenally explain the issue :)

**Pull request merged**
