### PR TITLE
Closes #1209 - Live branch is synchronized with remote target branch to allow for pushing without force

### LINKED ISSUE #1209: Live branch is synchronized with remote target branch to allow for pushing without force
### Use Case

I want to use the Git config staging as a backup for a _development_ config server. It should use the same repository and branch for pulling and pushing. I then want to merge the state of this branch into another one using a pull request. This second branch serves as source for further config server stages, e.g., _prod_.
The config servers are deployed in Kubernetes, i.e., may frequently restart and/or be removed and re-created.

### Problem

The development config server fetches changes from the source branch into _workspace_, then merges these changes into _live_, which is then pushed to the source branch. This can destroy a clean commit history, disallowing for rebase.

### Suggested Solution

When fetching from the source branch, always rebase _live_ on the source branch and then merge the changes into _workspace_. This will retain the commit history and add changes only on top.

### Side Note

The remote repo will still contain commits from workspace, like _"Commit configuration file and agent mapping changes"_. These are required, as the config server needs to know which _workspace_ changes have been merged into which commit on the _live_ branch.

### PR DESCRIPTION
**Pull request by Henning-Schulz**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1210)

### CODE REVIEW

**Comment by Henning-Schulz** [comment]
As the intended behavior changed, tests are failing now. I am going to adapt them.

**Review by mariusoe — CHANGES_REQUESTED** [review]
As discussed, this process will prevent the usage of pushing to a remote repository without "force" in case multiple repositories are used in combination with local changes.

**Comment by Henning-Schulz** [comment]
Current state is unstable/not ready yet. I have to implement the new behavior, as discussed.

**Comment by mariusoe** [comment]
I've converted it into a darf PR

**Review by mariusoe — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1210)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @Henning-Schulz and @mariusoe)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java, line 137 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1210#-MmrQn2f8SomeyqIzw6i:-MmrQn2g29Tf10o8BWAv:b1izox5) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e2091d9414379031b74e767b0d22abd049c354a4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java#L137)):*
> ```Java
>             log.info("Working directory is not managed by Git. Initializing Git repository and staging and committing all existing file.");
> 
>             if (hasRemote && remoteSettings.getPushRepository() != null) {
> ```

Maybe we should add some inline documention that it is clear why we are doing this.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java, line 190 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1210#-MmrQY0s1nCAUvE9LHW5:-MmrQY0s1nCAUvE9LHW6:bhdvs2o) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e2091d9414379031b74e767b0d22abd049c354a4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java#L190)):*
> ```Java
>     }
> 
>     private void setCurrentBranchToTarget() throws GitAPIException, IOException {
> ```

Can you document this method. Imo this is quite an important one.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java, line 199 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1210#-MnVpzzT2cUuMav-jNkA:-MnVpzzT2cUuMav-jNkB:b-necjrn) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e2091d9414379031b74e767b0d22abd049c354a4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java#L199)):*
> ```Java
>         // fetch pull and push repo, as we will need both to compare and synchronize local/pull/push repos
>         // push repo is expected to exist
>         remoteConfigurationManager.fetchSourceBranch(targetRepository);
> ```

This will fail in case the push branch does not exist. Imo it could be a vaild use-case that the push branch is created by the configuration server itself.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java, line 209 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1210#-MnVx4AE2NQLz7qdeA-E:-MnVx4AE2NQLz7qdeA-F:b4l716x) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e2091d9414379031b74e767b0d22abd049c354a4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java#L209)):*
> ```Java
>         boolean hardReset = isWorkdirEmpty() && remoteSettings.isInitialConfigurationSync() && remoteSettings.isAutoPromotion() && areRemotesEqual(sourceRepository, targetRepository);
> 
>         log.info("{}-resetting current branch to '{}'.", (hardReset ? "Hard" : "Soft"), targetRepository.getBranchName());
> ```

I think we are missing that we remove all files from the push target here in case we do a soft reset. Didn't we?
Let's discuss this once more, please.

**Review by Henning-Schulz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1210)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @mariusoe)

___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java, line 137 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1210#-MmrQn2f8SomeyqIzw6i:-MnWPIeB9oSwRj4N1zXk:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e2091d9414379031b74e767b0d22abd049c354a4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java#L137)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Maybe we should add some inline documention that it is clear why we are doing this.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java, line 190 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1210#-MmrQY0s1nCAUvE9LHW5:-MnWPE8C1aRRec7-ewtq:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e2091d9414379031b74e767b0d22abd049c354a4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java#L190)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Can you document this method. Imo this is quite an important one.
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java, line 199 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1210#-MnVpzzT2cUuMav-jNkA:-MnWU0VGAC4P08dfcT8g:b7380jg) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e2091d9414379031b74e767b0d22abd049c354a4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java#L199)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

This will fail in case the push branch does not exist. Imo it could be a vaild use-case that the push branch is created by the configuration server itself.
</blockquote></details>

Should be fixed with the next commit. Please double-check in your setting.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java, line 209 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1210#-MnVx4AE2NQLz7qdeA-E:-MnWP0pu-M1CLpHvUBg2:bezh4yy) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/e2091d9414379031b74e767b0d22abd049c354a4/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java#L209)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

I think we are missing that we remove all files from the push target here in case we do a soft reset. Didn't we?
Let's discuss this once more, please.
</blockquote></details>

As discussed, the implemented behavior is intended

**Comment by Henning-Schulz** [comment]
I have tested the startup with a missing push branch. It works and creates a git history as follows:
image

Imo this is the expected behavior and similar to before my changes

**Review by mariusoe — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1210)* status: all files reviewed, 4 unresolved discussions (waiting on @mariusoe)

**Review by mariusoe — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1210)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Henning-Schulz)

**Pull request merged**
