### PR TITLE
Closes #1187: Extend the configuration UI to be able to hide files

### LINKED ISSUE #1187: Extend the configuration UI to be able to hide files
Currently, all existing configuration files are displayed in the configuration UI's file tree. In case many files and directory exists, this tree can become quite messy. It would be great to have an option to hide certain files.

In this ticket, the configuration UI should be extended, so that specific files can be hidden from the file tree. Here, it should be implemented in such a way that files whose names begin with a dot are hidden. This should be able to be switched on and off dynamically (e.g. using the context menu). Hidden files should also be hilighted in some way when they are displayed.

### PR DESCRIPTION
**Pull request by Marcel-Haag**
closes #1187

This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493)

### CODE REVIEW

**Review by MariusBrill — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493)* status: all files reviewed, 1 unresolved discussion (waiting on @Marcel-Haag and @mariusoe)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js` line 269 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493#-N6rP8LmDhdLwVb4Me_q:-N6rP8LmDhdLwVb4Me_r:b5o9wjz) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1d9834164285e839800bf3f69d2c132f2a950b77/components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js#L269)):*
> ```JavaScript
>       hideFilesRecursively(files, hidePattern);
>     } else {
>       dispatch(fetchFiles());
> ```

Why do we need to fetch the files when showHiddenFiles is false?

**Review by heiko-holz — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493)* status: all files reviewed, 1 unresolved discussion (waiting on @Marcel-Haag and @mariusoe)

**Review by heiko-holz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493#-:-N6rbX4-526lJduzI-nk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Marcel-Haag and @mariusoe)

**Review by heiko-holz — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493)* status: all files reviewed, 1 unresolved discussion (waiting on @MariusBrill and @mariusoe)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js` line 269 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493#-N6rP8LmDhdLwVb4Me_q:-N6rUmm8ATgFBXDX2QR1:b-62cslu) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/1d9834164285e839800bf3f69d2c132f2a950b77/components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js#L269)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Why do we need to fetch the files when showHiddenFiles is false?
</blockquote></details>

because we toggle from `showHiddenFiles` to `!showHiddenFiles`.

But I see your point. Doing the toggle before and then negating the expression makes more sense.

I've pushed an update.

**Review by aaronweissler — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @heiko-holz, @Marcel-Haag, @MariusBrill, and @mariusoe)

*[a discussion](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493#-N7pqiclDYVnG-exb6lb:-N7pqiclDYVnG-exb6lc:bd6dn40) (no related file):*
When I create a new file or folder while hidden files are not shown, they all appear again. I assume it is because in the `writeFile` action the `fetchFiles` action is dispatched as well.
Maybe the hiding could be incorporated into the `fetchFiles` action directly?

I also wonder if the default should be that the hidden files are not shown, so they are only shown when explicitly asked for?

___

**Comment by heiko-holz** [comment]
*[a discussion](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493#-N7pqiclDYVnG-exb6lb:-N7tnMxr7DFgdvf8Wo4n:b-kfsfk3) (no related file):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

When I create a new file or folder while hidden files are not shown, they all appear again. I assume it is because in the `writeFile` action the `fetchFiles` action is dispatched as well.
Maybe the hiding could be incorporated into the `fetchFiles` action directly?

I also wonder if the default should be that the hidden files are not shown, so they are only shown when explicitly asked for?
</blockquote></details>

Good point, thank you for the comment!

I have refactored `toggleShowHiddenFiles` and incorporated it in `fetchFiles`.

Let's discuss the default state in the next meeting.

**Comment by heiko-holz** [comment]
*[a discussion](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493#-N7pqiclDYVnG-exb6lb:-N8Ncvi9CovwxEKYSudU:bfsfcc4) (no related file):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Good point, thank you for the comment!

I have refactored `toggleShowHiddenFiles` and incorporated it in `fetchFiles`.

Let's discuss the default state in the next meeting.
</blockquote></details>

The default state was now changed to `false`, i.e., hidden files are **not** shown per default

**Review by heiko-holz — DISMISSED** [review]
> Reviewed 3 of 4 files at r5, 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493)* status: all files reviewed, 1 unresolved discussion (waiting on @aaronweissler and @mariusoe)

**Review by aaronweissler — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493#-:-N8NUnx1E0eXwgbKp_hh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mariusoe)

**Review by heiko-holz — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mariusoe)

**Review by heiko-holz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mariusoe)

**Review by MariusBrill — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1493#-:-N8O5b6N1lAorNBBnxtS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mariusoe)

**Pull request merged**
