### PR TITLE
closes #521 - Ability to import one or multiple configuration files via the configuration server's web interface 

### LINKED ISSUE #521: Ability to import one or multiple configuration files via the configuration server's web interface
Currently, when a user wants to import one or multiple configuration files via the configuration server's web interface the following process has to be done:

- create a new file
- copy / paste the content into that file
- save the file

This process makes it quite tedious to import multiple files.

In this ticket, a feature should be implemented where the user can import one or multiple files at once without the need of creating and saving all files manually.

This could be implemented, for example, by allowing a user to import one or more files or folders via drag and drop or via a button in the configuration UI, which are then automatically created. In case whole folders are imported, their folder structure should be kept.

### PR DESCRIPTION
**Pull request by JazzMina88**
closes #521

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491)

### CODE REVIEW

**Comment by JazzMina88** [comment]
Screenshot 2022-06-28 at 15-39-28 inspectIT Ocelot Configuration Server Configuration

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @JazzMina88 and @MariusBrill)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js` line 127 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l9ZNg4JRB8wsW1Yo5:-N6l9ZNh2Xa_00hhx8k6:b-a6qhdj) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js#L127)):*
> ```JavaScript
>   showUploadDialog = () => this.setState({ isUploadDialogShown: true });
> 
>   hideUploadDialog = () => this.setState({ isUploadDialogShown: false });
> ```

do we need to reset the state of the upload dialog?

Currently, when I re-open the upload dialog, the previously selected files are still selected
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 14 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l9Dq26lTVL56zK8sf:-N6l9Dq26lTVL56zK8sg:b-qcowe0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L14)):*
> ```JavaScript
>   constructor() {
>     super();
>     this.handleClick = this.handleClick.bind(this);
> ```

do we need to bind this method? (especially when this method is renamed?)
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 51 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l9PH74-72GXbbNQFN:-N6l9PH74-72GXbbNQFO:bj3f8nu) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L51)):*
> ```JavaScript
>         }
>       >
>         <Dropzone onDrop={this.onDrop}>
> ```

maybe style the cursor as pointer in the DropZone? (as it is clickable to select files)
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 66 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l9AwBC7B9pkASDV_9:-N6l9AwBC7B9pkASDV_A:b-j82zuh) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L66)):*
> ```JavaScript
>   }
> 
>   handleClick = () => {
> ```

maybe rename this method to `uploadFiles`
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 71 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l8pbU0UXcw89oub95:-N6l8pbU0UXcw89oub96:bnm6qqr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L71)):*
> ```JavaScript
>       this.state.files.forEach((file) => {
>         const fileName = this.props.selection + '/' + file.name;
>         if (file.type === 'application/x-yaml') {
> ```

when I try to upload `file.yml` (`yml` extension) in Firefox, I receive the error `Wrong file type`
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 93 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6hm1YC215WCtHr2tbU:-N6hm1YC215WCtHr2tbV:bfkvpyj) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L93)):*
> ```JavaScript
>       });
>     } else {
>       showErrorMessage('You have to select a directory');
> ```

do we want that uploaded directories are uploaded into a new directory with their name?

E.g., we currently have selected the directory `some-online-config-directory` and want to upload the following directory

```
some-local-config-files-directory
   - file1.yml
   - file2.yml
```

Do we want to upload it as a directory (a new directory `some-local-config-files-directory`) or pull the individual files and upload them into our selected directory (`some-online-config-directory`?
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 93 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l8yLlBTCDqw2HU_mz:-N6l8yLlBTCDqw2HU_n-:bse7lbp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L93)):*
> ```JavaScript
>       });
>     } else {
>       showErrorMessage('You have to select a directory');
> ```

Additionally, I would expect to receive this error message already when I click on the upload button (not when I try to upload selected files)

**Review by MariusBrill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @heiko-holz)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js` line 127 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l9ZNg4JRB8wsW1Yo5:-N6qpqj38z9au36rKRhi:b-886gsx) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js#L127)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

do we need to reset the state of the upload dialog?

Currently, when I re-open the upload dialog, the previously selected files are still selected
</blockquote></details>

Fixed
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 14 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l9Dq26lTVL56zK8sf:-N6qrCMZ0rJnuPr3k2yx:b-kk3ut2) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L14)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

do we need to bind this method? (especially when this method is renamed?)
</blockquote></details>

solved
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 51 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l9PH74-72GXbbNQFN:-N6qrE-Q2OSjfgmCf5RH:b-kk3ut2) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L51)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

maybe style the cursor as pointer in the DropZone? (as it is clickable to select files)
</blockquote></details>

solved
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 66 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l9AwBC7B9pkASDV_9:-N6qrR_-054Y2umFzTsO:bzbkaju) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L66)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

maybe rename this method to `uploadFiles`
</blockquote></details>

Solved
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 71 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l8pbU0UXcw89oub95:-N6qrTTs4PpuXSDpXiCO:b-j6ybum) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L71)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

when I try to upload `file.yml` (`yml` extension) in Firefox, I receive the error `Wrong file type`
</blockquote></details>

I could not replicate this issue on my machine. Let's have a short talk about it.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 93 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6hm1YC215WCtHr2tbU:-N6qrb569-Y4R3mYCqR0:bp0jbk7) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L93)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

do we want that uploaded directories are uploaded into a new directory with their name?

E.g., we currently have selected the directory `some-online-config-directory` and want to upload the following directory

```
some-local-config-files-directory
   - file1.yml
   - file2.yml
```

Do we want to upload it as a directory (a new directory `some-local-config-files-directory`) or pull the individual files and upload them into our selected directory (`some-online-config-directory`?

</blockquote></details>

We discussed this comment and decided to make this a new issue.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 93 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l8yLlBTCDqw2HU_mz:-N6qrm2HEg6P70lbYfxv:b4w8sdo) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L93)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Additionally, I would expect to receive this error message already when I click on the upload button (not when I try to upload selected files)
</blockquote></details>

Changed the behaviour to upload the files into the selected directory.

**Comment by heiko-holz** [comment]
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 71 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l8pbU0UXcw89oub95:-N6vULF0AqebgpziAITa:b-tgzxr6) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L71)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

I could not replicate this issue on my machine. Let's have a short talk about it.
</blockquote></details>

Yes, let's chat about this.

On my machine (Windows 10), the file types are not recognized (the property `file.type` is unset). 
I tried Firefox, Brave, and Chrome as browsers.

**Review by heiko-holz — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @heiko-holz, @JazzMina88, and @MariusBrill)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 24 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6vYbafC1EUnmEmnK9X:-N6vYbafC1EUnmEmnK9Y:bklsa3v) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/df95fa0d06a2d72966ec3cb9e49825fcf0f82b19/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L24)):*
> ```JavaScript
>   constructor() {
>     super();
>     this.onDrop = (files) => {
> ```

Currently, only the most recent dropped files will be uploaded.
This makes it impossible to upload files from different folders.

I've uploaded a fix.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 96 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6vVTAZE-zTO6As6qko:-N6vVTAZE-zTO6As6qkp:b-mt3ywm) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/df95fa0d06a2d72966ec3cb9e49825fcf0f82b19/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L96)):*
> ```JavaScript
>         <div>{filesToUpload}</div>
> 
>         <Dropzone onDrop={this.onDrop} accept={['.yml', '.yaml']}>
> ```

does the  `accept={['.yml', '.yaml']}` property have any effect?
I can still put `.txt` and other files into the upload dialog.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 144 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6vVtjQ5ixVYsTLtQ2V:-N6vVtjQ5ixVYsTLtQ2W:biegwd1) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/df95fa0d06a2d72966ec3cb9e49825fcf0f82b19/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L144)):*
> ```JavaScript
>         };
>       } else {
>         showErrorMessage('Wrong file type');
> ```

Should we enhance this error message, e.g., by adding the information about the file and which file types are accepted?

E.g.,
`The file 'file-name.txt' has an invalid file type. Only yaml files are accepted.`

**Review by danipaniii — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491)* status: all files reviewed, 4 unresolved discussions (waiting on @JazzMina88 and @MariusBrill)

**Review by danipaniii — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491)* status: all files reviewed, 4 unresolved discussions (waiting on @heiko-holz)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 71 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l8pbU0UXcw89oub95:-NEtRF9c9CsFiN3XshRL:bb372zu) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L71)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Yes, let's chat about this.

On my machine (Windows 10), the file types are not recognized (the property `file.type` is unset). 
I tried Firefox, Brave, and Chrome as browsers.
</blockquote></details>

I experienced the same issue on Windows 10. But I observed that the file type of .txt files could be recognized, but not from the yaml files.
But since I fixed the dropzone, so that it can only accept yaml files, the check for the correct file type becomes kinda useless. Nevertheless I added a new function that gets the extension of the file and with this we can check the current file for the correct format.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 24 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6vYbafC1EUnmEmnK9X:-NEtPPli-uB2zuBqF8QI:b97n27h) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/df95fa0d06a2d72966ec3cb9e49825fcf0f82b19/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L24)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Currently, only the most recent dropped files will be uploaded.
This makes it impossible to upload files from different folders.

I've uploaded a fix.

</blockquote></details>

Alright, I also tested uploading files from different folders and it worked without problems 
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 96 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6vVTAZE-zTO6As6qko:-NEtPfJiCToPqQbwGbGs:b-i1gdan) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/df95fa0d06a2d72966ec3cb9e49825fcf0f82b19/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L96)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

does the  `accept={['.yml', '.yaml']}` property have any effect?
I can still put `.txt` and other files into the upload dialog.
</blockquote></details>

Here the syntax was wrong, I fixed it to the right one, so now the dropzone only accepts yaml files and other file types cannot be dropped anymore.



_Code snippet:_
```JavaScript
accept = {{ 'text/yml': [".yml", ".yaml"] }}
```
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 144 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6vVtjQ5ixVYsTLtQ2V:-NEtQTySE_98DWMtMd31:b-iozhhy) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/df95fa0d06a2d72966ec3cb9e49825fcf0f82b19/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L144)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Should we enhance this error message, e.g., by adding the information about the file and which file types are accepted?

E.g.,
`The file 'file-name.txt' has an invalid file type. Only yaml files are accepted.`
</blockquote></details>

Since now in the dropzone any non yaml file cannot be dropped into, I adjusted the text in the dropzone and added the message: "Only yaml files are being accepted!"

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491)* status: all files reviewed, 2 unresolved discussions (waiting on @JazzMina88)

___
*[`components/inspectit-ocelot-configurationserver-ui/.yarn/install-state.gz` line 0 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-NFHy2RiAC-_qA1-4hlu:-NFHy2RiAC-_qA1-4hlv:bfmeb9g) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/a461602d0fff48bfd1dd9c1bb48a6deba7aee856/components/inspectit-ocelot-configurationserver-ui/.yarn/install-state.gz#L0)):*
I think the `install-state.gz` file should not be commited to git, see https://yarnpkg.com/getting-started/qa
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 71 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6l8pbU0UXcw89oub95:-NFHyszQBfNvP9SfDmDe:b-wdj8zi) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2bba2a30c6097d500ccd69d42d0ba074c0fc2192/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L71)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

I experienced the same issue on Windows 10. But I observed that the file type of .txt files could be recognized, but not from the yaml files.
But since I fixed the dropzone, so that it can only accept yaml files, the check for the correct file type becomes kinda useless. Nevertheless I added a new function that gets the extension of the file and with this we can check the current file for the correct format.
</blockquote></details>

Nice, thanks!
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 96 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6vVTAZE-zTO6As6qko:-NFHyVlw5dj4fiHPVfdj:b-vefquz) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/df95fa0d06a2d72966ec3cb9e49825fcf0f82b19/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L96)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

Here the syntax was wrong, I fixed it to the right one, so now the dropzone only accepts yaml files and other file types cannot be dropped anymore.
</blockquote></details>

thanks!
It works as expected :)
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 144 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-N6vVtjQ5ixVYsTLtQ2V:-NEe98Di4VIPiv2tsW98:b-xnndms) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/df95fa0d06a2d72966ec3cb9e49825fcf0f82b19/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L144)):*
<details><summary><i>Previously, danipaniii wrote…</i></summary><blockquote>

Since now in the dropzone any non yaml file cannot be dropped into, I adjusted the text in the dropzone and added the message: "Only yaml files are being accepted!"
</blockquote></details>

Perfect, thanks!
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js` line 151 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491#-NFHz1PKD3GRxny3HsXq:-NFHz1PKD3GRxny3HsXr:b-4bfpkh) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/a461602d0fff48bfd1dd9c1bb48a6deba7aee856/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/UploadDialog.js#L151)):*
> ```JavaScript
>       let extension = this.getExtension(fileName);
> 
>       if (this.validateFileType(extension)) {
> ```

If I understand @danipaniii correctly in the above comment, this validation is not needed anymore as the dropzone has been correctly configured.
If yes, I would remove unnecessary validations and methods (`getExtension`) if they are not needed at all.

**Comment by danipaniii** [comment]
I noticed, I removed too much when, removing the unnecessary methods and validations. I will fix it this friday.

**Review by heiko-holz — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JazzMina88)

**Review by MariusBrill — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JazzMina88)

**Review by MariusBrill — APPROVED** [review]
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1491)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JazzMina88)

**Pull request merged**
