### PR TITLE
Closes #1290 - Add an endpoint to the Configuration Server to obtain a configuration documentation

### LINKED ISSUE #1290: Add an endpoint to the Configuration Server to obtain a configuration documentation
The goal is to implement an endpoint which can be used to retreive a configuration documentation for a specific agent mapping, generated by the component of #1289.

The endpoint should return the configuration documentation for the configuration related to the given agent mapping. The endpoint URL should be: `/api/v1/configuration/documentation`. The related agent mapping should be passed as a request parameter named `agent-mapping`.

### PR DESCRIPTION
**Pull request by aaronweissler**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1314)

### CODE REVIEW

**Review by heiko-holz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1314)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @aaronweissler and @MariusBrill)

___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/configuration/ConfigurationControllerTest.java, line 90 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1314#-Mwa7YtcEdU5RlL6AZuj:-MwaVFeu5D1CoB7CuyN6:b-d9dfrf) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/223aec5928ef59b3730d220c331f6808f9d98e57/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/configuration/ConfigurationControllerTest.java#L90)):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

I could not mock these two easily, because they are final classes due to their `Value` Annotation and mockito only supports mocking final classes when using mockito-inline instead (https://javadoc.io/doc/org.mockito/mockito-core/2.23.0/org/mockito/Mockito.html#Mocking_Final) and I did not want to add that for something rather small like this, but of course I could if you think it would be worth it :)
</blockquote></details>

We agreed to **not** use `mockito-inline` as as it does not work with IBM JDK8.

**Review by aaronweissler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1314)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @MariusBrill)

___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/configuration/ConfigurationControllerTest.java, line 90 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1314#-Mwa7YtcEdU5RlL6AZuj:-MwaXbkmEvCYvfjAObVs:bapzgn6) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/223aec5928ef59b3730d220c331f6808f9d98e57/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/configuration/ConfigurationControllerTest.java#L90)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

We agreed to **not** use `mockito-inline` as as it does not work with IBM JDK8.
</blockquote></details>

Okay, thank you! Then that question is settled.

**Review by aaronweissler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1314)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @MariusBrill)

___
*[components/inspectit-ocelot-configdocsgenerator/build.gradle, line 33 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1314#-MwfcEad2qZLoNhuVxBP:-MwfwFwkCxfjVSp70gfx:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/223aec5928ef59b3730d220c331f6808f9d98e57/components/inspectit-ocelot-configdocsgenerator/build.gradle#L33)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Just a reminder to update THIRD-PARTY-LICENCES.txt :) 
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfigurationManager.java, line 97 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1314#-MwffElO5kKKwIbVfLrJ:-MwfwGZW0U5RdGLnd4RW:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/223aec5928ef59b3730d220c331f6808f9d98e57/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfigurationManager.java#L97)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

This sentence is not quite right - Maybe something like "Takes an instance of AgentMapping and returns the befitting instance of AgentConfiguration" ? 
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfigurationManager.java, line 101 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1314#-Mwffa1s9C5TScHqvFEJ:-MwfwH5p1IalfftZpQa0:b-ls2vgt) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/223aec5928ef59b3730d220c331f6808f9d98e57/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfigurationManager.java#L101)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Here you could also add that the first matching instance of AgentConfiguration is returned in case there are more than one matching instances.
</blockquote></details>

Done.
As talked about, there can only be one configuration per Mapping.
___
*[components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/configuration/ConfigurationControllerTest.java, line 81 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1314#-MwfebZNBtwNt3bUNAEQ:-MwfwHqiBP2rVAtG71op:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/223aec5928ef59b3730d220c331f6808f9d98e57/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/configuration/ConfigurationControllerTest.java#L81)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

Maybe we could here add a third test case for the Situation that a JsonProcessingException is thrown?

You can provoke an exception in configDocsGenerator.generateConfigDocs with a when-thenThrow method in Mockito
</blockquote></details>

Done.

**Review by MariusBrill — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1314)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @aaronweissler)

**Review by MariusBrill — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1314)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aaronweissler)

**Pull request merged**
