### PR TITLE
Closes #914: [Feature] Expand configuration file tree when jumping to a file

### LINKED ISSUE #914: Expand the configuration file tree when jumping to a file
The web-UI provides the possibility to jump to a specific configuration file (e.g. by using the search dialog). When jumping to a configuration file, the file is opened but only selected in the configuration file tree in case the related directory is already shown.

It would improve the user experience when the file tree is expanded when a user jumps to a file, thus, users can immediately see where a file is located.

### PR DESCRIPTION
**Pull request by Marcel-Haag**
Closes #914 

This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485)

### CODE REVIEW

**Review by aaronweissler — CHANGES_REQUESTED** [review]
Since you moved on to a new project, I implemented some changes myself. I tried to explain the reasonings in my other comments, but please let me know if you have additional questions where I forgot to explain a change or was too unclear :)

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485#-:-N7G80av3vFbX12UE5vt:bjmz1g3)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @Marcel-Haag and @mariusoe)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js` line 43 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485#-N7G7jTVBzup_yV3grNZ:-N7G7jTVBzup_yV3grN_:bgv7dg4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/69e968504d3bfe2a726ede51d4e5fb51d4bd6a86/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js#L43)):*
> ```JavaScript
>    */
>   componentDidUpdate(prevProps) {
>     if (prevProps.targetFile !== '' && prevProps.targetFile !== this.searchedFileTest) {
> ```

Instead of using this placeholder variable `searchedFileTest`, you can simply use `prevProps.targetFile !== this.props.targetFile` to check if the prop changed.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js` line 56 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485#-N7G5zKZ54wzgl8hNPbG:-N7G5zK_0e1qwgh1RHTE:buzlxnp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/69e968504d3bfe2a726ede51d4e5fb51d4bd6a86/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js#L56)):*
> ```JavaScript
>    */
>   shouldComponentUpdate(nextProps, state) {
>     if (nextProps.defaultTree.concat(nextProps.files) && state.nodes !== nextProps.defaultTree.concat(nextProps.files)) {
> ```

The if statement always evaluates to true, since it's not the Array's contents that are compared but rather the Array objects.

However, comparing the Array contents is not necessary anyways, since `nodes` does not always change when an update is needed. It only changes when new files are created or files are deleted, but the component also needs to update on simple selection changes.

This means we do not need the `nodes` prop nor the `shouldComponentUpdate` function anymore in general.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js` line 77 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485#-N7G7OMdCOBBxXEyR-J3:-N7G7OMdCOBBxXEyR-J4:b-4ja04n) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/69e968504d3bfe2a726ede51d4e5fb51d4bd6a86/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js#L77)):*
> ```JavaScript
>    * @param split helps extracting the node key for recursive calls
>    */
>   expandLabelThroughDOMElements(targetNodeKey, iterations, split) {
> ```

Your solution works and it actually is kind of impressive, however you do not need to look through and modify DOM Elements directly to expand the nodes. The `Tree` component from PrimeReact offers a prop `expandedKeys` for this purpose which makes things a lot more simple and clean.

I did not look into this further, since I had found the `expandedKeys` prop already, but I also wondered if using a simple loop would actually be better than a recursive function here.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js` line 79 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485#-N7G9feOClWnkXcGC1iN:-N7G9feOClWnkXcGC1iO:b-75vxl8) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/69e968504d3bfe2a726ede51d4e5fb51d4bd6a86/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js#L79)):*
> ```JavaScript
>     // Create the child instance using react createRef
>     this.childRef = React.createRef();
>   }
> ```

Unless I missed something this constructor is not needed and `childRef` never used.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js` line 165 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485#-N7G8pip9kiY4wPKNEj4:-N7G8pip9kiY4wPKNEj5:b-mj3iw4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/69e968504d3bfe2a726ede51d4e5fb51d4bd6a86/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js#L165)):*
> ```JavaScript
>     }
>     this.props.selectFile(filename);
>     this.searchedFile = filename;
> ```

Using this variable that is only updated when using the search dialog to open a new file, leads to a bug where, if you open the same file twice using the search dialog and no other file with the search dialog in-between, the nodes will not get expanded again if closed in-between, since the `searchedFile` has not changed.

Instead we can use the `selection` prop in FileTree that already exists and is always changed, no matter if using the search dialog or simply clicking on a file. If the file was selected by simply clicking nothing will happen, since the nodes needed will already be expanded anyways.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js` line 171 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485#-N7GA1-53eQ8h51MuFmO:-N7GA1-53eQ8h51MuFmP:b-kh409s) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/69e968504d3bfe2a726ede51d4e5fb51d4bd6a86/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js#L171)):*
> ```JavaScript
>     if (!this.props.loading && this.props.isLatestVersion) {
>       this.props.selectedFileContentsChanged(value);
>     }
> ```

Unless I'm missing something, this `onChange` is a duplicate of the already existing one.

**Review by aaronweissler — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485)* status: all files reviewed, 6 unresolved discussions (waiting on @Marcel-Haag)

**Review by aaronweissler — DISMISSED** [review]

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485)* status: all files reviewed, 7 unresolved discussions (waiting on @Marcel-Haag)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js` line 40 at r4](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485#-N7p1YEW5W9s8fUVE6JL:-N7p1YEW5W9s8fUVE6JM:b-kdqmhp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/ff8745a23c38faa70f0fcaa7fb58502fa8bb6cf2/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js#L40)):*
> ```JavaScript
>     if (this.props.selection !== prevProps.selection) {
>       // if true, expand needed nodes in FileTree, in case the file was opened using search
>       const splittedTargetFilePath = this.props.selection.split('/');
> ```

this code causes a nullpointer exception when switching from a "regular" configuration file to a "default" configuration file (`Ocelot Defaults`) .

**Comment by heiko-holz** [comment]
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js` line 38 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485#-N7pANQHCcT1j_owu-EL:-N7pANQHCcT1j_owu-EM:bqt5h74) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/717c1b0edb2c9aec1894bd4d6d34be24b18d0894/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js#L38)):*
> ```JavaScript
>   componentDidUpdate(prevProps) {
>     // check if a new file has been selected
>     if (this.props.selectedFilePath !== prevProps.selectedFilePath) {
> ```

does this not only trigger when I select a new `path` and not a different `file` in the same path?

**Review by heiko-holz — COMMENTED** [review]
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @heiko-holz and @Marcel-Haag)

**Review by aaronweissler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @heiko-holz)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js` line 38 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485#-N7pANQHCcT1j_owu-EL:-N7pS2twEfC0b-FGMu4u:b-9qjvm6) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/717c1b0edb2c9aec1894bd4d6d34be24b18d0894/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js#L38)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

does this not only trigger when I select a new `path` and not a different `file` in the same path?
</blockquote></details>

Yeah, you're right. It would probably be expected behaviour for most cases, since usually if I search for a file in the same folder as the last file I had selected, the folder will still be open, but it could also be unexpected if I already closed that folder again for unrelated reasons.
I refactored it to use the full path and also parse the path within FileTree itself again.

**Review by heiko-holz — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marcel-Haag)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js` line 48 at r8](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485#-N7pmeu79SH6rrtEiuuW:-N7pmeu8DBM8jNo94AMx:b-l9pp5o) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/f41cf17d6313927c7929aea87c1577d8aa02aa9b/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js#L48)):*
> ```JavaScript
>       if (selection) {
>         filePath = selection;
>       } else if (selectedDefaultConfigFile) {
> ```

do we need the `else if`. As we are already checking that either `selection` or `selectedDefaultConfigFile` are not null, an `else` should be sufficient

**Review by heiko-holz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485#-:-N83We9UAIzaHk_q9j9o:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marcel-Haag)

**Pull request merged**
