### PR TITLE
Closes #1267 - Upgrade Spring Boot to the latest version

### LINKED ISSUE #1267: Upgrade Spring Boot to the latest version
Currently, the inspectIT Ocelot agent uses Spring Boot in version 2.1.1 which is quite old. To take advantage of the latest bug fixes and seucirty optimizations, Spring Boot should be upgraded to the latest version.

### PR DESCRIPTION
**Pull request by mariusoe**
#1267

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1271)

### CODE REVIEW

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 21 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1271)* status: 21 of 23 files reviewed, 1 unresolved discussion (waiting on @heiko-holz and @mariusoe)

___
*[gradlew, line 167 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1271#-MtHAMe205NTMLAFE3sx:-MtHAMe205NTMLAFE3sy:bpac1a) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/7c7d43d8661b0cac0dcbfe2b9886a72065e1d2d5/gradlew#L167)):*
> ```Shell
> eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"
> 
> # by default we should be in the correct project dir, but when run from Finder on Mac, the cwd is wrong
> ```

Why has this code been removed? Does it work from Finder on Mac without changing the directory?

**Review by heiko-holz — COMMENTED** [review]
> Reviewed 1 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1271)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @heiko-holz and @mariusoe)

**Review by mariusoe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1271)* status: 22 of 24 files reviewed, 1 unresolved discussion (waiting on @heiko-holz)

___
*[gradlew, line 167 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1271#-MtHAMe205NTMLAFE3sx:-MtMrUYe2GdwfzLy6IdX:b-3z60ya) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/7c7d43d8661b0cac0dcbfe2b9886a72065e1d2d5/gradlew#L167)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Why has this code been removed? Does it work from Finder on Mac without changing the directory?
</blockquote></details>

This change was due to the upgrade of Gradle and its a part of it. So, it was no change by me but by the Gradle team, thus, I would assume it works (at least I got no problems on Mac)

**Review by heiko-holz — APPROVED** [review]
> Reviewed 1 of 23 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mariusoe)

**Pull request merged**
