### PR TITLE
Add settings and info for developing UI in IntelliJ

### PR DESCRIPTION
**Pull request by aaronweissler**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1496)

### CODE REVIEW

**Review by PDuwe — APPROVED** [review]
Some tests seem to be failing.

Also, you could still get rid of the warnings. Looks good apart from the tests however, so you decide :)

**Comment by aaronweissler** [comment]
> Some tests seem to be failing.

Those agent tests have been failing seemingly randomly for a small while now. We still will investigate that further, but it's definitely not related to this PR, since there are no changes to Java code or directly related things in here at all (which also was my motivation for adding additional ignore paths for the workflow in #1497 that you also reviewed ^^)

> Also, you could still get rid of the warnings. Looks good apart from the tests however, so you decide :)

If you mean the warnings seen in `Files Changed`, they are also not related to this PR's changes, I'm not sure why GitHub is showing them for those two files.

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1496)* status: all files reviewed, 2 unresolved discussions (waiting on @aaronweissler and @PDuwe)

___
*[`CONTRIBUTING.md` line 17 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1496#-N6lMqWk8LLf-zClLAPG:-N6lMqWl0pF8ENVEN0_m:bklg61v) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8d9e9c5919ac47436504d3d370ffa3ab00c62843/CONTRIBUTING.md#L17)):*
> ```Markdown
> 
> ### Frontend Developing
> If developing JavaScript in IntelliJ, check that Settings.Languages & Frameworks.JavaScript.Code Quality Tools.ESLint is activated for correct linting.
> ```

this feature is only available in IntelliJ Ultimate, right?

If so, please add `Ultimate`
___
*[`components/inspectit-ocelot-configurationserver-ui/.eslintrc` line 45 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1496#-N6lIFYgCr2q07uGMAVt:-N6lIFYgCr2q07uGMAVu:b-c5g2xi) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/203c7216e5a879c404cbede37730f872788db7bf/components/inspectit-ocelot-configurationserver-ui/.eslintrc#L45)):*
> ```
>         "import/no-useless-path-segments": "error",
>         "react/prop-types": "warn",
>         "prettier/prettier": ["error", { "endOfLine": "auto" }]
> ```

this fixes the `delete 'CR' [prettier/prettier]` error message, right? (https://stackoverflow.com/questions/53516594/why-do-i-keep-getting-delete-cr-prettier-prettier)
___
*[`components/inspectit-ocelot-configurationserver-ui/README.md` line 33 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1496#-N6lMPOwAbp3wHjxdzC1:-N6lMPOwAbp3wHjxdzC2:b4pkhxl) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8d9e9c5919ac47436504d3d370ffa3ab00c62843/components/inspectit-ocelot-configurationserver-ui/README.md#L33)):*
> ```Markdown
> And the following to fix them automatically.
> ```bash
> yarn format:write
> ```

what does `yarn format:write` do as compared to `yarn lint --fix`?

Is it recommended to run `eslint --fix` on save?

**Comment by heiko-holz** [comment]
*[`components/inspectit-ocelot-configurationserver-ui/README.md` line 33 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1496#-N6lMPOwAbp3wHjxdzC1:-N6lSsfqCFTMX0HpkIFd:by0qsik) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8d9e9c5919ac47436504d3d370ffa3ab00c62843/components/inspectit-ocelot-configurationserver-ui/README.md#L33)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

what does `yarn format:write` do as compared to `yarn lint --fix`?

Is it recommended to run `eslint --fix` on save?
</blockquote></details>

(addendum: with current version of IntelliJ, we can use Tools.Actions on Save and check `Run eslint --fix`:

**Review by heiko-holz — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1496)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @heiko-holz and @PDuwe)

___
*[`components/inspectit-ocelot-configurationserver-ui/README.md` line 33 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1496#-N6lMPOwAbp3wHjxdzC1:-N70yIw1594ZWHP2IlSa:b-wsvasg) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/8d9e9c5919ac47436504d3d370ffa3ab00c62843/components/inspectit-ocelot-configurationserver-ui/README.md#L33)):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

`yarn format:write` runs `prettier --write` fixing issues, while `yarn lint --fix` or `yarn lint:fix` run `eslint --fix`. So in this case it should be the `lint` command instead. If I understand correctly, the `lint` command also considers errors considered by `prettier` anyways.
I also like just using the auto apply, so you get your errors fixed while developing without having to think of running it yourself, and don't have to fix all of them at once in the end if you forget.
</blockquote></details>

Thanks for the explanation!

**Review by heiko-holz — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1496)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PDuwe)

**Pull request merged**
