### PR TITLE
bug #1479:  Configuration UI overlaps Combined-Services-Badge and Show-Logs-Icon

### LINKED ISSUE #1479: Configuration UI overlaps Combined-Services-Badge and Show-Logs-Icon
For agents with a very long name, the icons on the right side of the column will overlap with the badge showing the number of combined services. Presumably this would also overlap the name itself if it's long enough.

### PR DESCRIPTION
**Pull request by sbraitsch**
Closes #1479 
Added a max width to the name template. Name + ID combinations that are too long will get ellipsized to prevent overlap.
I also moved the service-count badge statically next to the show log and show config icons to make the position consistent.
Added the name + id as a tooltip, so it can be seen fully even when it gets ellipsized.

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1489)

### CODE REVIEW

**Comment by heiko-holz** [comment]
Will be discussed in the week of 29.08-02.09.2022 when I'm in FFM

**Review by danipaniii — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1489)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @heiko-holz and @MariusBrill)

**Comment by danipaniii** [comment]
In order to always show the full name of the service name and not having to hover over it, there is the possibility to change the styling like this: `.this :global(.might-overflow) {
            max-width: 19rem; 
            display: inline-block;
            white-space: normal;
            overflow: visible;
            overflow-wrap: break-word;
            text-overflow: unset;
          }`

**Comment by danipaniii** [comment]
The original solution:
original

The alternative:
alternative

**Comment by heiko-holz** [comment]
We discussed in the team and decided for the version with the line-break.
@danipaniii can you please implement and commit that version :)?

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1489)* status: all files reviewed, 1 unresolved discussion (waiting on @MariusBrill and @sbraitsch)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 188 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1489#-NGG8XLu5FANNCmtNiil:-NGG8XLu5FANNCmtNiim:boswyr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/32aeeddb3389a19329020ec9f73c86488a112f5e/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L188)):*
> ```JavaScript
>           }
> 
>           .this :global(.might-overflow):hover {
> ```

do we even need the agent name on hover? 
I.e., can we remove the `title` for the agent name?
Let's discuss this in today's sync

**Review by heiko-holz — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1489)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MariusBrill)

___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 188 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1489#-NGG8XLu5FANNCmtNiil:-NGVIe6u2g8xQwTX6wKt:b-woihsj) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/32aeeddb3389a19329020ec9f73c86488a112f5e/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L188)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

do we even need the agent name on hover? 
I.e., can we remove the `title` for the agent name?
Let's discuss this in today's sync
</blockquote></details>

As discussed, I removed the `hover` attribute and related CSS class

**Review by heiko-holz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1489#-:-NGVkQof3-Cx1ZGLLp9w:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MariusBrill)

**Pull request merged**
