### PR TITLE
Closes #525 - Allow scopes to exclude certain methods / classes

### LINKED ISSUE #525: Allow scopes to exclude certain methods / classes
Scopes allow to select specific methods from classes ast the moment.
E.g. it is easily possible to define scope for all classes implementing a certain interface.

It is however very difficult to exclude certain methods / classes at the moment. For example if you want to instrument all classes implementing an interface except for one class.

To solve this, we should add an `exclude` option to scopes:
```
inspectit:
  instrumentation:
    scopes:
       scope_a:
         ...
       scope_b:
         exclude:
           scope_a: true
         ...
```
In this example scope_b would *not* instrument the methods matched by scope_a.

It is important that the configuration validation ensures that there are no cycles in the exclude-definitions.

### PR DESCRIPTION
**Pull request by Patrick-Eichhorn**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943)

### CODE REVIEW

**Review by JonasKunz — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943)* status: all files reviewed, 9 unresolved discussions (waiting on @Patrick-Eichhorn)

___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettings.java, line 48 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943#-MKoPQp428_dmhLUs9Rl:-MKoPQp428_dmhLUs9Rm:b-3aoh9n) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b40ff461dca5b03123f17154345fe5fa0f6f34b/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettings.java#L48)):*
> ```Java
> 
>     /**
>      * Scopes which are to be excluded
> ```

Be a bit more specific in your description: The keys of the map are the names of scopes, whose methods will be excluded from being matches by this scope.
___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettings.java, line 84 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943#-MKoPdc19LIWHT_reie_:-MKoPdc19LIWHT_reiea:b-zcmfy0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b40ff461dca5b03123f17154345fe5fa0f6f34b/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettings.java#L84)):*
> ```Java
>      * Validates this scope, invoked by {@link InstrumentationSettings#performValidation(InspectitConfig, ViolationBuilder)}
>      *
>      * @param container      the root config containing this rule
> ```

"The root config containing this rule" --> copy paste error
___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettings.java, line 109 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943#-MKoQWEm-7M3nwqNV-cL:-MKoQWEm-7M3nwqNV-cM:b-c9ndvg) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b40ff461dca5b03123f17154345fe5fa0f6f34b/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettings.java#L109)):*
> ```Java
>      * @param parentScope the scope, which holds the exclude-scopes
>      * @param scopes map of scopes
>      * @param verified a list containing already verified scopes
> ```

Clarify a little in your comment: Verified means that this scope is guaranteed to not be part of a cyclic dependency.
___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettings.java, line 110 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943#-MKoQ4Y3-yvazpbRwp7z:-MKoQ4Y3-yvazpbRwp8-:b-gmdbp9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b40ff461dca5b03123f17154345fe5fa0f6f34b/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettings.java#L110)):*
> ```Java
>      * @param scopes map of scopes
>      * @param verified a list containing already verified scopes
>      * @param visitedParents temp list for verified parentScopes
> ```

State the invariant here:
`visitedParents` represents the current path in the depth-first search. The last element in the list must be `parentScope`.
___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettings.java, line 113 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943#-MKoQJuuDJEvvWYZ2fea:-MKoQJuuDJEvvWYZ2feb:bbdcgdx) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b40ff461dca5b03123f17154345fe5fa0f6f34b/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettings.java#L113)):*
> ```Java
>      * @param vios the violation output
>      */
>     private static void verifyCyclicalDependence(String parentScope, Map<String, InstrumentationScopeSettings> scopes, Set<String> verified, List<String> visitedParents, ViolationBuilder vios) {
> ```

You dont't verify that there is a a cyclical dependency, you verify that there is none.
Therefore name this `verifyNoCyclicDependency`.
___
*[inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettings.java, line 123 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943#-MKoR27tEnk6CCeYKFBF:-MKoR27tEnk6CCeYKFBG:b-13ah9l) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b40ff461dca5b03123f17154345fe5fa0f6f34b/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettings.java#L123)):*
> ```Java
>                 .forEach(excludeScope -> {
>                     if (visitedParents.contains(excludeScope)) {
>                         vios.message("Specified excluded Scope in '{scope}' has cyclical dependence with other Scope -> '{excludeScope}'") // verifiedParens ausgeben
> ```

Still an open TODO here!
___
*[inspectit-ocelot-config/src/test/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettingsTest.java, line 31 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943#-MKo_azyC5ry6Lrd-V-L:-MKo_azyC5ry6Lrd-V-M:b-dm5cse) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b40ff461dca5b03123f17154345fe5fa0f6f34b/inspectit-ocelot-config/src/test/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettingsTest.java#L31)):*
> ```Java
> 
>     @Spy
>     ViolationBuilder vios;
> ```

Why do you sue `@Spy` here? Also you don't evene use this, do you?
___
*[inspectit-ocelot-config/src/test/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettingsTest.java, line 148 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943#-MKoa25GCo4fLfdtfnua:-MKoa25GCo4fLfdtfnub:b-rat6ci) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b40ff461dca5b03123f17154345fe5fa0f6f34b/inspectit-ocelot-config/src/test/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettingsTest.java#L148)):*
> ```Java
>             assertThat(violations.get(0).getParameters())
>                     .containsValue("scope-a")
>                     .containsValue("scope-c");
> ```

Don't forget to also check for `scope-b` as soon as you have done the TODO from above
___
*[inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationScopeResolver.java, line 61 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943#-MKoawyV4KllXd7GISNQ:-MKoawyV4KllXd7GISNR:b-kgwy65) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/2b40ff461dca5b03123f17154345fe5fa0f6f34b/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationScopeResolver.java#L61)):*
> ```Java
>      * @return The resolve {@link InstrumentationScope}.
>      */
>     private void resolveScope(String name, Map<String, InstrumentationScopeSettings> settings, Map<String, InstrumentationScope> cache) {
> ```

Update the javadoc to include the parameters.

**Review by Henning-Schulz — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Henning-Schulz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Henning-Schulz — APPROVED** [review]
> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Henning-Schulz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943#-:-MLmOZY89b8BaZw-vOlT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
