### PR TITLE
feat #1333:  Enable downloading support archives from the configurati…

### LINKED ISSUE #1333: Enable downloading support archives from the configuration UI
As a supporter, when receiving a support request, I would like to get a support archive from the user who reached out to me. This will speed up the support significantly, as I don't need to ask for details. The archive should contain at least the version, configuration, logs, and JVM parameters of the affected agent.

---

To get a support archive, there should be a possibility to select the agent for which a support archive should be created. A new button could be added to the "Agent Status" overview, which can be used to request a support archive.

If a support archive is created directly by the configuration server and not by the configuration UI, it has the advantage that they can also be created programmatically (e.g. via curl). In this case, the configuration server must be extended by a corresponding endpoint.

### PR DESCRIPTION
**Pull request by sbraitsch**
Closes #1333 
Added new endpoint that internally combines results of multiple commands and returns them in a single object.
That object gets parsed in the frontend and is automatically downloaded as a zip-archive containing 3 separate files (config, logs, environment details).

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487)

### CODE REVIEW

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487)* status: all files reviewed, 5 unresolved discussions (waiting on @MariusBrill and @Napfschnecke)

___
*[`components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCommandManager.java` line 90 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-N6OFhi544G-f4AZsdDA:-N6OFhi67PzWIaQxPJTc:b-ktwyjr) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/229881060b565d31252720b212fba474ade07aa1/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCommandManager.java#L90)):*
> ```Java
>             }
> 
>             if (command == null) {
> ```

Is this behavior intended?

Is the `commandQueue` always empty after a command has been polled?

In case there are multiple commands in the `commandQueue`, the cache for the agent would be invalidated after the first command has been polled.
___
*[`components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentService.java` line 18 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-N6g5_B80mwFDr_AAUG3:-N6g5_B80mwFDr_AAUG4:byehlbo) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/229881060b565d31252720b212fba474ade07aa1/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentService.java#L18)):*
> ```Java
> import java.util.concurrent.ExecutionException;
> import java.util.concurrent.atomic.AtomicInteger;
> ```

A short description of the class would be nice :)
___
*[`components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentService.java` line 85 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-N6g67fsE4MLf2apDk2i:-N6g67fsE4MLf2apDk2j:b-z47i3) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/229881060b565d31252720b212fba474ade07aa1/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentService.java#L85)):*
> ```Java
>                         break;
>                     case LOG:
>                         ResponseEntity<String> logResponse = (ResponseEntity<String>) result;
> ```

it would be nice to have an "error message" in the log file in case that the log preloading is disabled instead of receiving an empty log file.
E.g., "Logs cannot be retrieved because log preloading (`inspectit.log-preloading`) is not enabled. To retrieved agent logs, please enable the log preloading."
___
*[`components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/agent/AgentServiceTest.java` line 29 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-N6g92cb7ItiOWlDXNda:-N6g92cb7ItiOWlDXNdb:bvaaxl5) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/229881060b565d31252720b212fba474ade07aa1/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/agent/AgentServiceTest.java#L29)):*
> ```Java
> import static org.mockito.Mockito.doReturn;
> import static org.mockito.Mockito.when;
> ```

Please add a short description
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 272 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-N6gArAu9vnmj4MX2lNM:-N6gArAu9vnmj4MX2lNN:byrumyd) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d30f3c3fcbf1e032fd1d4a0ba6c7bc982eec3018/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L272)):*
> ```JavaScript
>             <i className={classNames('pi pi-fw', iconClass)} style={{ color: iconColor }}></i>
>             <span>{healthInfo}</span>
>             <Button
> ```

It would be great if the button is only enabled when the agent commands are enabled. Otherwise it should show on hover that the agent commands need to be enabled in order to download the support archive.

Alternately, a short popup telling the user that the agent commands need to be enabled would also work.

This can be turned into a new ticket in order to close this PR
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js` line 313 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-N6gBebp6fJTRRCQWRcO:-N6gBebp6fJTRRCQWRcP:ba5ils0) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d30f3c3fcbf1e032fd1d4a0ba6c7bc982eec3018/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js#L313)):*
> ```JavaScript
>   downloadSupportArchive = (agentId, agentVersion) => {
>     getStore().dispatch(
>       notificationActions.showInfoMessage('Preparing Archive', 'Download will start automatically once the archive is ready.')
> ```

It would be nice if the messaging/informing is aligned to that of retrieving the agent logs and configuration (using the `DownloadDialogue`with a progress bar instead of toasts).

Especially when downloading the archive fails due to timeout (which most likely happens because the agent commands are not enabled), the toast can be easily missed.

This can also be turned into a new ticket to speed up closing this PR

**Comment by heiko-holz** [comment]
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js` line 272 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-N6gArAu9vnmj4MX2lNM:-N6gi8cg1uIQWL9ns2Km:bxyuarw) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d30f3c3fcbf1e032fd1d4a0ba6c7bc982eec3018/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js#L272)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

It would be great if the button is only enabled when the agent commands are enabled. Otherwise it should show on hover that the agent commands need to be enabled in order to download the support archive.

Alternately, a short popup telling the user that the agent commands need to be enabled would also work.

This can be turned into a new ticket in order to close this PR
</blockquote></details>

I created an issue for this: https://github.com/inspectIT/inspectit-ocelot/issues/1495

**Comment by heiko-holz** [comment]
*[`components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCommandManager.java` line 90 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-N6OFhi544G-f4AZsdDA:-N6vNaXe0nPJvwCeIOLC:bumxddw) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/229881060b565d31252720b212fba474ade07aa1/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/AgentCommandManager.java#L90)):*
<details><summary><i>Previously, Napfschnecke (sbr) wrote…</i></summary><blockquote>

Previously we checked if the Queue was empty and invalidated then.
This caused a race condition, where the check for the empty queue passed, but the queue got populated with the following command before the invalidation ran.
So it dropped the second command.
Checking for null should (and has consistently during testing) assert, that we only invalidate the command cache after all commands have been processed. Side effect is that the invalidation only occurs on the scheduled command fetch every 15sec and not immediately after processing the second command.
I am very open to any suggestion that makes this safer and more understandable :) 
</blockquote></details>

Sounds reasonable :)
I was just missing this context!

**Review by Napfschnecke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487)* status: 3 of 14 files reviewed, 2 unresolved discussions (waiting on @heiko-holz and @MariusBrill)

___
*[`components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentService.java` line 18 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-N6g5_B80mwFDr_AAUG3:-N88NbsX0I5gROmX4akI:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/229881060b565d31252720b212fba474ade07aa1/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentService.java#L18)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

A short description of the class would be nice :)
</blockquote></details>

Done.
___
*[`components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/agent/AgentServiceTest.java` line 29 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-N6g92cb7ItiOWlDXNda:-N88Np96AZ1nyq6fvR-Q:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/229881060b565d31252720b212fba474ade07aa1/components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/agent/AgentServiceTest.java#L29)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Please add a short description
</blockquote></details>

Done.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js` line 313 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-N6gBebp6fJTRRCQWRcO:-N88O4ox5VCVhm8OX_68:b-896fjx) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d30f3c3fcbf1e032fd1d4a0ba6c7bc982eec3018/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js#L313)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

It would be nice if the messaging/informing is aligned to that of retrieving the agent logs and configuration (using the `DownloadDialogue`with a progress bar instead of toasts).

Especially when downloading the archive fails due to timeout (which most likely happens because the agent commands are not enabled), the toast can be easily missed.

This can also be turned into a new ticket to speed up closing this PR
</blockquote></details>

Done

**Review by heiko-holz — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r4, 3 of 7 files at r5, 4 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487)* status: all files reviewed, 1 unresolved discussion (waiting on @MariusBrill and @Napfschnecke)

___
*[`components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentService.java` line 93 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-N8NHVuq2FHiPPNQWXb3:-N8NHVuq2FHiPPNQWXb4:bm1b9e4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/58417051a89b17a261becb0f01930031d3367baf/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentService.java#L93)):*
> ```Java
>                     case LOG:
>                         ResponseEntity<String> logResponse = (ResponseEntity<String>) result;
>                         archiveData.logs = archiveData.currentConfig.contains("log-preloading: {enabled: true}") ? logResponse.getBody() : "Logs cannot be retrieved because log preloading (inspectit.log-preloading) is not enabled. To retrieve agent logs, please enable the log preloading.";
> ```

Two minor questions:

- would it make more sense to have this behavior/conditional before the command is executed, so that we do not wait for the timeout exception? 
e.g., either in the `logs` method or in the `buildSupportArchive` method.
- can we directly query the `InspectitConfig.logPreloading.enabled` instead of checking for the embedded yaml string? In case the property's name changes, we would need to adjust it here.
___
*[`components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js` line 313 at r2](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-N6gBebp6fJTRRCQWRcO:-N8NJZQXEuFm1R7nQAVN:b-wdj8zi) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/d30f3c3fcbf1e032fd1d4a0ba6c7bc982eec3018/components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js#L313)):*
<details><summary><i>Previously, Napfschnecke (sbr) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Nice, thanks!

**Review by heiko-holz — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-:-NBpjnx69-C8YSgWCsEr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MariusBrill)

___
*[`components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentService.java` line 93 at r6](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1487#-N8NHVuq2FHiPPNQWXb3:-NBpkikO-_ZjVvq2kmpg:b103ma4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/58417051a89b17a261becb0f01930031d3367baf/components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentService.java#L93)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Two minor questions:

- would it make more sense to have this behavior/conditional before the command is executed, so that we do not wait for the timeout exception? 
e.g., either in the `logs` method or in the `buildSupportArchive` method.
- can we directly query the `InspectitConfig.logPreloading.enabled` instead of checking for the embedded yaml string? In case the property's name changes, we would need to adjust it here.

</blockquote></details>

We found a nice solution for this :)

**Pull request merged**
