### PR TITLE
Closes #1121 - ﻿﻿Add selfmonitoring metric for the beacon processors

### LINKED ISSUE #1121: Add selfmonitoring metric for the beacon processors
Add selfmonitoring metric for the beacon procerssor to EUM Server.

### PR DESCRIPTION
**Pull request by Mahir-Isikli**
closes #1121

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1122)

### CODE REVIEW

**Review by mariusoe — CHANGES_REQUESTED** [review]
Your base commit is quite old. Please rebase the PR on the latest commit or merge the master branchinto your PR branch.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1122#-:-MePaR7Y5IFZCm_fdOk1:bzapqzd)* status: all files reviewed, 3 unresolved discussions (waiting on @Mahir-Isikli and @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CompositeBeaconProcessor.java, line 30 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1122#-MeP_rBXBGgBQ-nkR1Dd:-MeP_rBY-8PnODUnx6ce:bk6xfbv) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/769881aaa133b3bcddea619a3daa5c685ff5cafb/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CompositeBeaconProcessor.java#L30)):*
> ```
> is_error
> ```
Java variables are named using camel-casing, so, just use `isError` instead of `is_error`
___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 268 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1122#-MeP_m1L8bjTlOFeJCxI:-MeP_m1L8bjTlOFeJCxJ:b-ky8xnp) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/769881aaa133b3bcddea619a3daa5c685ff5cafb/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L268)):*
> ```YAML
>             aggregation: SUM
>             tags:
>               beacon_processor: true
> ```

The `is_error` tag is missing here
___
*[components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CompositeBeaconProcessorTest.java, line 24 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1122#-MeP_Ia43GYKQfCzTgir:-MeP_Ia43GYKQfCzTgis:b-kiomb8) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/769881aaa133b3bcddea619a3daa5c685ff5cafb/components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CompositeBeaconProcessorTest.java#L24)):*
> ```Java
> 
>     @Mock
>     private SelfMonitoringMetricManager selfMonitoring;
> ```

This mock is not used. Please revert this file when no change is done.

**Comment by Patrick-Eichhorn** [comment]
@Mahir-Isikli can you still add this self-monitoring metric to the [documentation](https://inspectit.github.io/inspectit-ocelot/docs/enduser-monitoring/eum-server-configuration#self-monitoring)?

**Review by Mahir-Isikli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1122)* status: all files reviewed, 3 unresolved discussions (waiting on @mariusoe and @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CompositeBeaconProcessor.java, line 30 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1122#-MeP_rBXBGgBQ-nkR1Dd:-MfCVx7q7FH6Lmk-oiub:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/769881aaa133b3bcddea619a3daa5c685ff5cafb/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CompositeBeaconProcessor.java#L30)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> is_error
> ```
Java variables are named using camel-casing, so, just use `isError` instead of `is_error`
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 268 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1122#-MeP_m1L8bjTlOFeJCxI:-MfCVy-A4rVsvQ5Q5rQw:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/769881aaa133b3bcddea619a3daa5c685ff5cafb/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L268)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

The `is_error` tag is missing here
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CompositeBeaconProcessorTest.java, line 24 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1122#-MeP_Ia43GYKQfCzTgir:-MfCW-boAfgQ6r4iGTSo:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/769881aaa133b3bcddea619a3daa5c685ff5cafb/components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CompositeBeaconProcessorTest.java#L24)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

This mock is not used. Please revert this file when no change is done.
</blockquote></details>

Done.

**Review by mariusoe — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patrick-Eichhorn)

**Review by mariusoe — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patrick-Eichhorn)

**Pull request merged**
