### PR TITLE
Closes #977 - EUM server can export received beacons via http

### LINKED ISSUE #977: Extend EUM server in order to export all received Boomerang beacons into an Elasticsearch
Currently, the EUM server allows to record metrics based on beacons (JSON objects) sent by Boomerang. For this, metrics will be derived of the beacon's attributes.

In this ticket, the EUM server should be extended by a feature, allowing users to export all received beacons into an Elasticsearch (or Logstash). Doing this, users can analyse the beacons outside the EUM server or use AI feature to process them.

The implementation should focus on the ability to use Logstash as a beacon sink, thus, it can be used to filter and pretransform beacons before storing them in an Elasticsearch.

### PR DESCRIPTION
**Pull request by mariusoe**
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/984)

### CODE REVIEW

**Comment by SaschaBrechmannVHV** [comment]
I think, the elastic logstash receiver you are think of is this one?
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html
I have some questions about this:
1. Did the Push respects the http status-code (429; busy), as shown in the documentation: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html#_blocking_behavior
2. How about Authentication? could one provided user/password?
3. How about SSL-Endpoint? How about enterprise CA SSL for the Endpoint?
4. Did you send the "application/json" Encoding header?
5. How about "spooling" if the Endpoint is not available?

Regards, Sascha

**Review by Patrick-Eichhorn — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/984)* status: all files reviewed, 4 unresolved discussions (waiting on @mariusoe)

___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 176 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/984#-MS2rp90E-haxoKGd0_s:-MS2rp90E-haxoKGd0_t:bi7robl) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/bff4d211f4b093eeb931fcd347778bf3b34c2b7f/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L176)):*
> ```YAML
>         unit: amount
>         views:
>           '[inspectit-eum/self/beacons_received/COUNT]':
> ```

Should metrics ending in ".../count" be either upper or lower case? (Metrics ending in ".../sum" are lower case)
___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 186 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/984#-MS2sMfR8D7zvMr1q_jo:-MS2sMfR8D7zvMr1q_jp:b6qazhq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/bff4d211f4b093eeb931fcd347778bf3b34c2b7f/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L186)):*
> ```YAML
>         views:
>           # the amount of beacon exports
>           '[inspectit-eum/self/beacons_export/COUNT]':
> ```

/COUNT lower or upper case?
___
*[components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporterTest.java, line 146 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/984#-MS2tT2_C3-5JXd1Ezuq:-MS2tT2_C3-5JXd1Ezur:b-5qmopb) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/bff4d211f4b093eeb931fcd347778bf3b34c2b7f/components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporterTest.java#L146)):*
> ```Java
>             assertThat(nextBeaconBuffer).isEmpty();
>         }
> ```

Should the flush interval still be tested?
___
*[inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md, line 392 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/984#-MS2sfja5xxzZTiCcN1q:-MS2sfja5xxzZTiCcN1r:b-sk7p5a) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/bff4d211f4b093eeb931fcd347778bf3b34c2b7f/inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md#L392)):*
> ```Markdown
> | Metric name | Description |
> | --- | --- |
> | `inspectit_eum_self_beacons_received_count` | Counts the number of received beacons | 
> ```

/COUNT lower or upper case (see previous comments)

**Comment by mariusoe** [comment]
Hi @SaschaBrechmannVHV 

exactly, that Logstash input plugin can be used as a data sink for the server.

Regarding your questions:

> 1. Did the Push respects the http status-code (429; busy), as shown in the documentation

No, this was not respected but I think it make sense to implement this as well in order to protect the endpoint.

>2.  How about Authentication? could one provided user/password?

No. The abbility to provide an authentication for the HTTP endpoint will be implemented in a follow up ticket.

> 3. How about SSL-Endpoint? How about enterprise CA SSL for the Endpoint?

Yes, that is supported. HTTPS endpoint are supported, as long as the certificates are correctly configured for the JVM executing the EUM server.

> 4. Did you send the "application/json" Encoding header?

Yes, `application/json` will be used as content-type header.

> 5. How about "spooling" if the Endpoint is not available?

Do you mean that the beacons should be buffered in case the HTTP endpoint is not available? Currently, we will drop the data in case the HTTP endpoint is not available in order to protect the EUM server. Because the beacons can be quite big, depending on what data they contain, thus, buffering a lot of data/beacons can lead to a very high memory consumtion of the EUM server.
I think this behavior is similar to Logstash, because (as far as I know) it will also drop data e.g. if the data output will fail. Or am I wrong on this point?

**Comment by SaschaBrechmannVHV** [comment]
> Do you mean that the beacons should be buffered in case the HTTP endpoint is not available? Currently, we will drop the data in case the HTTP endpoint is not available in order to protect the EUM server. Because the beacons can be quite big, depending on what data they contain, thus, buffering a lot of data/beacons can lead to a very high memory consumption of the EUM server.
> I think this behaviour is similar to Logstash, because (as far as I know) it will also drop data e.g. if the data output will fail. Or am I wrong on this point?

Thx for your answers. This is OK. I would only be clear about this point. 
Spooling could be done on Disk, to avoid to much RAM usage. 
Your are right about the logstash behaviour. For that reason one would uses Kafka or Redis as Broker and splitt logstash in frontend (receiver) and backend (filter, parsing, storage) processing. 

Regards, Sascha

**Review by mariusoe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/984)* status: all files reviewed, 4 unresolved discussions (waiting on @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 176 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/984#-MS2rp90E-haxoKGd0_s:-MS3UnzfAvgxZhAoVOzC:b-unatj8) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/bff4d211f4b093eeb931fcd347778bf3b34c2b7f/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L176)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

Should metrics ending in ".../count" be either upper or lower case? (Metrics ending in ".../sum" are lower case)
</blockquote></details>

I changed this one also to lower case. Imo this is more consistent than upper case. I've also added this to the "breaking changes" sectionm just in case :)
___
*[components/inspectit-ocelot-eum-server/src/main/resources/application.yml, line 186 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/984#-MS2sMfR8D7zvMr1q_jo:-MS3Uncc9ywgsZiceSPa:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/bff4d211f4b093eeb931fcd347778bf3b34c2b7f/components/inspectit-ocelot-eum-server/src/main/resources/application.yml#L186)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

/COUNT lower or upper case?
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporterTest.java, line 146 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/984#-MS2tT2_C3-5JXd1Ezuq:-MS3WxAuDIMzFypv5C-Q:bjy3ytk) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/bff4d211f4b093eeb931fcd347778bf3b34c2b7f/components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporterTest.java#L146)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

Should the flush interval still be tested?
</blockquote></details>

I would skip it for now. Maybe this is changed soon in order to support delaying requests (if the target endpoint is under load).
___
*[inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md, line 392 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/984#-MS2sfja5xxzZTiCcN1q:-MS3WbUTDmihnjwpE6_6:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/bff4d211f4b093eeb931fcd347778bf3b34c2b7f/inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md#L392)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

/COUNT lower or upper case (see previous comments)
</blockquote></details>

Done.

**Review by Patrick-Eichhorn — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/984)* status: all files reviewed, 1 unresolved discussion (waiting on @Patrick-Eichhorn)

**Review by Patrick-Eichhorn — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/984)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mariusoe)

**Pull request merged**
