### PR TITLE
Closes #1076 - Extend the graphical configuration view in order to support the creation of new scopes

### LINKED ISSUE #1076: Extend the graphical configuration view in order to support the creation of new scopes
In this ticket, the graphical configuration view of the configuration UI is to be extended so that it is possible for users to create new scopes. The [scope wizard dialog (#1075)](#1075) is to be used so that users can easilycreate a scope.

To be able to create scopes, an "Add" button shall be provided. When a scope is created, the YAML of the configuration shall be adjusted, but not saved. To save the change, the user must explicitly use the "Save" button.

A scopes should have a unique name, also stating that it has been generated in some way.

### PR DESCRIPTION
**Pull request by Patrick-Eichhorn**
closes #1076

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099)

### CODE REVIEW

**Review by mariusoe — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @mariusoe and @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js, line 92 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-MbM0MFyAvy6YWrNqCQ9:-MbM0MFyAvy6YWrNqCQA:b-21uzp9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dcd236c4edd0850830ff47cc1a8f8992111cee28/components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js#L92)):*
> ```
> Class
> ```
Type...
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js, line 96 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-MbM0STi4oIDj5yIZYNL:-MbM0STi4oIDj5yIZYNM:b-h8b9wb) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dcd236c4edd0850830ff47cc1a8f8992111cee28/components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js#L96)):*
> ```
> let 
> ```
const
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js, line 107 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-MbM0zDO2V2N9uKn7SAg:-MbM0zDO2V2N9uKn7SAh:b-alazs9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dcd236c4edd0850830ff47cc1a8f8992111cee28/components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js#L107)):*
> ```JavaScript
> 
>     if (_.isEmpty(methodMatcherType) ^ _.isEmpty(methodName)) {
>       throw new Error('Either the methodMatcherType AND methodName must be specified, or neither of them!');
> ```

Imo we can just ignore the type in case no name is specified. Maby
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js, line 121 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-MbM1dGM6WffTlTvX5P8:-MbM1dGM6WffTlTvX5P9:bhjifm3) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dcd236c4edd0850830ff47cc1a8f8992111cee28/components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js#L121)):*
> ```JavaScript
>     const scope = { [scopeName]: _.merge(classMatcherScope, { methods: [methodMatcherBody] }) };
>     // prepare rule Scope
>     const ruleScope = { scopes: { [scopeName]: false } };
> ```

Let's enable them by default - users will most likely add them when they also want to use them
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js, line 139 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-MbLzmrZ4J76vOU-qP0A:-MbLzmrZ4J76vOU-qP0B:b-v1fju7) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dcd236c4edd0850830ff47cc1a8f8992111cee28/components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js#L139)):*
> ```
> writeScope 
> ```
How about `addScope`?
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js, line 141 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-MbM-5BoEC53v_2rf1yZ:-MbM-5BoEC53v_2rf1y_:b-gb8kq4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dcd236c4edd0850830ff47cc1a8f8992111cee28/components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js#L141)):*
> ```
> _numb
> ```
I think this will not work because as soon the browser is restarted, the `uniqueId` function will return the same number as before.

We should also use a more expressive name like `s_generated_scope_`

For me, a UUID would also be fine. So the output could be like `s_gen_scope_109156be-c4fb-41ea-b1b4-efe1671c5836`
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/ScopeWizardDialog.js, line 17 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-MbM3q3d-uWCvbft-niC:-MbM3q3e7GJLXREWKOYl:b-f7gqeb) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dcd236c4edd0850830ff47cc1a8f8992111cee28/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/ScopeWizardDialog.js#L17)):*
> ```JavaScript
> const ScopeWizardDialog = ({ visible, onHide, onApply }) => {
>   const [typeMatcher, setTypeMatcher] = useState({ type: 'type', matcherType: 'EQUALS_FULLY', name: null });
>   const [methodMatcher, setMethodMatcher] = useState({
> ```

Ah, these state variables will become a problem, because they are only set once and are not resetted - when the dialog is mounted. So when the dialog is closed and reopened, some of the values will still exist.

Use an effect which depends on the `visible` property which resets the state when the dialog is opened:

```
useEffect(() => {
  if (visible) {
    ...
  }
}, [visible]);
```

**Review by mariusoe — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099)* status: all files reviewed, 7 unresolved discussions (waiting on @Patrick-Eichhorn)

**Review by Patrick-Eichhorn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099)* status: all files reviewed, 7 unresolved discussions (waiting on @mariusoe)

___
*[components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js, line 92 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-MbM0MFyAvy6YWrNqCQ9:-MbM6e1xDv-mjZ0T9gQf:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dcd236c4edd0850830ff47cc1a8f8992111cee28/components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js#L92)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> Class
> ```
Type...
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js, line 96 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-MbM0STi4oIDj5yIZYNL:-MbM6ivS-MjZ3QOhueIK:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dcd236c4edd0850830ff47cc1a8f8992111cee28/components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js#L96)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> let 
> ```
const
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js, line 107 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-MbM0zDO2V2N9uKn7SAg:-MbM6x5Y0yqqyV2tYD_D:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dcd236c4edd0850830ff47cc1a8f8992111cee28/components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js#L107)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Imo we can just ignore the type in case no name is specified. Maby
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js, line 121 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-MbM1dGM6WffTlTvX5P8:-MbM70cM0sKX9AAdRAIO:b-5wni7t) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dcd236c4edd0850830ff47cc1a8f8992111cee28/components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js#L121)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Let's enable them by default - users will most likely add them when they also want to use them
</blockquote></details>

Done in next PR #1080
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js, line 139 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-MbLzmrZ4J76vOU-qP0A:-MbM7TzW1B19g9WmdbKT:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dcd236c4edd0850830ff47cc1a8f8992111cee28/components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js#L139)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> writeScope 
> ```
How about `addScope`?
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js, line 141 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-MbM-5BoEC53v_2rf1yZ:-MbMAXl-5g_baydHAG3j:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dcd236c4edd0850830ff47cc1a8f8992111cee28/components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js#L141)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> _numb
> ```
I think this will not work because as soon the browser is restarted, the `uniqueId` function will return the same number as before.

We should also use a more expressive name like `s_generated_scope_`

For me, a UUID would also be fine. So the output could be like `s_gen_scope_109156be-c4fb-41ea-b1b4-efe1671c5836`
</blockquote></details>

Done.
___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/ScopeWizardDialog.js, line 17 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-MbM3q3d-uWCvbft-niC:-MbM7Ulw7Ob3kYR5SN8Z:btz3h89) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/dcd236c4edd0850830ff47cc1a8f8992111cee28/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/ScopeWizardDialog.js#L17)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Ah, these state variables will become a problem, because they are only set once and are not resetted - when the dialog is mounted. So when the dialog is closed and reopened, some of the values will still exist.

Use an effect which depends on the `visible` property which resets the state when the dialog is opened:

```
useEffect(() => {
  if (visible) {
    ...
  }
}, [visible]);
```
</blockquote></details>

Done in next PR #1080

**Review by Patrick-Eichhorn — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099#-:-MbMB6G79NpHXZ-_YwVD:bnfp4nl)* status: 6 of 10 files reviewed, 7 unresolved discussions (waiting on @mariusoe)

**Pull request merged**
