### PR TITLE
Closes #1407 - Insert events into preloaded logs

### LINKED ISSUE #1407: [Feature] - Insert events into preloaded logs
**Is your feature request related to a problem? Please describe.**
The new agent command to retrieve logs is nice, but I would like to know better when some relevant events happened when viewing the logs. For example, when a new instrumentation config was fetched, old instrumentation logs get outdated. However, the default log-preloading config only considers `WARN` and `ERROR` logs, which don't contain the `INFO` messages about newly applied instrumentation.

**Describe the solution you'd like**
I would like the agent to put artificial log entries into the preloaded logs that mark certain events (such as instrumentation) occur.

**Describe alternatives you've considered**
An alternative would be to throw away instrumentation logs whenever new instrumentations are applied, which is however very complex to realize. Also, we don't really benefit from throwing away the logs and there might be edge cases where the "outdated" logs are still interesting.

**Additional context**
As we plan to connect the log retrieval with a health status indicator, the artificial log entries will also help understanding the current health, as it is based on the same logs and events.

### PR DESCRIPTION
**Pull request by Henning-Schulz**
Artificially added log events will look like follows.

`2022-04-29 10:47:42,709 INFO  33860  --- [inspectIT] [pectit-thread-1] ### LOG-INVALIDATING EVENT ###           : Property sources reload! Some previous log messages may now be outdated.`

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1411)

### CODE REVIEW

**Comment by Henning-Schulz** [comment]
Now without beginner's mistakes 😄

**Review by MariusBrill — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1411)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Henning-Schulz and @MariusBrill)

___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/LogPreloader.java` line 65 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1411#-N13x1iA8-vc4V1Y1f0U:-N13x1iB4JhiOO__ijK7:b-rrm3tv) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c386525f21169456f82e8703414b749d2d9a9848/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/LogPreloader.java#L65)):*
> ```Java
>         if (invalidator != null) {
>             String invalidationString = invalidator.getClass().getSimpleName();
>             if (invalidationString.endsWith("Event")) {
> ```

I am not quite sure why we need this. Maybe we could have a short call about it?

**Review by Henning-Schulz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1411)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @MariusBrill)

___
*[`inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/LogPreloader.java` line 65 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1411#-N13x1iA8-vc4V1Y1f0U:-N143bfG6sZIN9lQbt_6:bsj7jsb) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/c386525f21169456f82e8703414b749d2d9a9848/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/LogPreloader.java#L65)):*
<details><summary><i>Previously, MariusBrill (Marius Brill) wrote…</i></summary><blockquote>

I am not quite sure why we need this. Maybe we could have a short call about it?
</blockquote></details>

It is for formatting the log message. I added a comment and changed the code a little to make it better understandable.

**Review by MariusBrill — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1411)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Henning-Schulz)

**Pull request merged**
