### PR TITLE
Closes #1042 - Add client header information as beacon fields

### LINKED ISSUE #1042: Add client header information as beacon fields

### PR DESCRIPTION
**Pull request by Patrick-Eichhorn**
closes #1042

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1043)

### CODE REVIEW

**Review by mariusoe — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1043)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @mariusoe and @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/Beacon.java, line 40 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1043#-MYAAeNPAoh7-5ZKmtiS:-MYAAeNPAoh7-5ZKmtiT:bt8v0f9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/0b4cf255c8bde186f4d8ee9d8be91c29553f748a/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/Beacon.java#L40)):*
> ```Java
>      * @return a new {@link Beacon} instance
>      */
>     public static Beacon of(Map<String, String> beaconMap, Map<String, String> clientHeaderMap) {
> ```

Hmm, I have to say that I would rather keep the Beacon class without specific application logic and more like a container.
So, the beacon should not care whether a parameter is sent by the user, a request parameter or anything else.

Due to this, I think that this logic would be a good fit for another beacon processor. Or what do you think?


In case you are going for a beacon processor, you don't have to pass the request around but you can access it using the following code from anywhere in the app:
```
ServletRequestAttributes requestAttributes = (ServletRequestAttributes) RequestContextHolder.getRequestAttributes();
if (requestAttributes == null) {
    return null;
}

HttpServletRequest request = (requestAttributes).getRequest();
```

Then you can read the headers and merge them into the beacon.

```
HttpServletRequest request = getCurrentRequest();
if (request == null) {
    return beacon;
}

Map<String, String> requestHeaders = Collections.list(request.getHeaderNames())
        .stream()
        .collect(Collectors.toMap(Function.identity(), headers -> Collections.list(request.getHeaders(headers))
                .stream()
                .map(header -> HEADER_PREFIX + header)
                .collect(Collectors.joining(","))));

return beacon.merge(requestHeaders);
```

Thisway, the beacon class doesn't have to be touched and acts just like a container.

--- The following is regarding testing the proposed approach

If you want to add unit tests, the static method for accessing the request makes it a bit difficult. But it should work when you wrap it in a supplier and replace it with a dummy one inside your tests.
E.g. you can put the static request access logic inside a separate method and call it via a supplier:

```
Supplier<HttpServletRequest> requestSupplier = this::getCurrentRequest;
// .....
HttpServletRequest httpServletRequest = requestSupplier.get();
```

In your test, you can replace that supplier with a dummy one:
```
requestSupplier = () -> {
  return mockRequest;  
};

I hope I didn't confused you too much - but let's talk in case you have any questions :)
```
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/Beacon.java, line 41 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1043#-MYAATxo5jFIMUuZm9wI:-MYAATxp5Mix_uPXMNYA:b6a97h9) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/0b4cf255c8bde186f4d8ee9d8be91c29553f748a/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/Beacon.java#L41)):*
> ```
> "client.header."
> ```
Please extract this in a static, final variable, so we don't have magic strings

**Review by Patrick-Eichhorn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1043)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @mariusoe and @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/Beacon.java, line 40 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1043#-MYAAeNPAoh7-5ZKmtiS:-MYdV6Y6CEVpesD6BL4x:b49asxz) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/0b4cf255c8bde186f4d8ee9d8be91c29553f748a/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/Beacon.java#L40)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

Hmm, I have to say that I would rather keep the Beacon class without specific application logic and more like a container.
So, the beacon should not care whether a parameter is sent by the user, a request parameter or anything else.

Due to this, I think that this logic would be a good fit for another beacon processor. Or what do you think?


In case you are going for a beacon processor, you don't have to pass the request around but you can access it using the following code from anywhere in the app:
```
ServletRequestAttributes requestAttributes = (ServletRequestAttributes) RequestContextHolder.getRequestAttributes();
if (requestAttributes == null) {
    return null;
}

HttpServletRequest request = (requestAttributes).getRequest();
```

Then you can read the headers and merge them into the beacon.

```
HttpServletRequest request = getCurrentRequest();
if (request == null) {
    return beacon;
}

Map<String, String> requestHeaders = Collections.list(request.getHeaderNames())
        .stream()
        .collect(Collectors.toMap(Function.identity(), headers -> Collections.list(request.getHeaders(headers))
                .stream()
                .map(header -> HEADER_PREFIX + header)
                .collect(Collectors.joining(","))));

return beacon.merge(requestHeaders);
```

Thisway, the beacon class doesn't have to be touched and acts just like a container.

--- The following is regarding testing the proposed approach

If you want to add unit tests, the static method for accessing the request makes it a bit difficult. But it should work when you wrap it in a supplier and replace it with a dummy one inside your tests.
E.g. you can put the static request access logic inside a separate method and call it via a supplier:

```
Supplier<HttpServletRequest> requestSupplier = this::getCurrentRequest;
// .....
HttpServletRequest httpServletRequest = requestSupplier.get();
```

In your test, you can replace that supplier with a dummy one:
```
requestSupplier = () -> {
  return mockRequest;  
};

I hope I didn't confused you too much - but let's talk in case you have any questions :)
```
</blockquote></details>

Processing the client header attributes in a separate beacon processor is a good idea, therefore this logic is also easier to maintain.
I have adjusted the implementation accordingly.
___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/Beacon.java, line 41 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1043#-MYAATxo5jFIMUuZm9wI:-MYdVX8b-tnM2sKyYTWI:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/0b4cf255c8bde186f4d8ee9d8be91c29553f748a/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/Beacon.java#L41)):*
<details><summary><i>Previously, mariusoe (Marius Oehler) wrote…</i></summary><blockquote>

> ```
> "client.header."
> ```
Please extract this in a static, final variable, so we don't have magic strings
</blockquote></details>

Done.

**Review by Patrick-Eichhorn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1043)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @mariusoe and @Patrick-Eichhorn)

___
*[components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/Beacon.java, line 40 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1043#-MYAAeNPAoh7-5ZKmtiS:-MYdW6zz4fofN704yWlK:b-896fix) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/0b4cf255c8bde186f4d8ee9d8be91c29553f748a/components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/Beacon.java#L40)):*
<details><summary><i>Previously, Patrick-Eichhorn wrote…</i></summary><blockquote>

Processing the client header attributes in a separate beacon processor is a good idea, therefore this logic is also easier to maintain.
I have adjusted the implementation accordingly.
</blockquote></details>

Done.

**Review by mariusoe — APPROVED** [review]
> Reviewed 8 of 8 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1043)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patrick-Eichhorn)

**Pull request merged**
