### PR TITLE
Closes #1546: [Bug] - Agent throws exception if logback config contains net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder

### LINKED ISSUE #1546: [Bug] - Agent throws exception if logback config contains net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder
**Describe the bug**
When the Java application or the inspectIT Ocelot agent is configured to use a custom configuration file (e.g., `-Dlogback.configurationFIle=path/to/logback-config.xml` or `-Dinspectit.logging.config-file:path/to/logback-config.xml`), the agent throws the following exception. This is because the dependency to `net.logstash.logback:logstash-logback-encoder` is missing in inspectIT Ocelot, which is needed by the logback configuration.

Exception:
```Java
07:43:58,896 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [./log/logback-config.xml] at [file:/C:/Users/HHO/dev/inspectit/inspectic-ocelot-playground/./log/logback-config.xml]
07:43:58,950 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
07:43:58,953 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/C:/Users/HHO/dev/inspectit/inspectic-ocelot-playground/./log/logback-config.xml] 
07:43:58,953 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 30 minutes
07:43:58,954 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
07:43:58,956 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
07:43:58,960 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
07:43:58,976 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
07:43:58,976 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [StdoutJsonAppender]
07:43:58,977 |-ERROR in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Could not create component [encoder] of type [net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder] java.lang.ClassNotFoundException: net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder
	at java.lang.ClassNotFoundException: net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder
	at 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at 	at ch.qos.logback.core.util.Loader.loadClass(Loader.java:120)
	at 	at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.begin(NestedComplexPropertyIA.java:102)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:64)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:134)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at 	at rocks.inspectit.ocelot.core.logging.logback.LogbackInitializer.initLogging(LogbackInitializer.java:84)
	at 	at rocks.inspectit.ocelot.core.logging.logback.LogbackInitializer.initDefaultLogging(LogbackInitializer.java:70)
	at 	at rocks.inspectit.ocelot.core.AgentImpl.<clinit>(AgentImpl.java:53)
	at 	at java.lang.Class.forName0(Native Method)
	at 	at java.lang.Class.forName(Class.java:348)
	at 	at rocks.inspectit.ocelot.bootstrap.AgentManager.startOrReplaceInspectitCore(AgentManager.java:40)
	at 	at rocks.inspectit.ocelot.agent.AgentMain.startAgent(AgentMain.java:110)
	at 	at rocks.inspectit.ocelot.agent.AgentMain.lambda$premain$0(AgentMain.java:93)
	at 	at java.lang.Thread.run(Thread.java:748)
```

Logback configuration:
```xml
<configuration scan="true" scanPeriod="30 minutes" packagingData="true">
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <!-- encoders are  by default assigned the type
             ch.qos.logback.classic.encoder.PatternLayoutEncoder -->
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="StdoutJsonAppender" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <mdc>
                    <mdcKeyFieldName>CUSTOM_CORRELATION_ID=correlationId</mdcKeyFieldName>
                    <mdcKeyFieldName>CUSTOM_USERINFO=userId</mdcKeyFieldName>
                </mdc>
                <pattern>
                    <pattern>
                        { "loglevel": "%level", "ibm_datetime": "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}", "type": "iact_message", "loggerName": "%logger","thread": "%thread","message": "%message", "exception": "%exception" }
                    </pattern>
                </pattern>
            </providers>
        </encoder>
    </appender>

    <root level="info">
        <appender-ref ref="StdoutJsonAppender" />
    </root>

</configuration>
```
**To Reproduce**
1. Use the above logback configuration
2. Run the Java application with `-Dlogback.configurationFile=/path/to/logback-configuration.xml`
3. See error

**Expected behavior**
I'd like to be able to use the logback configuration file.

The easiest solution is to add the required dependency to the inspectIT Ocelot agent.

### PR DESCRIPTION
**Pull request by heiko-holz**
Closes #1546

- - -
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1550)

### CODE REVIEW

**Review by heiko-holz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1550)* status: all files reviewed, 2 unresolved discussions (waiting on @quandor)

___
*[`inspectit-ocelot-core/build.gradle` line 64 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1550#-NMEL8P77bPfDjdMn1QW:-NMEWxOnAeL1bQqa06u3:b-j51qd4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/53f6be310a850ff1b73755aa0c43f7d48776538b/inspectit-ocelot-core/build.gradle#L64)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

Is there a reason why you did not chose the most current version 7.2 (https://central.sonatype.dev/artifact/net.logstash.logback/logstash-logback-encoder/7.2)?
</blockquote></details>

Valid point.
I chose the version that was used in another project. I have upgraded the version accordingly.
___
*[`inspectit-ocelot-core/build.gradle` line 66 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1550#-NMELZmZ0GgDHp-_6zkV:-NMEXJa37wPDXR-gR8va:by3bwx4) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/53f6be310a850ff1b73755aa0c43f7d48776538b/inspectit-ocelot-core/build.gradle#L66)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

This is basically the only change. The rest is either formatting or an according test. If I am mistaken, please show me other code that changed.
</blockquote></details>

You are correct.
inspectIT Ocelot was already capable of loading custom logback files.

I just added the support of`net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder` and other encoder provided by logstash.

I have thus just added the dependency and created a test `LogbackInitializerTest.CustomLogFileWithLogstash` for this scenario.

**Review by quandor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1550#-:-NMEYq_G4z1mcJYh9GVx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @heiko-holz)

___
*[`inspectit-ocelot-core/build.gradle` line 66 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1550#-NMELZmZ0GgDHp-_6zkV:-NMEYjrt2JfL-V6LY1MP:b-3kvwns) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/53f6be310a850ff1b73755aa0c43f7d48776538b/inspectit-ocelot-core/build.gradle#L66)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

You are correct.
inspectIT Ocelot was already capable of loading custom logback files.

I just added the support of`net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder` and other encoder provided by logstash.

I have thus just added the dependency and created a test `LogbackInitializerTest.CustomLogFileWithLogstash` for this scenario.
</blockquote></details>

LGTM. That's how I understood the file changes, too.

**Review by quandor — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1550)* status: all files reviewed, 1 unresolved discussion (waiting on @heiko-holz)

___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/rules/RuleTracingSettings.java` line 100 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1550#-NMEc9UA9TVBjagQBP4j:-NMEc9UA9TVBjagQBP4k:b-omukkb) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/64f2f6f3e02e156451e3dcd95e14faab2dfd2227/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/rules/RuleTracingSettings.java#L100)):*
> ```Java
>      * The default {@link SampleMode sample mode} used for the {@link #sampleProbability}. Defaults to {@link TracingSettings#getSampleMode() inspectit.tracing.sample-mode}  if not set and {@link #sampleProbability} is used.
>      */
>     @Builder.Default
> ```

Was that intentional?

**Review by heiko-holz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1550)* status: all files reviewed, 1 unresolved discussion (waiting on @quandor)

___
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/rules/RuleTracingSettings.java` line 100 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1550#-NMEc9UA9TVBjagQBP4j:-NMEcKa6AWZBouHoNRXN:b-mwemf7) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/64f2f6f3e02e156451e3dcd95e14faab2dfd2227/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/rules/RuleTracingSettings.java#L100)):*
<details><summary><i>Previously, quandor (Jochen Just) wrote…</i></summary><blockquote>

Was that intentional?
</blockquote></details>

Yes, 
actually this should have been fixed in the original PR of the auto tracing feature, but somehow I forgot.
Gradle reminded me of this when I was building the `THIRD-PARTY-LICENSES.txt` :D

**Comment by heiko-holz** [comment]
*[`inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/rules/RuleTracingSettings.java` line 100 at r3](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1550#-NMEc9UA9TVBjagQBP4j:-NMUUFpmBxf4Nyf_gLAX:b-2820dm) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/64f2f6f3e02e156451e3dcd95e14faab2dfd2227/inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/rules/RuleTracingSettings.java#L100)):*
<details><summary><i>Previously, heiko-holz (Heiko Holz) wrote…</i></summary><blockquote>

Yes, 
actually this should have been fixed in the original PR of the auto tracing feature, but somehow I forgot.
Gradle reminded me of this when I was building the `THIRD-PARTY-LICENSES.txt` :D
</blockquote></details>

I reverted this and moved it to another issue: https://github.com/inspectIT/inspectit-ocelot/issues/1565

**Review by quandor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1550#-:-NMXYPDQ-_gdfQDqSDmM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @heiko-holz)

**Pull request merged**
